### ISSUE TITLE
:dart: Welcome: Spoiler / Issues / Contribution / Discussions / Feedback

### ISSUE THREAD

**Issue by Lurkars** [Lurkars/gloomhavensecretariat#104]
# Welcome 

Here are some short infos/guidelines about this repository. My timezone is GMT+1, so just as info when I am giving ETAs like *today*.

## Spoiler

Please take a look at [Spoiler Warnings](https://github.com/Lurkars/gloomhavensecretariat/discussions/103)!

## Issues

You should create an issue if you
- experience any bug/technical issues ("I cannot add curses to AM deck!")
- have a concrete feature request ("Please add keyboard shortcut for drawing AM")

If you just have ideas or want to discuss behavior, please create a [Discussion](#Discussions).

Every issue should contain a detailed description of the problem/improvement. Depending on the problem, please provide the following information
- GHS Version (you found the number in *Menu* under *About*)
- Browser/OS
- if server is used: self-hosted or public
- if you referring to a scenario/section always provide edition (short version is enough)

### Issue workflow

I am using a simple issue workflow by using the label function
- mostly two categories, to categorize the issue 
  - https://github.com/Lurkars/gloomhavensecretariat/labels/bug for issues 
  - https://github.com/Lurkars/gloomhavensecretariat/labels/enhancement for improvements/new features
- issue states
  - https://github.com/Lurkars/gloomhavensecretariat/labels/in%20progress currently working on this
  - https://github.com/Lurkars/gloomhavensecretariat/labels/to%20test this should be fixed/done, but needs to be verified
  - https://github.com/Lurkars/gloomhavensecretariat/labels/backlog will be worked on in the future, but not yet 
  - https://github.com/Lurkars/gloomhavensecretariat/labels/pending if more information or feedback is required to determine the issue (so mostly issue is assigned back to creator)
  - https://github.com/Lurkars/gloomhavensecretariat/labels/wontfix this will not be worked on (mostly then closed afterwards)

In most cases, I would mark a new issue as https://github.com/Lurkars/gloomhavensecretariat/labels/backlog or https://github.com/Lurkars/gloomhavensecretariat/labels/in%20progress (when directly start working on it) and assign it to me. After the issue is solved, it will remain open and going in https://github.com/Lurkars/gloomhavensecretariat/labels/to%20test  assigning the issue back to the report to verify the fix.

## Contribution

I am really happy about any contribution. Please just use a brief description about what your PR does. It's easier to validate your PR if the description already saying "fixes standee data in GH scenario \# 5" than me looking at the files and trying to determine this information.

## Discussions

The GitHub Discussion section is for everything that involves a bit more conversation:
- [:pray: Q&A](https://github.com/Lurkars/gloomhavensecretariat/discussions/categories/q-a): If you just need help or other questions
- [:bulb: Ideas](https://github.com/Lurkars/gloomhavensecretariat/discussions/categories/ideas) If you have an idea, but need more input or want to give/get feedback
- [:ballot_box: Polls](https://github.com/Lurkars/gloomhavensecretariat/discussions/categories/polls): This will mostly come out from an Idea discussion, if some ideas may conflict, we can start a poll. Other use cases would be to get community feedback about what to prioritize

Use the label https://github.com/Lurkars/gloomhavensecretariat/labels/feedback, https://github.com/Lurkars/gloomhavensecretariat/labels/help%20wanted or https://github.com/Lurkars/gloomhavensecretariat/labels/question for marking your discussion category.

**Comment by itemforty** [comment]
Is there a single place you'd prefer we add typos? Making a single issue for each one seems like overdoing it.

**Comment by Lurkars** [comment]
Currently not, but just create one with all you got.

**Comment by ruanmed** [comment]
Hi @Lurkars , I could work in a translation for Portuguese (Brazilian) - pt-BR for the application, based on [the official translated version of Gloomhaven published in Brazil by Galápagos Jogos](https://www.mundogalapagos.com.br/gloomhaven/produto/GLH001) that I own.

Since there are already three different language localizations here (de, fr and kr), would you know if I need to get any permission from Galápagos Jogos in Brazil to use the same terms they used in their translations? 
My concern is if I'd be breaking any copyright they have for the translations (if that's even possible), or if using their translations here would fall under fair use regardless.

**Comment by Lurkars** [comment]
> Hi @Lurkars , I could work in a translation for Portuguese (Brazilian) ....

Moved this to a new issue, since this not the place to discuss. #589
