### ISSUE TITLE
Marking a scenario as completed unlocks scenarios from other editions with campaign mode enabled.

### ISSUE THREAD

**Issue by MisuVir** [Lurkars/gloomhavensecretariat#106]
In the campaign sheet with Campaign Mode enabled, marking scenario 1 "Black Barrow" as completed correctly makes scenario 2 "Barrow Lair" available, but also makes JotL scenario 2 "A Hole in the Wall" appear as available. The expected result would be that only Barrow Lair becomes available and other edition scenarios are not affected. The inverse happens when marking JotL scenario 1 as completed - all the scenario 2's in the other editions become available.

This appears to affect all editions. If you complete scenario 1 in any edition, it unlocks scenario 2 for all editions.

<img width="444" alt="Screenshot" src="https://user-images.githubusercontent.com/8415993/216474713-de860646-6f45-4fa1-91d3-5916af475317.png">

**Comment by Lurkars** [comment]
Ough, okay. Will be fixed soon!

**Comment by Lurkars** [comment]
Please verify fix in [v0.43.4](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.43.4)

**Comment by MisuVir** [comment]
Looks good to me.
