### ISSUE TITLE
Drag for modifying HP and XP doesn't work in second column

### ISSUE THREAD

**Issue by dfannius** [Lurkars/gloomhavensecretariat#114]
v0.43.7 standalone app (installed the .dmg file) on a macOS laptop. When I click and drag to modify HP or XP on a card in the right column, it acts as if the anchor point for the drag were in the left column. so the drag starts out applying an extremely positive change, and bringing the mouse all the way over to the corresponding point in the first column eventually brings the change back down to 0.

**Comment by Lurkars** [comment]
Will take a look later.

**Comment by Lurkars** [comment]
Sorry, I cannot reproduce in any case (and don't have any Apple device). So I think we have to investigate further and you need to provide some more details. Is this always happening when in 2-column?

**Comment by dfannius** [comment]
It's a little harder to reproduce than I thought. It seems that maybe you have to first click and drag while the card is in the left column, and then maybe some value is not getting reset when the card changes columns. Try this (it just worked for me):

- Start a scenario with enough characters and monsters to require two columns.
- Select initiatives so that some character (I'll call it A) will be in the left column.
- Click Draw to start the round.
- Click and drag A's hit points to the left to reduce it.
- Click Next Round.
- Select initiatives so that A will be in the right column.
- Click Draw to start the round.
- Click and drag A's hit points.

**Comment by Lurkars** [comment]
Thanks I could reproduce and will provide a fix. Just didn't reset the previous dragged value after dragging. So hopefully easy fix.

**Comment by Lurkars** [comment]
Should be fixed with [v0.44.2](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.44.2), please verify.

**Comment by dfannius** [comment]
Looks good - I tried my recipe and it worked fine.
