### ISSUE TITLE
[BUG] Curses are removed on enemy death 

### ISSUE THREAD

**Issue by pakoito** [Lurkars/gloomhavensecretariat#116]
Curses are applied for all enemies, but the game tracks them per individual enemy. When an enemy is removed, their curses get removed from the deck too.

**Comment by Lurkars** [comment]
I removed automatically scenario reset when removing last monster, please verify in [v0.44.2](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.44.2)

**Comment by pakoito** [comment]
Feels like it works as expected now, thanks :D
