### ISSUE TITLE
[Suggestion] Toggle to make Attack decks and status panel always visible

### ISSUE THREAD

**Issue by pakoito** [Lurkars/gloomhavensecretariat#119]
The centered UI looks great, but leaves some space on the sides that could be used for more buttons and controls, instead of having them under states and modals.

![e](https://user-images.githubusercontent.com/514871/218257910-1bc1b3c1-110c-4a22-af4b-16baa533400b.png)

**Comment by pakoito** [comment]
It's awesome to see the progress of other features happening in real time, by the way :D I'm like 20 scenarios in using the app, and the latest changes to health tracking and the loot deck are life-savers.

**Comment by Lurkars** [comment]
I see, but makes it too difficult for me to handle those views then:

Two Column mode on wide screens
![Two-Column Desktop](https://user-images.githubusercontent.com/2760570/218266836-de291774-63e9-4ce5-aaa7-c610d581fc10.png)

Mobile Device with small sceen
![Mobile Device](https://user-images.githubusercontent.com/2760570/218266860-d928f9ca-e0f7-42b8-be7d-7a63311f286b.png)

So I don't think I will do something like this. I am working on a special character view, which will be optimized for just managing one single character on the screen.
