### ISSUE TITLE
Images missing for some AttackModifierType's

### ISSUE THREAD

**Issue by jsvanderlaan** [Lurkars/gloomhavensecretariat#121]
In `attackmodifierdeck-dialog` you can edit the attackmodifier deck, but for some of the `AttackModifierType`'s the image is missing.
As far as I can tell for `plus`, `minus`, `empower` and `enfeeble`. 

Maybe add them to the exception list in `AttackModifierDeckDialogComponent.changeType`, just as for `invalid`, `plus3` and `plus4`, but I'm not sure if you are not supposed to add these, or that just the image is missing.

![image](https://user-images.githubusercontent.com/36159302/218301807-c7e36a0f-1516-4bd6-aa0a-036ff74288d4.png)
![image](https://user-images.githubusercontent.com/36159302/218301815-63b8556f-292a-43be-8dcc-4bf3dc8fd02e.png)

**Comment by Lurkars** [comment]
Thanks, that's correct. First need to remove those. Empower and enfeeble is still WIP for Trail of Ashes. So not implemented anyways and the plus and minus one added for the Town Guard Perks. Just forgot to remove them from the menu, will fix it.

**Comment by Lurkars** [comment]
Should be fixed in [v0.45.1](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.45.1)

**Comment by Lurkars** [comment]
Please close when verified.
