### ISSUE TITLE
Damage suffer colour to white to fit with text

### ISSUE THREAD

**Issue by EnSnack** [Lurkars/gloomhavensecretariat#124]
Currently the `%game.action.damage%` symbol looks as such, slightly off from the text:
![image](https://user-images.githubusercontent.com/114947600/218325306-01d0c4ce-988a-4c70-b8de-61dee9154d17.png)

**Comment by Lurkars** [comment]
Ah it's on objectives actions!?

**Comment by Lurkars** [comment]
Will be fixed

**Comment by Lurkars** [comment]
Check comment to #123 .
