### ISSUE TITLE
'Undo' does not revert the previous round's monster ability cards

### ISSUE THREAD

**Issue by TheSquinter** [Lurkars/gloomhavensecretariat#126]
If you use the Undo button to go to a previous round, the monster ability cards do not always revert. This appears to only affect cards that were shuffled due to the shuffle icon present.

**Comment by Lurkars** [comment]
Sounds bad, I hope I know what the issue is. Will be fixed. Thanks for noticing!

**Comment by Lurkars** [comment]
Should be fixed in [v0.45.3](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.45.3). Please verify and close issue if solved.

**Comment by TheSquinter** [comment]
Looking good now. Nice work!
