### ISSUE TITLE
Additional loot cards

### ISSUE THREAD

**Issue by TheSquinter** [Lurkars/gloomhavensecretariat#130]
Potentially a spoiler, but when you are advised to add loot card 1418 (and presumably 1419), the card is intended to be added to all scenario loot decks in addition to the normal loot table until all sections have been marked off.

I cannot see a way to add this permanently without using the 'edit' > 'show loot table' option on the loot deck and adding special card 1 manually at the start of each scenario. Would it also be possible to have a method to track which sections have been marked off? Such as a tick box similar to the +1 enhancements.

The exact wording in the book is: "Add loot card 1418 to every scenario loot deck in addition to the normal loot distribution. When drawn, read any one section number depicted."

**Comment by Lurkars** [comment]
Okay, will think about where to set this properly.

**Comment by UChess1986** [comment]
Theres also enhancements you can make to loot.

**Comment by orphu** [comment]
You can already add +1 enhancements to loot cards. Click the double-arrow "expand" icon on the deck and then "+1 enhancements"

**Comment by TheSquinter** [comment]
Yep but this is different to enhancements. It’s the additional 2 loot cards you’re given in the loot deck but not used until told so during the campaign.

**Comment by Lurkars** [comment]
> Yep but this is different to enhancements. It’s the additional 2 loot cards you’re given in the loot deck but not used until told to during the campaign. 

I only can repeat:

If you open the popup, there is a button "+1 enhancements", there you can enhance cards. Has nothing to do with "edit deck" and changing loot table!

**Comment by Lurkars** [comment]
I now edit persistence to the special cards, so when you add/remove 1418/1419, it will be added/removed for future scenarios. Please verify in [v0.45.5](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.45.5)

**Comment by Lurkars** [comment]
I also prepared marking the sections on the cards, but that's not done yet. I spoiled myself the sections and I think I will also implement the rewards/effects directly. Looks dooable. But yes, that all comes in the future.

**Comment by TheSquinter** [comment]
The additional loot cards are now persistent between scenarios. Thanks!

**Comment by itemforty** [comment]
Sorry to necro this, but I'm curious how it works in-game. I see that it's added to the loot decks, but should we expect to have the physical card to read the sections and check them off? Or is there a long press or other setting to make it all work digitally?

**Comment by Lurkars** [comment]
I think the initial issue was about that adding the card to the loot deck was not persistent, not about exactly adding the sections. Anyways, I commented about adding the feature and then seem to forgot about this. So yeah, currently it's not possible to check the sections on a loot card, but I wanted to add this. So I reopen the issue and will work soon on this so that you can mark the corresponding section etc.

**Comment by Lurkars** [comment]
So added an initial implementation now in [v0.80.6](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.80.6). By now, you need to open the Loot Deck dialog and can check every section how you want to. If you want to add a section without applying rewards, double click it. Same applies if you want to remove a section. Hope this is enough for first usage and happy about ideas to improve!

**Comment by itemforty** [comment]
That's so awesome, thank you so much! Just tested and that's perfect for us! You rock
