### ISSUE TITLE
Option to reset round tracker back to 1

### ISSUE THREAD

**Issue by TheSquinter** [Lurkars/gloomhavensecretariat#131]
There are some scenario sections where you are instructed to reset the round tracker back to 1 as part of the scenario special rules.

Would be helpful to have that feature added somewhere if possible! :)

**Comment by Lurkars** [comment]
This is technically implemented (to display/apply rules correctly). I thought it was clever to still show the full round number, but seems better to change this (and maybe show full rounds in brackets behind or).

See https://github.com/Lurkars/gloomhavensecretariat/blob/main/src/app/game/model/data/ScenarioData.ts#L31 (scenario data is also section data, so just yet to true on corresponding sections)

**Comment by Lurkars** [comment]
Since I needed this feature also in the background for applying rules like "after next round", I now added two modes for reset round, one visible and one hidden. So on scenarios explicitly saying "Reset counter to 1", the Round will then show as 1 with the total number in brackets.

**Comment by Lurkars** [comment]
Please check if this works for you as intended in [v0.45.5](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.45.5)

**Comment by TheSquinter** [comment]
Apologies, I'm not seeing where you can set this. Is it scenario/section dependent? For example, I'm checking Scenario 46 which references section 40.2. Is it due to the section data missing?
Thanks again for all your work on this.

**Comment by Lurkars** [comment]
Yes, it's just the data missing. I can quick search the scenario book for corresponding rules and at it.

**Comment by Lurkars** [comment]
I quickly added the sections I could found now. I do not check for other logic now, so maybe section should not be available at beginning of scenario but is now etc. As said, the room and rule data is still lacking.

**Comment by TheSquinter** [comment]
I just checked this again and looks to be all good now, resetting the round and showing the total next to it. Thank you!
