### ISSUE TITLE
Possible bug with Ice Wraith deck / subActions

### ISSUE THREAD

**Issue by EnSnack** [Lurkars/gloomhavensecretariat#137]
So at level 3 and above, Ice Wraith apply one of two conditions based on whether they're elite or not.

Elites apply wound but are melee and have retaliate.
Normals apply curse but are ranged and have shield.

Range in fh/deck/ice-wraith.json is displayed as:
```
"subActions": [
    {
      "type": "range",
      "value": 4,
      "small": true
    }
  ]
```

However, I fear this overwrites the natural ability of normal Ice Wraiths applying curse, here are two examples:
![image](https://user-images.githubusercontent.com/114947600/220209327-f72c9694-37fd-49ea-ae51-0306363ef256.png)

In the top one only the normal one is ranged, however here it does not apply curse, in the bottom one they are both ranged and correctly both of them apply their conditions. I haven't looked at the actual deck, so I'm not sure if it only applies its condition in certain cases, but I thought I'd bring it up.

**Comment by Lurkars** [comment]
Should be fixed in [v0.45.5](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.46.5). Please verify.
