### ISSUE TITLE
Issue on Lurker Mindsnapper ability card. 

### ISSUE THREAD

**Issue by richardhedberg** [Lurkars/gloomhavensecretariat#140]
For Lurker Mindsnappers the ability card "Turn the weak" is wrong. The controlled attack should just be a plain attack 3 and not with target 2, pierce and muddle since it's not the Mindsnapper that performs it.

**Comment by Lurkars** [comment]
Thanks, will be fixed soon. Are there more abilities like this? I have special case for grant abilities, but the text didn't contain the word grant and I may just overlooked it, but that's why this can also affect more abilities...

**Comment by richardhedberg** [comment]
We're just getting started so not sure, but i guess Control is the issue here. There might be more abilities that make monsters control attacks, so maybe you can go through the database and see if there'e any more matches. I'll let you know if i find something else.

**Comment by Lurkars** [comment]
Couldn't find "control" or "grant" (without "grant" as action). So I hope this was the only one and should be fixed in [0.47.4](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.47.4).

**Comment by Lurkars** [comment]
Please verify fix and close on success. (v0.47.4)

**Comment by richardhedberg** [comment]
Amazing work, thank you!
