### ISSUE TITLE
Feature Request: option to group multiple "Objectives" similar to the way monsters are grouped

### ISSUE THREAD

**Issue by itemforty** [Lurkars/gloomhavensecretariat#144]
One thing I would love to see is an option to group multiple objectives together under a single objective type, much like other enemies of the same name. 

Best example of how this could help is any scenario with multiple escorts (e.g. Forgotten Circles #99): 

![image](https://user-images.githubusercontent.com/175024/221653155-07d2df73-8b01-464a-925a-52ce6b192960.png)

It's not a big deal, but it seems like it would take up less room on the screen.

**Comment by Lurkars** [comment]
Is a good idea. I will think about this!

**Comment by Lurkars** [comment]
Will definitely come. I will just add something like standees as for monster.

**Comment by Lurkars** [comment]
I know it's been a while, but I was really busy in fixing all existing stuff. Hopefully I will find time for this now. It's a big change, so yeah we'll see.

**Comment by Lurkars** [comment]
At least I now started with this!

**Comment by Lurkars** [comment]
Pewww, this is now implemented in [v0.74.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.74.0). Really tough one through all the special rules and interfaces. I hope that this will work out now for everyone and that the new bugs introduced are not that critical for v0.74.0 being a stable experience. I am happy about feedback and improvements.

**Comment by itemforty** [comment]
This is SO amazing, sorry for taking so long to see this and close it out.
