### ISSUE TITLE
Feature Request: A setting to disable "drag to change initiative order"

### ISSUE THREAD

**Issue by itemforty** [Lurkars/gloomhavensecretariat#145]
Another low-priority thing, I would love to be able to disable the option to drag an enemy, player, or other figure around the initiative order. We've never had a good reason to use it, and as careful as I am, my other players always seem to accidentally drag pieces around when trying to scroll. If this is too difficult or not worth it feel free to close it out, but I figured I would request it anyway. Thanks!

**Comment by Lurkars** [comment]
Yeah this is easy. Will add.

**Comment by Lurkars** [comment]
New setting in [v0.47.7](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.47.7): `Disable drag'n'drop for figures`. Please verify if working as intended and close issue.

**Comment by itemforty** [comment]
Yep perfect!
