### ISSUE TITLE
Feature request; block modifications, well, disconnected from server

### ISSUE THREAD

**Issue by eborisch** [Lurkars/gloomhavensecretariat#148]
Thank you for all your work on this tool, it’s really going fantastic.

One thing that would make the user experience a little nicer, however, is to block interactions when you are known to be disconnected from a server. We played around the table with everyone having their own handheld device, and there were frequent occurrences of someone starting to enter changes only to realize they had dropped the connection.

**Comment by Lurkars** [comment]
Thanks, I will think about this. Maybe adding a confirmation dialog on first change or so that user is more aware about being disconnected!

**Comment by Lurkars** [comment]
![image](https://user-images.githubusercontent.com/2760570/222986182-341b6065-7241-4291-a194-1e4cd534e9d4.png)

Current state. Having something like this in mind?

**Comment by eborisch** [comment]
Yes, that would be perfect!

**Comment by Lurkars** [comment]
I also addressed an issue with re-connecting on focus. So hopefully this is solved. Anyway the dialog should now be live in [v0.49.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.49.0). Please verify and close issue if solved.

**Comment by eborisch** [comment]
Working great now, thanks for the quick update!
