### ISSUE TITLE
Crimson Scales Scenario 3

### ISSUE THREAD

**Issue by JP-Ellis** [Lurkars/gloomhavensecretariat#149]
We just finished the scenario, a few things to note:

- [ ] Missing 10 bonus XP at the end of the scenario
- [ ] Missing instructions to move water tiles at the end of each round.

**Comment by Lurkars** [comment]
Adding bonuses of scenarios is a functionality still missing. But I got several requests for this, so will prioritize this now.

I will try to recheck the CS data! Thanks.

**Comment by Lurkars** [comment]
Yeah, especially the CS data is lacking. I just inserted the room data from TTS mod and special rules from X-haven. So this is not validated with Scenario/Section book. Those are the points in priority order to be done, I think:
- [ ] section data to separate files (I will do this automatically [today?])
- [ ] set parent scenario for sections (I think, can also be automated by me [today?])
- [ ] move corresponding room data from scenario to section
- [ ] check room monster data for special monster and replace corresponding standees
- [ ] check/add/fix special rules for all scenarios/sections
