### ISSUE TITLE
In Jaws of the Lion first two scenarios should not award XP

### ISSUE THREAD

**Issue by JulienEllie** [Lurkars/gloomhavensecretariat#150]
There is an extra 12 XP (6+6) granted for completing scenarios 1 and 2 that should not be granted. Only scenario 3+ grant the 6 base XP (at level 1).

**Comment by JulienEllie** [comment]
Awesome. Thank you!

**Comment by Lurkars** [comment]
This should be fixed in [v0.49.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.49.0). Please verify and close issue if solved.

**Comment by JulienEllie** [comment]
Verified fixed.
