### ISSUE TITLE
Inccorect application label on Android

### ISSUE THREAD

**Issue by AcidWeb** [Lurkars/gloomhavensecretariat#152]
It is extremely minor cosmetic issue but on Android application installed by the page is called `ghs` instead full apllication name.

**Comment by AcidWeb** [comment]
It looks like if `short_name` is declared in `manifest.webmanifest` then Android launcher use it instead `name.

**Comment by Lurkars** [comment]
Mhm I see. What do you recommend as short name? "GH Secretariat"?

**Comment by AcidWeb** [comment]
That should fit.

**Comment by Lurkars** [comment]
This should be changed in [v0.49.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.49.0). Please verify and close issue if solved.

**Comment by AcidWeb** [comment]
It is.
