### ISSUE TITLE
Elements infused by clicking on monster ability cards doesn't wane at the end of the round

### ISSUE THREAD

**Issue by johan-ejstrud** [Lurkars/gloomhavensecretariat#157]
- **Version:** v0.49.8
- **Browser:** Edge (but also experienced on Windows)

### Steps to reproduce
1. 'Add monster' -> 'Chaos Demon' (from JOTL)
2. Add one monster standee.
3. Click 'Draw' -> 'Next Round' and repeat until a monster ability card with element infusion appears.
4. Click on the elements on the monster ability card to infuse them.
5. Click 'Next round'.

Bug: The elements are now 'Strong' (fully coloured), but should be 'Waning' (half coloured).

### Example
In this example, I infused air, ice, and wind by clicking on the monster ability card, and infused earth, light, and dark by clicking on the icons directly in the app bar.

![image](https://user-images.githubusercontent.com/11992346/224330831-5b972ba4-a7cc-4c0f-9d76-dd112aad99eb.png)

After clicking 'Next Round' air, ice and wind are 'Strong' (fully coloured), but earth, light, and dark are 'Waning' (half coloured).
![image](https://user-images.githubusercontent.com/11992346/224330990-d17cd3e5-2c70-4ec3-8a67-864e091d09a2.png)

**Comment by Lurkars** [comment]
Thanks,I will take a look.

**Comment by Bnibling** [comment]
Similarly, clicking on monster ability doesn't consume an element properly with Wild Icon.

Here, the Dark is strong and Sun Demon has a Wild to infuse Light:
<img width="1293" alt="image" src="https://user-images.githubusercontent.com/48171929/224358344-ae2ed66d-8b05-4676-bf12-50f52003e4d8.png">

Clicking the ability infuses Light, but Dark remains:
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/48171929/224358452-7f2bea54-8c96-40d7-976a-8039d49e7e13.png">

This should be players choice as well if multiple elements are active:
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/48171929/224358646-fd71add0-e319-45f0-862d-5aea07952a90.png">

That being said, the wild icon isn't an active button on the current version, so this might need to be a feature inclusion later on.

**Comment by Lurkars** [comment]
I addressed the initial issue in [v0.49.9](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.49.9), so please verify. I will keep this issue open then as improvement for the wild icon.

**Comment by johan-ejstrud** [comment]
> I addressed the initial issue in [v0.49.9](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.49.9), so please verify. I will keep this issue open then as improvement for the wild icon.

It works! Thanks a lot @Lurkars and thanks for a great tool. 👏

**Comment by Lurkars** [comment]
Close this prior to #160

**Comment by Lurkars** [comment]
![Screenshot from 2023-04-07 23-22-10](https://user-images.githubusercontent.com/2760570/230680590-7705b6f7-2d4b-41f6-8acd-564f9b4344eb.png)

Short update on the wild element consumption/creation: I added that select box (looking same for consume/create) to select item for effect. On Consume only strong/waning items are listed, on creation only not strong item are listed. Maybe play around with this. Version is [v0.57.7](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.57.7)
