### ISSUE TITLE
Dragging Monster Health - Minimum reduction is 2, not 1.

### ISSUE THREAD

**Issue by tylerseitz** [Lurkars/gloomhavensecretariat#158]
When click-dragging monster health, the smallest reduction possible is -2, I cannot get monsters to reduce by -1. To reduce a monster health by -1, I must first reduce it by -2, then increase it by +1. Player health seems to work just fine, -1 can be done without issue.
Increasing the monster health maximum to a large number doesn't fix the problem, implying that it is not a scaling/rounding error.

Same behavior for me across windows app, chrome internet app and running site directly in windows edge browser.

Is this expected behavior, if so is there a setting I can change to fix this?

**Comment by Lurkars** [comment]
Mhm I cannot reproduce myself, so can you provide some more details? I guess OS is Windows? What Desktop Resolution are you using? Did you try on different devices?

**Comment by tylerseitz** [comment]
**System configuration:**
OS: Windows 10 x64
Resolution: 3840 X 2160

**Steps to recreate:**
Select Frosthaven
Add blinkblade
Selt Scenario 1
Click and drag monster health to see issue of -2 minimum selection.

If I change the zoom setting to be much further zoomed in, then the dragging to -1 will work correctly. Conversely, if I zoom out very far the problem gets worse and the minimum health drag reduction is -3.

I tested it on a different windows 11 device, running the app through chrome. 1600 x 900 resolution. -1 dragging works until I zoom out to one click past when the heroes/monsters get split into 2 columns.

**Comment by Lurkars** [comment]
Thanks for the info. I think it's currently just pixel/resolution related, I will try to find a way to make it more relative, but problem is of course the bid difference between horizontal mobile screen (like 400px wide) and a bid screen like yours (3840px wide). So I will definitely work on this, but will take multiple iterations I think. Maybe I can try to work with acceleration factor too, the dragging slowly vs fast.

**Comment by Lurkars** [comment]
I tested this with simulating that big resolution and it's actually a rounding bug. I hopefully fixed that now in [v0.49.11](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.49.11). To smooth things out, I tried to added a cap of 1200px, so with wider screens, I try to "simulate" an actual width of 1200. So please verify if this is solved for you in that version and close this issue if so.

**Comment by tylerseitz** [comment]
I have tested at 4k resolutions with various zoom levels and I have not been able to reproduce this issue in the latest [v0.49.11](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.49.11)
