### ISSUE TITLE
Feature request: option to not ask for confirmation when going to next round and not all figures are done

### ISSUE THREAD

**Issue by CDietzel** [Lurkars/gloomhavensecretariat#159]
The way we use this app is purely as a way to manage monster attack cards and the loot deck. We don't use any of the features involving tracking player turns, monster turns or monster status effects. As a result, tracking which monster's turn it is is not helpful for us. 

However, the app requires that we click all the monsters one by one to end their turns, or else it shows a warning when you try to go to the next round: 

![image](https://user-images.githubusercontent.com/5873592/224508353-988b25fe-faa0-4d06-94f4-4fd0f2e0580f.png)

It would be nice if there were an option to make this warning not appear, so that we wouldn't have to click it at the end of every round.

**Comment by Lurkars** [comment]
Thanks. Good idea, I will add a setting for this and also check for other settings that disable any turn based effect (like expiring status effects) to also skip that reminder!

**Comment by Lurkars** [comment]
Added this in  [v0.49.10](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.49.10). Please verify and close issue if solved.

**Comment by CDietzel** [comment]
Yes, I tested this feature and it works. Thanks!

Closing the issue.
