### ISSUE TITLE
Missing Frosthaven Campaign Stickers

### ISSUE THREAD

**Issue by Gary-157** [Lurkars/gloomhavensecretariat#161]
Some campaign stickers are missing/require implementing for Frosthaven:
- Brummix tracks (x5, identical)
- Coral Crown (x6, individual, specific placement)

**Comment by Lurkars** [comment]
Will be fixed in next release (hopefully today)

**Comment by Lurkars** [comment]
This should be fixed in [v0.49.12](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.49.12) except for the specific placement. I don't think I will implement this. So please test general implementation and close issue if solved.

**Comment by Gary-157** [comment]
![image](https://user-images.githubusercontent.com/127674373/225114116-e3cf18e8-e6b6-47cd-8333-0e2b19d838f9.png)
I'm getting the attached when trying to view previously working campaign stickers, and mixed results trying to add new stickers

**Comment by Lurkars** [comment]
Okay, as always created new issues with this by having a bracket set wrong. Hopefully working now in  [v0.50.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.50.0)

**Comment by Gary-157** [comment]
Looks good, thanks!
