### ISSUE TITLE
Crimson Scale Scenario 4

### ISSUE THREAD

**Issue by JP-Ellis** [Lurkars/gloomhavensecretariat#162]
As usual, awesome work! We just played scenario 4 of The Crimson Scale and we are doing the following very minor issues:

- [x] Toxic imp has "Shield +X" action. Typically, this is calculated to be just "Shield X"?
- [x] Blood Ooze has an attack action which is "Range X" with a note that it has to be exactly range X. When there are both elite and regular oozes with different ranges, this, I think is incorrect.
- [x] The city guards and archers are special as they are allies to the player and have an adjusted max HP.

**Comment by Lurkars** [comment]
Thanks for the info, actually 1 and 2 are bugs that are not related to the scenario, but good to know. I hopefully fixed all that stuff in [v0.50.1](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.50.1). Also I added data for Scenario 4, if you already played it okay, but if you still find time to verify, I am happy. So please test all stuff in latest version and close issue if solved.

**Comment by JP-Ellis** [comment]
Thanks for the fixes!

After checking the Blood Ooze cards, yes I can confirm it is meant to be range 2 for both elite and normal.
