### ISSUE TITLE
Frosthaven scenario 34 spawns

### ISSUE THREAD

**Issue by dfannius** [Lurkars/gloomhavensecretariat#164]
Spoilers for Frosthaven scenario 34!

I know that not all scenarios are expected to have all their info yet, so apologies if I'm raising this issue too early.

In Frosthaven scenario 34, the Lord of Chaos spawns Chaos Sparks, which are physically represented just by number tokens and always perform the same action on initiative 90. It would be nice if there were a monster type for them that we could spawn so we could keep track of their hit points and conditions and remember when in the round they go. We were so used to Gloomhaven Secretariat doing everything for us that we almost forgot their turn a couple of times.

**Comment by Lurkars** [comment]
I read through it, I won't be able to represent the T parameter, so first need some setting to disable calculation, for certain values, but won't be a big problem. Artwork of the Chaos Sparks is more an issue for me 😅. So don't know how long it takes, but will definitely add a solution here.

**Comment by Lurkars** [comment]
Ha, already checking in a regex for valid calculation, so won't to any calculation with the T parameter. So this will be a quick fix! Will definitely come today!

**Comment by Lurkars** [comment]
So hopefully done everything right in [v0.50.3](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.50.3). Added awesome artwork from DALL·E 2 🙈. The Chaos Sparks are typed as boss, because I didn't want to add a fourth monster type. But I think it shouldn't be that important. Please verify and close issue if solved. Thanks.

**Comment by dfannius** [comment]
It's already useful, thanks! A few things:

- Technically the monster ID numbers should be able to go up to 12, not just 8 (even if only 2xC of them can be on the board at once).
- The a and b next to them isn't necessary (unless there's a reason I'm not thinking of); the players will put number tokens on the board so they will know which spark is where.
- Ideally the app would do the C part of the attack calculation while leaving the T part to the players. But I understand if it's a pain to do that.
- Their text should say "Cannot focus _on_ character summons."

**Comment by Lurkars** [comment]
>     * Technically the monster ID numbers should be able to go up to 12, not just 8 (even if only 2xC of them can be on the board at once).

Don't know if this is worth the effort. Just use token 1-8 then!?

>     * The a and b next to them isn't necessary (unless there's a reason I'm not thinking of); the players will put number tokens on the board so they will know which spark is where.

This is currently a feature, if it's in the text, it will be added to the monster too. This came form the special rules hints, where you may need to distinguish between a marker standee and a non marker standee (of the same type). Also don't think it's worth the effort to add extra to just show it in text but not on standee for this purpose.
 
>     * Ideally the app would do the C part of the attack calculation while leaving the T part to the players. But I understand if it's a pain to do that.

Thought already about this, and yes would be a pain and definitely won't do that now.

>     * Their text should say "Cannot focus _on_ character summons."

Will be fixed, thanks.

**Comment by dfannius** [comment]
> Don't know if this is worth the effort. Just use token 1-8 then!?

Yep, of course. The effect is very slightly different but it really does not matter.

I agree that all of the things you said are not worth the effort are not worth the effort :)

**Comment by dfannius** [comment]
Also, feel free to close this issue when the text is fixed.
