### ISSUE TITLE
Enhancement Request: Crossover Character Sheets/Perks

### ISSUE THREAD

**Issue by Richter54** [Lurkars/gloomhavensecretariat#167]
Hello!

I am wondering if it would be possible to add in support for the Crossover Character sheets with rebalanced perks that Cephalofair has provided at the following link:  https://drive.google.com/drive/folders/1t2VZUGusJWDXTNsq_LKv_zSaD9q3A3Bm?usp=sharing

This would ideally also contain support for the attack modifier decks with any updated perks.

Thank you! This app is great and has been really helpful for managing our campaign.

Jacob

**Comment by Lurkars** [comment]
You're welcome, this is already in progress, just not finished yet. See:
https://github.com/Lurkars/gloomhavensecretariat/tree/main/data/fh-crossover/character
