### ISSUE TITLE
How do we count with Traveling cloak +1 max HP?

### ISSUE THREAD

**Issue by jorge-graca-sky** [Lurkars/gloomhavensecretariat#174]
I feel like this is an issue that 300 people have had, I must be missing something for sure. But gods I cannot increase the max health of a character even with the Traveling Cloak equipped...

**Comment by Lurkars** [comment]
I haven't implement feature of the item yet, so you have do adjust max HP manually:

- in the character menu is a level icon, when you click on this you can increase max HP (this is feature from the old helper, so many people may know it)
- important: on leveling up, max HP will be reset to new level menu, so you have to redo the process on leveling up

As said, I will implement auto-apply for this, bit just haven't done yet!

![IMG_20230326_071116.jpg](https://user-images.githubusercontent.com/2760570/227756633-dbf38077-2051-49fd-8743-f45c5b5281f5.jpg)

![IMG_20230326_071141.jpg](https://user-images.githubusercontent.com/2760570/227756637-91192d15-205e-45c1-83d9-8ea8936c47f6.jpg)

**Comment by jorge-graca-sky** [comment]
uhmm ok that was not intuitive, I don't feel so dumb :P hehehe.

Thanks for the super quick reply, awesome work done here!

**Comment by Lurkars** [comment]
Thanks for quickly closing this. An update is on the way for automatically applying this effect! So then it's easier.

**Comment by Lurkars** [comment]
So small update here: in  [v0.53.4](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.53.4) the HP increase should be applied automatically on round start, when item is equipped. I also added a bunch of other item effects to apply.

**Comment by jorge-graca-sky** [comment]
Awesome thanks!
