### ISSUE TITLE
Monster round spawning rules

### ISSUE THREAD

**Issue by TheSquinter** [Lurkars/gloomhavensecretariat#181]
I'm noticing some inconsistencies with the spawn rules as I'm trying to review and update any missing for each scenario.

I could be doing something wrong, but using Scenario 8 as an example:
1. Set 3 characters and start Scenario 8
2. Draw opening round and go to next round
3. Draw for round 2 then open door (21.1)
4. It prompts to spawn 1 normal hound

Repeat steps
1. Restart Scenario 8
2. Move to round 3
3. Draw for round 3 then open 21.1
4. It prompts to spawn 1 elite hound

The issues:
1. The spawning should only occur at the start of the next round
2. The spawning should start with a normal, then elite every other round
3. (Unique to Scenario 8)  It has a custom note asking to spawn "1 hound for every empty starting hex", when it should just be one hound spawning in 'any' empty starting hex

I've tried playing around with every combination of `"resetRound": "hidden", R % 2 == 0", R % 2 == 1", "start": "true"` I can think of, but I might be missing something obvious.

**Comment by Lurkars** [comment]
Thanks, will be fixed. Cannot be solved now, because there is a bug in applying rules that I need to fix: when opening section, the rules get applied directly on opening, but only the `"always": true` rules should get checked. I will fix this and also fix scenario data, because `"resetRound": "hidden"` is also missing.

**Comment by Lurkars** [comment]
Please verify change in [v0.54.4](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.54.4). I hope this is working right now!

**Comment by TheSquinter** [comment]
It looks like the spawning rules work now! However when opening the section mid-round (like opening a door) it moves the round forward by one automatically.

**Comment by Lurkars** [comment]
I hope this is correctly fixed now in [v0.54.5](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.54.5)

**Comment by TheSquinter** [comment]
Nice work as always mate - all fixed.
