### ISSUE TITLE
FH: Bug on bane expiration 

### ISSUE THREAD

**Issue by Doctawin** [Lurkars/gloomhavensecretariat#185]
When gaining bane during a character's turn, the bane should trigger next turn; however, it triggers the same turn it was gained. 

Discussion here: https://boardgamegeek.com/thread/3058902/question-about-timing-bane

**Comment by Lurkars** [comment]
Okay, during testing I found a few issues with the condition stuff, so fix will take longer than expected, but I am working on this. Other issues
- on draw: conditions get applied and then reverted, this can lead to strange behavior in sorting when apply would kills figure
- undo/redo not working properly

**Comment by Lurkars** [comment]
Hopefully all fixed in [v0.57.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.57.0). Would be awesome if you can re-check this!

**Comment by Doctawin** [comment]
> Hopefully all fixed in [v0.57.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.57.0). Would be awesome if you can re-check this!

Ran a few tests with different conditions, reapplied it, removed it, increased/decreased health, and used undo/redo. Looks like everything is working except bane interacting with brittle. Based on brittle's wording, I think it should double bane's damage, but it's not triggering on bane.

**Comment by Lurkars** [comment]
Ah thanks, so much to consider. Will fix this too!

**Comment by Doctawin** [comment]
One more interaction: regenerate isn't removing bane and bane isn't removing regenerate.

**Comment by Lurkars** [comment]
Ough, thanks. All should be fixed in next release!

**Comment by Lurkars** [comment]
So now new issues addressed in  [v0.57.1](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.57.1). Please verify.

**Comment by Doctawin** [comment]
> So now new issues addressed in [v0.57.1](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.57.1). Please verify.

The following appear to now work correctly: 
- ward and bane interaction works
- brittle and bane interaction works
- regenerate is removed at the end of a turn when bane triggered 

The following isn't working correctly: 
- Regenerate heal at the beginning of a turn should remove bane, but currently, it's not doing so. Manually healing will remove bane though. 
- There's an odd behavior with clicking on a character's portrait to end the turn and then clicking on the portrait again to undo it. Here's the sequence: give a character bane, end their turn, click again to unend their turn, and then click to end their turn. This will trigger bane and not gray out the character portrait. 
- When I click to end a character's turn when they just have bane on them, the bane correctly triggers, but the character portrait doesn't turn gray. 
- Clicking on any status, clicking on it again to unselect it, and then closing the window will put the status on the character.

**Comment by Doctawin** [comment]
Here's another interaction I'm not exactly sure what's happening: A character suffers bane. Later, they get bane and regenerate. When regenerate triggers, it heals for 10, instead of 1.

**Comment by Lurkars** [comment]
> The following isn't working correctly: 
> - Regenerate heal at the beginning of a turn should remove bane, but currently, it's not doing so. Manually healing will remove bane though. 

This is working for me! I will take a deeper look at the other issues.

**Comment by Doctawin** [comment]
> > The following isn't working correctly:
> > 
> > * Regenerate heal at the beginning of a turn should remove bane, but currently, it's not doing so. Manually healing will remove bane though.
> 
> This is working for me! I will take a deeper look at the other issues.

Interesting. Maybe it's because I changed the max health of the character? When I added a different character, regenerate removed bane correctly. Maybe the above issues were because I changed the max health?

**Comment by Lurkars** [comment]
And another fixing round in  [v0.57.2](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.57.2). I really tried to address all issues, but always a bit afraid to create new once....

**Comment by Doctawin** [comment]
> And another fixing round in [v0.57.2](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.57.2). I really tried to address all issues, but always a bit afraid to create new once....

I did some brief testing, and I think all the interactions between the conditions are now working. One oddity that came up with this testing is if bane is on a character and another condition is added, then the bane gets removed.

**Comment by Lurkars** [comment]
> One oddity that came up with this testing is if bane is on a character and another condition is added, then the bane gets removed. 

Can you give more details? Cannot reproduce on a quick test.

**Comment by Lurkars** [comment]
And again, now in [v0.57.4](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.57.4). Hopefully we can close this one soon :sweat_smile:

**Comment by Doctawin** [comment]
> And again, now in [v0.57.4](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.57.4). Hopefully we can close this one soon 😅

I believe it's all working now, so I'll close this one :) . Awesome job!

**Comment by Lurkars** [comment]
I hope now that my new addition "permanent conditions" doesn't break anything here :sweat_smile:
