### ISSUE TITLE
Request: Shrink "Absent" players

### ISSUE THREAD

**Issue by itemforty** [Lurkars/gloomhavensecretariat#189]
The ability to mark players absent is really handy, especially for our group of 6 people, as we can put in our custom names, add items to the character sheets, keep their notes, etc. However, since we're only playing 4 at a time, the grayed-out characters take up a lot of room during card selection and the rounds, causing some crowding on the page.  If there was a way to shrink the absent players to 1/4th, and make sure they're always last on the page during all phases, it would be really helpful.

![image](https://user-images.githubusercontent.com/175024/229823723-484a7c26-4221-45ef-8ecd-b3d8c81a46f3.png)

![image](https://user-images.githubusercontent.com/175024/229825307-00090ff8-a38a-4242-b5d8-fab3d6cce58d.png)

Alternatively, a way to remove them from play, but keep their stats and custom names, etc, would be really awesome, but that seems like far more work so I figured I go small. Thanks for looking!

**Comment by Lurkars** [comment]
Hey, what do you think about the existing setting `Hide absent figures`? :sweat_smile:

**Comment by Lurkars** [comment]
So please re-open if you don't like the feature as it is, but for me this is already supported, so I will close issue.

**Comment by itemforty** [comment]
Oh! Hahah first time messing around with that option and forgot about that! Yep easy close. hahahah
