### ISSUE TITLE
Display issues on scenario summary

### ISSUE THREAD

**Issue by gkaragia** [Lurkars/gloomhavensecretariat#190]
There are some display issues when one or more characters are absent in scenario summary. In the example below, Blinkblade is absent.

![screenshot](https://user-images.githubusercontent.com/53191348/230148323-e88a5dfc-57a6-4b3c-80d1-a5cdf5e191ee.png)

**Comment by Lurkars** [comment]
Thanks, just published a release and now no time to fix this. So will come tomorrow I think.

**Comment by Lurkars** [comment]
Should be fixed in [v0.57.3](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.57.3)

**Comment by gkaragia** [comment]
It does! Thank you!

**Comment by gkaragia** [comment]
Reopening as it seems that this still happens.
