### ISSUE TITLE
Spawning rules if figure present

### ISSUE THREAD

**Issue by TheSquinter** [Lurkars/gloomhavensecretariat#200]
Thought I'd post here for tracking. Looks like a recent change (assuming around when Spawn Objectives was added) has broken the rules where `"type": "present"` is used as a condition. 

It only seems to work now when `"value": "1"` and `"tags"` on the objective/figure itself are also included, however many existing scenarios and rules across all editions do not have the value or tags set causing those rules to not be working anymore.

Some example FH scenarios include 21 (Section 51.1), 25 (Section 58.2)

**Comment by Lurkars** [comment]
Thanks will be fixed in a minute!

**Comment by Lurkars** [comment]
Should be fixed in [v0.58.1](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.58.1), please verify.

**Comment by TheSquinter** [comment]
All fixed, nice work.
