### ISSUE TITLE
Solo scenarios

### ISSUE THREAD

**Issue by z-m-k** [Lurkars/gloomhavensecretariat#206]
Is it possible to automatically add solo scenarios for classes in the party once they reach the minimum level? Otherwise, how do one actually add a solo scenario?

**Comment by z-m-k** [comment]
They are affect campaign play. They do not advance the campaign in the sense that ```These scenarios have no scenario numbers, locations, or stickers to go on the campaign map. You should not encounter a road event before playing them or perform an Outpost Phase after playing them.``` They do, however, affect the campaign as the character can still loot (the loot deck is 15 coin cards), gain experience, and the reward is either a custom item that synergies with the class or a one perk mark.

**Comment by Lurkars** [comment]
Okay, zunahm i dumm change that they are visible in campaign mode

**Comment by Lurkars** [comment]
Changed in [v0.59.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.59.0). So solo scenarios should now be visible in campaign mode. Please verify and close if solved.

**Comment by z-m-k** [comment]
These show up now. Now we need to add the missing solo scenarios, but that's for another issue.
