### ISSUE TITLE
Bug: wounded figures that are killed before their turn come back from the "dead"

### ISSUE THREAD

**Issue by itemforty** [Lurkars/gloomhavensecretariat#208]
Basically the title

1. On your turn, wound an enemy figure that's going later in initiative order

![image](https://user-images.githubusercontent.com/175024/230948971-802ab7c1-7b6e-4c61-bf9c-b903774fbe32.png)

2. "Kill" that same enemy using the skull icon

![image](https://user-images.githubusercontent.com/175024/230949133-f5421f15-db1e-4817-b7ad-259f238d029c.png)

3. Click either on your portrait to end your turn, or click on the enemy portrait to start theirs, enemy comes back:

![image](https://user-images.githubusercontent.com/175024/230949303-62c2d3c9-4f5e-47c8-a74d-bcf6145540d9.png)

This does NOT happen if you simply drop their HP down to zero. Thanks for looking!

**Comment by Lurkars** [comment]
Haha strange in multiple ways, just read email notification first and thought: damn I fixed this for HP, but didn't test dead. Then quick test working fine... Okay I should ask for current version. So yes should be fixed, but also in prev. version this should also happen by lowering hp to zero 😅
