### ISSUE TITLE
Bug? UX problem? Declining poison damage is hard to do on mobile

### ISSUE THREAD

**Issue by itemforty** [Lurkars/gloomhavensecretariat#209]
With a mouse it's really easy to hover over and click on the X to decline poison damage:

![image](https://user-images.githubusercontent.com/175024/230951021-4a94b976-aaa1-4a2f-b341-2d3656372acb.png)

However on mobile the, uh, hitbox? for lack of a better term seems to be very specific. Testing it on an Android phone, I have to make sure to click the upper left-most section of the X, or it applies either poison damage OR double. User experience from there is to try to heal the monster, which then asks to confirm if they healed their condition, or UNDO, which brings us back to the poison choice again.

 At this point we just disable that feature, but it'ss handy so we'd like to use it eventually. Thanks for looking!

**Comment by Lurkars** [comment]
Okay thanks, I will add more space between all buttons.

**Comment by Lurkars** [comment]
Added in [v0.59.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.59.0). Please test and close issue if solved.

**Comment by itemforty** [comment]
Yep, that seems to work much better. Thank you!
