### ISSUE TITLE
Feature Request: Additional "Name" field for Geminate, and a button to switch between them during play

### ISSUE THREAD

**Issue by itemforty** [Lurkars/gloomhavensecretariat#210]
The Geminate playstyle requires it to change forms, so Cephalofair decided to add a second name field in the physical copy of the game (which hasn't been uploaded so all online copies seem to only have one field there).

![image](https://user-images.githubusercontent.com/175024/230954270-28c3d057-aa3a-4924-8ed4-095c2260f38a.png)

The player running the Geminate in our campaign suggested having a button that could switch between those two names so we can keep track of his forms, and also because it would be adorable. I agree and thought I would ask. Thanks again!

**Comment by Lurkars** [comment]
Due to being lazy, I won't resize the field and just put the two name fields next to each each other, hope this will be okay.

**Comment by Lurkars** [comment]
Added in [v0.59.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.59.0). You toggle the figures state by clicking on the character icon next to the name! Hope this is touchy enough on mobile!
