### ISSUE TITLE
[Suggestions] Status effect description on tooltip

### ISSUE THREAD

**Issue by pakoito** [Lurkars/gloomhavensecretariat#211]
![2023-04-10 20_20_35-Gloomhaven Secretariat — Mozilla Firefox Private Browsing](https://user-images.githubusercontent.com/514871/230979779-5bd43984-355f-466a-9757-f2750882f63e.png)

As per title, at the moment the tooltips for status effects are just the names. Why not include the full description in the tooltip?

**Comment by Lurkars** [comment]
Good idea. Any resources for good description texts? The complete text from rule book seem's a bit long for some conditions.

**Comment by TheSquinter** [comment]
What about the player Reference cards?
![image](https://user-images.githubusercontent.com/124784924/231153805-ba1d7993-7d07-4e47-aeb0-ccf725e165e1.png)

![image](https://user-images.githubusercontent.com/124784924/231153824-796b9a02-d331-4edc-9802-ab20ea966a70.png)

**Comment by Lurkars** [comment]
New tooltips in [v0.59.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.59.0) with new setting to disable. Please close issue if solved.

**Comment by pakoito** [comment]
Exactly what I wanted. Thanks Lurkars!
