### ISSUE TITLE
[Bug] Bane interactions

### ISSUE THREAD

**Issue by pakoito** [Lurkars/gloomhavensecretariat#212]
Bane doesn't seem to trigger at the end of an enemy turn under certain circumstances, i.e. when the enemy is poisoned.

## Repro
Start a scenario
Give poison and bane to a character
Start the round
Move to character, see bane apply
Poison causes the enemy not to go away

![2023-04-10 20_25_00-Gloomhaven Secretariat — Mozilla Firefox Private Browsing](https://user-images.githubusercontent.com/514871/230980513-8f9b664c-3817-46a8-a187-eee7a45977b9.png)

I have found other cases where Bane wasn't applied when it should, but I cannot repro them convincingly. I remember Bane not applying to a stunned enemy at some point. This is more obvious if you go back and forth in the turn order, applying or unapplying the effects.

**Comment by Lurkars** [comment]
Should be fixed in [v0.59.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.59.0)

**Comment by TheSquinter** [comment]
Weird issue. Bane doesn't seem to be triggering when clicking through and marking a figures turn as finished. But if you just go straight to next round (and confirm not all figures done), it applies.

**Comment by Lurkars** [comment]
Damn those states. Can't reproduce in straight okay, but toggling active around, was able to reproduce. Have to investigate further again.

**Comment by pakoito** [comment]
Thank you as always Lurkars :D I took a break from FH and you've improved the app nicely in that time!

**Comment by Lurkars** [comment]
And we continue with testing in [v0.59.3](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.59.3)

As always changed much stuff in trying to fix all circumstances, in the end add new bugs I think, but I couldn't find them yet.

**Comment by pakoito** [comment]
Cheers! I won't be able to thoroughly test for a few days, this week is full of socials.

**Comment by TheSquinter** [comment]
Now when I apply Bane to a character, it doesn't trigger via active states or next round skipping.
It seems to be working fine for monsters though!

This sounds like a _bane_ for you 😆

**Comment by Lurkars** [comment]
Yes shouldn't touch this stuff late evening after work..  otherwise no other time. Will provide a fix soon!

**Comment by Lurkars** [comment]
Fixed in [v0.59.4](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.59.4)

[Wonderful typo](https://github.com/Lurkars/gloomhavensecretariat/commit/c185f24bfd68817075646ebcaeb3dda0af47e4e8#diff-d9d55e551d9cc48536f05d0689051b1e52f81232f4316c502f7a5903f23e2d33L35) (I am mostly wondering why this is valid code...)

**Comment by TheSquinter** [comment]
Yep looking good for me so far

**Comment by pakoito** [comment]
I have retired my kelp, and these problems have been better in the last 5 scenarios. I'll consider it done.
