### ISSUE TITLE
[Feature] +1 sticker on loot

### ISSUE THREAD

**Issue by pakoito** [Lurkars/gloomhavensecretariat#213]
There is an Event card in Frosthaven (WR-01 maybe?) that gives a +1 sticker to a loot card of your choice. It'd be good if it was implemented :D

**Comment by TheSquinter** [comment]
This is already implemented if you click on the Loot Deck to open it up and select +1 Enhancements :)

![image](https://user-images.githubusercontent.com/124784924/231022510-f7ee1ef4-7178-4e14-86cb-b1a680fa3871.png)

You can then scroll down to find lumber/metal/hide and pick one to add +1 to it. 

Unsure if you can enhance coins or herb cards yet, cause if not maybe those can be removed from the list to make it easier to navigate.

**Comment by Lurkars** [comment]
> Unsure if you can enhance coins or herb cards yet, cause if not maybe those can be removed from the list to make it easier to navigate.

Also not 100% sure, but first I only support resource enhancement and got told, that it's also possible to enhance coin cards. Cannot validate, but this is now on purpose, that you can enhance every card (except for random item and specials).

Please close issue if solved with the current enhancement options!

**Comment by pakoito** [comment]
Oooooh, you click on the _count_ and not on the expand.

**Comment by Lurkars** [comment]
After round, so before draw, just click on the cards! Otherwise number.
