### ISSUE TITLE
[Feature] Equipment with negative effects

### ISSUE THREAD

**Issue by pakoito** [Lurkars/gloomhavensecretariat#214]
I may have not done this correctly, but I haven't been able to make equipment that adds `-1` cards work out of the character sheet. Even when I try to edit the deck manually, it eventually reverts back as I tweak with other parts of the game.

**Comment by TheSquinter** [comment]
I'm finding the cards only get added once the round actually starts.
For example, if I add the Crude Chain Armor, 'equip' it by clicking on it, the AMD total doesn't change until round 1 starts.

Item added and equipped:
![image](https://user-images.githubusercontent.com/124784924/231024272-ceea4873-d00a-4c0e-934b-a201c24da51b.png)

New scenario chosen or scenario restarted, AMD shows 20:
![image](https://user-images.githubusercontent.com/124784924/231024358-8c34b1bc-e86e-4311-9f63-a3d7ea43c08b.png)

'Draw' to start round 1, AMD now shows 21:
![image](https://user-images.githubusercontent.com/124784924/231024398-af7a4644-47e3-42d2-8879-0b9478bc1aef.png)

**Comment by Lurkars** [comment]
Yes, but this is inconsistent to the other item effects, so I will change to apply directly on equipping!

**Comment by Lurkars** [comment]
Should be changed in [v0.59.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.59.0)

**Comment by TheSquinter** [comment]
This looks to be adding the cards in, but equipping seems harder or non-intuitive. On mobile you press and hold, on PC you now double click. Might be easier clicking a tick box or something to show it as equipped? Maybe expanding on the icons with a header? Just an idea:

![image](https://user-images.githubusercontent.com/124784924/231307819-95fe6708-c283-4672-b236-25a7eec99fde.png)

**Comment by Lurkars** [comment]
This is "works as designed" and hasn't change in recent version: like perks, you cannot equip items during scenario. If you still want, you need to double click.

I hope I didn't get the rules wrong here, but equip is meant to take the item into the scenario, not to actually play/trigger it. From my understanding, effects like adding -1 cards are applied when you take item with you, not when playing it.

**Comment by TheSquinter** [comment]
Hmm I'm not following. You can have a pool of items on you, such as 2 chest pieces. Normally choosing which to bring to scenario (or equip) won't matter for the app, unless these items add negative item effects. In that case, we'd want to add the negative effects for that equipped piece.

I just thought it wasn't quite clear that once you add the item, you also needed to 'equip' by double clicking the item name for the effect to take place.

And in FH, you can in theory loot an item during a scenario and equip it straight away, even if it puts you over your limit. You're technically meant to add any negative items effects when you do this too. Not sure if that rule is worth making any changes to the app for though.

From FAQ:
> **If a random item or chest reward item has -1's, would I have to add them for the rest of the scenario?** If you don't have a perk to ignore negative item effects, you can choose not to equip it. If you do equip it, you'll have to add the -1's._

**Comment by Lurkars** [comment]
In GHS: equip = bringing to scenario

That is respecting the rukes like only 1 armour can be brought to a scenario. There is no functionality to actually play an item. For the FH rules, that what double clicking is exactly for, to ignore the equip rules. Anyway item effects should apply when equipped.

**Comment by pakoito** [comment]
I'll need a few days to check, this week is full of socials.

**Comment by pakoito** [comment]
You have to click on it to equip it! Silly me, yeah it works now. Cheers!
