### ISSUE TITLE
Feature Request: Way for Blinkblade to Choose/Switch Fast/Slow During Card Selection

### ISSUE THREAD

**Issue by itemforty** [Lurkars/gloomhavensecretariat#218]
Similar to the Geminate feature you added, a way for the Blinkblade to set their speed during card selection. Maybe just a toggle between these two icons:

![image](https://user-images.githubusercontent.com/175024/231503341-71636a4a-fe32-40e4-a4ed-bc43cd7e337a.png) ![image](https://user-images.githubusercontent.com/175024/231503403-1a6352af-2602-4368-8441-fe675b88860b.png)

Helpful for all players to keep track when things get crazy. Just a thought! Thank you!

**Comment by Lurkars** [comment]
Yeah can simply add this. Maybe with option to turn off if irritating for someone.

**Comment by Lurkars** [comment]
Please test in [v0.59.3](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.59.3). Didn't add any settings, so now people need to get used to the new feature :D

**Comment by itemforty** [comment]
Looks really good! Looks like the "(Slow)" and "(Fast)" text only seem to display when the character name is not customized. 

Here's the default icon with a custom name:
![image](https://user-images.githubusercontent.com/175024/231564197-c8807417-43ce-438b-801b-211846002eeb.png)

But this character didn't have anything in the second name field:
![image](https://user-images.githubusercontent.com/175024/231564821-584a088b-e0ee-45ed-863e-6782e1a0d3c5.png)

So this is what it looks like when you toggle:
![image](https://user-images.githubusercontent.com/175024/231564226-34a7bd8e-f6c9-43d1-8c57-fef6b60f57fd.png)

**Comment by Lurkars** [comment]
This is on purpose, when no title set, the name is used with the version behind, if you set title, it's your choice. And you still want this, just set it to `Dr Marty Song (Fast)` and you're done. I will add two settings for this, one to disable this completely and one to disable showing the version name in brackets. Because currently it's not possible to just have "Blinkblade" there.

**Comment by itemforty** [comment]
Ok! Easy workaround, and the icon is more than enough. Thanks!
