### ISSUE TITLE
Adding/Improving Scenario Rules

### ISSUE THREAD

**Issue by Lurkars** [Lurkars/gloomhavensecretariat#219]
- [x] move `hp` to `setHp` [v0.59.3](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.59.3)
- [x] ~~add new `hp` as figure selector~~ add `healh` field to figure identifier [v0.59.3](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.59.3)
- [x] new `heal` figure action (differs from `setHp`) [v0.59.3](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.59.3)
- [x] `element` section marker?  [v0.59.12](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.59.12)
- [x] new `treasureLooted` trigger for rules with support for any treasure, explicit treasure and treasure count (like for Goal treasures) [v0.59.7](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.59.7)

_Source https://github.com/Lurkars/gloomhavensecretariat/discussions/183

**Comment by Lurkars** [comment]
@TheSquinter any suggestions on the hp filtering is a check for `current HP <= "value"` enough or do we need more complex rules?

**Comment by Lurkars** [comment]
okay, I think with "disablingRules" `<=` operator is enough, because you can always define a range by adding a disabling rule...

**Comment by TheSquinter** [comment]
> I am currently struggling more with something, where the matched figures also need to be applied... like "all monsters < HP/2 gain muddle" or so. Currently not possible.

I think that's ok, I don't recall anything needing to be applied based on current HP other than things like "when boss hits 50% HP, read this section and boss heals for X'.

**Comment by TheSquinter** [comment]
> move hp to setHp [v0.59.3](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.59.3)

This is working great

A few issues with `health` and `heal`:

1. `"health": "[H/2{$math.ceil}]"`

This doesn't appear to be working. Unless I'm doing it wrong.
If I hardcode like `"health": "10"`, it triggers, but not `1/2, H/2, HP/2, 50%` etc. 

2. It also isn't triggering **at** the `value`, but when their HP is less than the `value` (e.g. if monster has 20 max HP, `"health": "10"` doesn’t trigger when monster is at 10, but does when they have 9 HP)

3. `"type": "heal", "value": "[HP/2{$math.floor}]"`
This is not displaying calculated results, but I believe it does apply correctly. It works fine for other simple value calculations like `LxC` or `2`

![image](https://user-images.githubusercontent.com/124784924/231618915-742d0651-2981-49f7-9713-2deb2f9da9ea.png)

4. Minor: where is that heal icon from? Should it instead be the normal heal icon used in the book? 

Old vs new
![image](https://user-images.githubusercontent.com/124784924/231619549-338ebae7-297a-4d70-a454-88b3c0e02f40.png)

**Comment by Lurkars** [comment]
> A few issues with `health` and `heal`:
> 
> 1. `"health": "[H/2{$math.ceil}]"`
> 
> This doesn't appear to be working. Unless I'm doing it wrong.
> If I hardcode like `"health": "10"`, it triggers, but not `1/2, H/2, HP/2, 50%` etc. 

I will check

> 2. It also isn't triggering **at** the `value`, but when their HP is less than the `value` (e.g. if monster has 20 max HP, `"health": "10"` doesn’t trigger when monster is at 10, but does when they have 9 HP

Okay, maybe I implemented < HP not <= HP, will check and change

> 3. `"type": "heal", "value": "[HP/2{$math.floor}]"`
> This is not displaying calculated results, but I believe it does apply correctly. It works fine for other simple value calculations like `LxC` or `2`

This is indirectly WAD, showing calculated value is not possible, because value differs. But `"[HP/2{$math.floor}]"` should become `"HP/2 (rounded down)"`,, have to check too why this isn't happening

> 4. Minor: where is that heal icon from? Should it instead be the normal heal icon used in the book? 

This is my awesome self created heal condition icon for applying heal interaction when increasing HP, anyway you're right, I think this wasn't even on purpose, will change to the heal action icon.

**Comment by TheSquinter** [comment]
Thanks I'll give it a try again!

**Comment by TheSquinter** [comment]
Yep it was my bad - I needed to use `"type": "present"` together with `"health"` to do something like open a section when a boss hits `H/2`. It's also now working at <= now too!

**Comment by Lurkars** [comment]
Added treasures trigger in [v0.59.7](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.59.7), see [JOTL #18](https://github.com/Lurkars/gloomhavensecretariat/blob/main/data/jotl/scenarios/18.json) as example.

**Comment by Lurkars** [comment]
added element marker by using `"marker": "element:fire"` for example. Version not build yet, because need to test some other changes properly before release.

**Comment by TheSquinter** [comment]
Can we use `"marker": "element:fire"` for map sections too? There's only really one scenario that could use this though.

**Comment by Lurkars** [comment]
will take a look. Maybe difficult due to using placeholder...but I think this is currently also not working for monsters (didn't test, but I think adding marker `element:fire` to spawn rule etc will not work as expected, so need to adjust this anyways)

**Comment by Lurkars** [comment]
So element marker should also work for section markers now in [v0.60.3](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.60.3)

**Comment by TheSquinter** [comment]
I added the markers for Scenario 66

![image](https://user-images.githubusercontent.com/124784924/233226220-4af13f88-774d-4793-8e10-da286cf636da.png)

Not a big deal, but not sure if we want to update the sorting to use the section numbers in this case - looks like it's sorting alphabetically by Air > Dark > Earth, etc
