### ISSUE TITLE
Minor bugs

### ISSUE THREAD

**Issue by TheSquinter** [Lurkars/gloomhavensecretariat#222]
Just some minor bugs I've noticed:

- [x] Using `"resetRound": "hidden"` in two or more sections in the same scenario causes the round to advance by 2. 
For e.g. see FH Scenario 37 and open each of the sections. `resetRound` is used a lot here in these sections due the 'every second spawn' rule for 3 players - don't want an elite to be spawned first
- [x] `looseCondition` should be 'lose' :( sorry!. The code itself doesn't matter, but when triggered it displays on screen as "Loose x condition" [v0.59.6](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.59.6)
- [x] The 'hint' info for the Monsters option in settings just shows 'hint' [v0.59.6](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.59.6)

**Comment by Lurkars** [comment]
Okay the reset round will be tricky. I understand now, you like open #A in round 4, counter resets to 1, spawn rules say: "spawn in R % 2 = 0", round 2 spawns happen, open #B, counter resets to 1, round 2 spawn rule from #A triggers again, right, where you actually are in R = 3 of first reset. Currently no idea how to solves this.

**Comment by TheSquinter** [comment]
Actually I was referring more to the visual round tracker skipping 2 rounds. The spawn rules work as intended.

But using Sc 37 as the example, say I'm in Round 2 and open Section 70.1, Round stays as '2'.
If I then move to round 3 open Section 81.5, the round tracker moves to Round 5.
Opening 144.1 then moves the tracker to Round 7.

**Comment by Lurkars** [comment]
Okay I'll take a look again. Missunderstood that. Anyway I think the error I described can still happen then! When you have active rules depending on "even rounds" and section resets rooms to 1 (odd) on an even round, than that rules would have an offset. Note yes, this can be solved with a bunch of disabling rules but will of course increase complexity a lot.

**Comment by TheSquinter** [comment]
> The section counter jumping should be fixed in [v0.59.7](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.59.7)

Section counter is fixed!

Couple more to add:

1. Unsure if this one is intended. But if Auto Standees is **enabled**, any scenarios or sections which are missing the spawning rules (such as FH 54) do not show the monsters in the list meaning players need to use Add Monster to at least manually spawn them themselves. If Auto Standees is **off**, then the monsters decks show.

2. Abael Herder has ability 'Heed the Pigs'. With calculated stats on, it's safe to assume the '0' should be X, but range should be X+1, which is not shown. Was unsure how to fix this without using custom text for the attack and range, but then you don't get the elite's added muddle effect.

![image](https://user-images.githubusercontent.com/124784924/232181434-0c2a5d24-8817-426b-8ad4-9a69f888bce6.png)

Original card:

![image](https://user-images.githubusercontent.com/124784924/232181441-a7cd7133-3fd1-4d23-8ae3-d5411825586b.png)

Similar with the Piranha Pig's Feast not showing the X.

![image](https://user-images.githubusercontent.com/124784924/232181641-c22d3d9a-8f3b-451d-8a74-dc0cada93b31.png)

**Comment by Lurkars** [comment]
I changed something to fix an ability cards but, that causes now more issues. Easy revert, but I can't find the bug causing the change anymore for trying to provide a different fix. Damn.

**Comment by Lurkars** [comment]
Cards should be fixed in [v0.59.9](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.59.9). For the monster adding, I don't want to touch this in a quick shot and break things. First of all, why aren't there any spawns? So is his just missing spawn rules? So it's more to provide a better workaround for missing data? Because if so, that's what I need to check then, are there monsters listed for the scenario that won't come up in any room or rule and THEN add it.

**Comment by TheSquinter** [comment]
This is fixed. I'll create a new issue for the standees
