### ISSUE TITLE
Small Typo Collection Thread

### ISSUE THREAD

**Issue by itemforty** [Lurkars/gloomhavensecretariat#223]
Boneshaper Character Sheet:
- [x] "Immediatley" should be "Immediately" [v0.59.6](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.59.6)
- [x] "exhauseted" should be "exhausted" [v0.59.6](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.59.6)
- [x] "enenmies" should be "enemies" [v0.59.6](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.59.6)

Settings, "Show Hints" tool tip: 
- [x] "shortscuts" should be "shortcuts" [v0.59.6](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.59.6)

**Comment by Lurkars** [comment]
Closed for #242
