### ISSUE TITLE
"Show full ability cards" issue

### ISSUE THREAD

**Issue by Escher0** [Lurkars/gloomhavensecretariat#225]
When using the "Show full ability cards" setting, one or both of two issues will always eventually happen, usually within 1 or 2 rounds. One is the title disappearing, and the other is the title being wrong, as in showing the title of a different ability card.

**Comment by Lurkars** [comment]
Thanks for the report and surprised no one noticed before...Should be fixed in [v0.59.6](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.59.6), please verify and close issue if solved.

**Comment by Escher0** [comment]
I was surprised as well; I'm guessing not many people turn that option on. Thanks for the quick fix, I will check it out when we play on Monday.

**Comment by orphu** [comment]
Our group encountered this in our last session. I came to report it, and see that it's already fixed! Thanks!

**Comment by Escher0** [comment]
Forgot to come back and report that we had no issues in our last session. Thanks again for the quick fix.

**Comment by Escher0** [comment]
Closed
