### ISSUE TITLE
Solo scenarios are shown blocked if their index matches a blocked campaign scenario

### ISSUE THREAD

**Issue by bluefish2020** [Lurkars/gloomhavensecretariat#227]
Hello, in this campaign scenarios 3 and 9 are blocked.
The third and ninth solo scenarios are incorrectly shown with the blocked icon.

![solo_senario_blocked](https://user-images.githubusercontent.com/115673318/232174286-c4f9ce8e-1229-4177-a702-9b7e6b243ec6.png)

ScenarioManager.isBlocked should be returning false for all of the solos.

This may be related to https://github.com/Lurkars/gloomhavensecretariat/issues/206 if solo scenarios were not shown in campaign mode before?

**Comment by Lurkars** [comment]
Thanks. Will fix this.

**Comment by Lurkars** [comment]
Thanks. Will fix this.

**Comment by Lurkars** [comment]
Should be fixed in [v0.59.9](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.59.9). Please verify and close issue if solved. Thanks,

**Comment by bluefish2020** [comment]
Looks good now. Thanks!
