### ISSUE TITLE
"Character Forms" and "Form Hint" aren't persistent after a reload

### ISSUE THREAD

**Issue by itemforty** [Lurkars/gloomhavensecretariat#230]
GHS doesn't seem to remember "Character Forms" or "Form Hint" after a reload on desktop or on mobile. Once either refreshes the server connection, page, or app (Android), those options are disabled. Not a big deal, but probably not intended. Thanks for looking!

**Comment by Lurkars** [comment]
Ah yes, wanted to keep this setting local, but forgot exception, so written server settings sync it gets overwritten with default everyone. Will be fixed. Does it make more sense to you to sync this setting too?

**Comment by Lurkars** [comment]
Added this in [server v0.59.9](https://github.com/Lurkars/ghs-server/releases/tag/v0.59.9). So should just sync now.

**Comment by itemforty** [comment]
Perfect! Thank you so much!
