### ISSUE TITLE
Monsters not listed if spawn rules missing

### ISSUE THREAD

**Issue by TheSquinter** [Lurkars/gloomhavensecretariat#231]
With Auto Standees enabled, any scenarios or sections which are missing the spawning rules do not show the monsters in the list meaning players need to use Add Monster to at least manually spawn them themselves. 

If Auto Standees is off, then the monsters cards show.

This is intended more as a workaround for complex spawn rules that haven't been implemented yet (like FH Scenario 54).

**Comment by Lurkars** [comment]
Small addition: when scenario rules and/or interactive abilities are disabled, the corresponding monsters should also be added. So this is not just a workaround for missing data!

**Comment by Lurkars** [comment]
I hope this is fixed in [v0.62.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.62.0) without breaking any existing stuff. Please verify.

**Comment by TheSquinter** [comment]
This looks to be working as intended.
