### ISSUE TITLE
Interactive summon abilities and wildcard elements (Scenario 60 spoilers)

### ISSUE THREAD

**Issue by TheSquinter** [Lurkars/gloomhavensecretariat#232]
- [x] When there are multiple monsters sharing the same deck in the scenario, if one monster is summoned by the boss using the interactive special ability it will get a different ability card drawn than if it were manually added via standee.

This is with drawExtra not set.

- [ ] Also discovered, with a boss special ability which consumes multiple wildcards to summon, for e.g.:
```
          "type": "element",
          "value": "ice:wild:wild",
```
If you consume the ice and the first wild, it doesn't let you choose to consume the second. But you're still able to interact and use the summon ability anyway

**Comment by Lurkars** [comment]
First issue should be solved in [v0.59.10](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.59.10). The second one is a bit more difficult, have to change a bit how it's stored that summon ability was triggered etc. This will take a while.

**Comment by TheSquinter** [comment]
It looks as though you've fixed #2 as well. Seems to be working now!

**Comment by TheSquinter** [comment]
I don't think the "confederated" label is really needed? Monsters are either allies to you, or allies with themselves against other monsters. In both cases, they'd use the ally deck and seeing the 'Ally' label is enough for players to know. Unless you want to use 'Allied' label instead?

**Comment by Lurkars** [comment]
> It looks as though you've fixed 2 as well. Seems to be working now!

This is not complete yet, as I would understand, you would get for example multiple summons for every consumed element. By now you still can only summon once!

**Comment by Lurkars** [comment]
> I don't think the "confederated" label is really needed? It's not a very commonly used word. Monsters are either allies to you, or allies with themselves against other monsters. In both cases, they'd use the ally deck and seeing the 'Ally' label is enough for players to know. Unless you want to use 'Allied' label instead?

Good idea with "allied", I want to make a difference, because one may be confused reading "ally" when it's still an enemy to you. Otherwise people have to remember text from the scenario rules that it's still enemies. But allied would be enough for me, I still would like to mark something worth a different color or so to make this clear.

**Comment by TheSquinter** [comment]
> This is not complete yet, as I would understand, you would get for example multiple summons for every consumed element. By now you still can only summon once!

I think this is working as intended. At least, it is for this particular boss. It consumes Ice:Wild:Wild to summon a monster. It should only do this once as you can only consume the Ice once.

I'm only noticing `"type": "sufferDamage"` can be triggered multiple times via interactive ability (but that's maybe a separate issue...)

**Comment by Lurkars** [comment]
> > This is not complete yet, as I would understand, you would get for example multiple summons for every consumed element. By now you still can only summon once!
>
> I think this is working as intended. At least, it is for this particular boss. It consumes Ice:Wild:Wild to summon a monster. It should only do this once as you can only consume the Ice once.

You're sure on this? Haven't played, I interpreted the card, that 6 available elements works would result in 6 summons... Otherwise it would a bit weak?! Like require 3 elements for 1 summon.


> I'm only noticing `"type": "sufferDamage"` can be triggered multiple times via interactive ability (but that's maybe a separate issue...)

Will be fixed soon. With the conditions fixed, I also produced new bugs with active states, so refactor the whole process. And then there's #235 😓

**Comment by TheSquinter** [comment]
> Edit: ah okay, I read through it, seems that most of the time all 6 elements are strong. (When coming to that boss). But if so, current state is also wrong, because you just need to consume one element for the summon to be activated. So please give again feedback on that one, what you think it should really work.

Yeah you're right that all 6 elements would be strong (and I see you've assigned the element marker to the 'lieutenants' and added the rules - nice!).

I still think that's intended. He still needs to consume 3 elements for one summon. On his turn his special 1 can consume all 6 elements to summon 1 Clawcrusher and 1 Mindsnipper. Special 2 can summon 1 Wavethrower but also do a big attack. Also note section 115.4 that only 1 character can damage the boss, so seems to be balanced (but I also haven't actually played it).

On the app, it looks like the interactive summon action is currently allowed even without consuming the 3 elements. But if you click it, it doesn't let you do it again like you can with `sufferDamage` (which is good).

**Comment by TheSquinter** [comment]
This all looks to be working nicely!
