### ISSUE TITLE
Improve / Fix scenario unlocking for FH

### ISSUE THREAD

**Issue by datenshi888** [Lurkars/gloomhavensecretariat#237]
After successfully finishing scenario 114, the app unlocks scenario 115 instead of adding section 86.1 to calendar in 4 weeks. (the section presumably unlocks that scenario, haven't confirmed as we're trying to avoid spoilers). The flow chart does show that scenario 114 leads to 115 but finishing the scenario should not unlock 115 directly as per scenario/section books.

**Comment by Lurkars** [comment]
Thanks, I just used the flowchart for the data, but need to update the data.

**Comment by TheSquinter** [comment]
Not sure how this would get handled as not everyone would be using the campaign sheet calendar and section notes to trigger "4 weeks have passed, now unlock scenario". I think unlocked scenario is ok if it's in the flowchart. 

Unless it just doesn't get unlocked in the app at all and players have to manually add the unlocked scenario once section note is read in their calendar, like you might for side scenarios.

**Comment by datenshi888** [comment]
@TheSquinter If I'm not mistaken I've come across a similar situation in a different quest and the app already has a way of handling it. It tells you to add the section to your campaign sheet calendar in X weeks after you mark the quest as complete and also adds it to the in app campaign sheet calendar automatically at the time. This quest just had the reward set mistakingly as "unlock scenario".

**Comment by TheSquinter** [comment]
Oh that’s good to know thanks for the heads up.

**Comment by Lurkars** [comment]
Sorry that in was busy with #235. Will fix this soon!

**Comment by Lurkars** [comment]
So in [v0.60.1](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.60.1) I now fixed the wrong unlock and started adding corresponding section to calendar as scenario reward, anyway, this results in a few Todos:
- [ ] general scenario reward data is missing for most FH scenarios
- [ ] possibility to open(and automatically apply) calendar sections to gain the rewards there (in this example, unlock 115 after reaching the corresponding weak!) This is luckily not so difficult, because I already have those "conclusion" sections, so just need to add the UX for this

**Comment by night5hade** [comment]
Here are a couple of other instances in which succeeding the scenario adds a section to the calendar as oppose to unlocking another scenario directly:

- Scenario 69 Ends with adding 15.4 to the calendar in 3 weeks, this unlocks Scenario 70 
- Scenario 11 ends with adding 54.3 to the calendar in 4 weeks, this unlocks scenarios 28 and 30

**Comment by TheSquinter** [comment]
All the scenario unlocks and section rewards should be added or fixed as of [v0.61.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.61.0)!

**Comment by Lurkars** [comment]
Yes, I leave this open for fulfilling

> - [ ] possibility to open(and automatically apply) calendar sections to gain the rewards...

**Comment by datenshi888** [comment]
Not sure if I should open a new thread for a similar issue or just aggregate them over here?

Scenario 9 completion should not reward a new location. It only awards 2 Corpsecap.
It's part (start?) of a puzzle questline, from what I can gather.

**Comment by Lurkars** [comment]
I have currently no access and therefore no clue of the puzzle book. So you also unlock scenarios in there? If so, I have to think about is I want to support that. Otherwise there's always opportunity to unlock scenarios manually for that use case. Regarding scenario 9 I will take a look thanks.

**Comment by Lurkars** [comment]
Okay easy to see, some scenarios are unlock by puzzle. So need to find a way to add this too. By now I would reference to manually unlock those scenarios! For scenario 9 I will remove the direct unlock.

**Comment by Lurkars** [comment]
Calendar Sections are now automatically rewarded in [v0.62.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.62.0). Reworked a bit the calendar. Still open to list the rewards!

**Comment by Lurkars** [comment]
Updated TODOs:

- [ ] list applied rewards in week section view
- [ ] possibility to add puzzle solutions to unlock scenarios

**Comment by datenshi888** [comment]
Scenario 115 (follow up to 114) adds a section to the calendar in a bit of a new way, based on how many objectives were destroyed.

For that particular scenario it's in X+1 weeks, where X is the number of objectives destroyed.

The issue is referenced in #272 as well.

**Comment by TheSquinter** [comment]
There seems to be a bug with `calenderSection` rewards applying 1 week early.

For e.g. 95.4 should unlock Scenario 66, but it changes icon and unlocks 1 step before.
![image](https://user-images.githubusercontent.com/124784924/235850199-b6dff04e-cda0-46bb-b826-ad49f1bf33f3.png)
![image](https://user-images.githubusercontent.com/124784924/235850318-5fbbfe82-c59e-4a02-b0d0-c23779947ae3.png)

**Comment by Lurkars** [comment]
> Updated TODOs:
> 
>     * [x]  list applied rewards in week section view
> 
>     * [x]  possibility to add puzzle solutions to unlock scenarios

Added in [v0.64.1](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.64.1)
