### ISSUE TITLE
Feature Request: Show all connected Clients the Scenario Summary 

### ISSUE THREAD

**Issue by itemforty** [Lurkars/gloomhavensecretariat#243]
Love the Scenario Summary, but when playing a game with a group of players who all have their own devices it would be really nice to have the Summary appear on everybody's phone, not just the person who triggered it. 

I don't know how hard that is or if that's worth it for other players, but would definitely be helpful for us, or players who play remotely. 

Thanks!

**Comment by Lurkars** [comment]
I will think about this.

**Comment by itemforty** [comment]
That looks really good and works as intended when connected to the public server! Hilariously it's *not* working when connected to my VPS or my state-side hosted client. How can I check the server version number?

**Comment by Lurkars** [comment]
Yeah you need latest server version for it. Server version is just in the server logs printed at startup.

**Comment by itemforty** [comment]
Yep that's on me; I wasn't getting the latest version of gh-server. Works really great, thanks again!
