### ISSUE TITLE
Monster ability cards with +0 attacks or moves are showing as 0 when "Show calculated stats" is checked

### ISSUE THREAD

**Issue by mikecmeli** [Lurkars/gloomhavensecretariat#245]
"Show calculated stats" off
![image](https://user-images.githubusercontent.com/12204301/232961016-2a39a200-7be2-4cd5-b7ed-3684f716116d.png)

"Show calculated stats" on
![image](https://user-images.githubusercontent.com/12204301/232961060-1c37d8b0-3d9a-44eb-a917-6524a6998380.png)

You can see that the actions are being set to 0, rather than zero being added to the base stats. This does not happen with any other values as far as I can tell.

**Comment by Lurkars** [comment]
Should be fixed in [v0.60.2](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.60.2)! Please verify and close issue if solved. Thank you!

**Comment by mikecmeli** [comment]
Fix verified! Thanks!
![image](https://user-images.githubusercontent.com/12204301/233239922-bbaa7e1a-09f8-4aaa-b8bd-ac9f33a6e756.png)
