### ISSUE TITLE
Feature Request: Renaming Summons?

### ISSUE THREAD

**Issue by itemforty** [Lurkars/gloomhavensecretariat#253]
It would be awesome to customize summons' names. Adds immersion and some consistent story telling elements to the game. Not sure how hard it would be to do, but just figured no harm in asking!

Thanks!

**Comment by Lurkars** [comment]
Shouldn't be much work to add a "title" field like on character. Just busy currently with #163 , so but to backlog.

**Comment by Lurkars** [comment]
Please verify in [0.62.4](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.62.4). The summon title can be change in the level menu of the summon. If this is working as intended, please close issue, thanks.

**Comment by itemforty** [comment]
Very cool, works exactly like expected. Only other QoL improvement would be to make the custom names persistent instead of reverting back to default, but I'm not going to complain about something that's already really neat. Thank you!

**Comment by Lurkars** [comment]
What do you mean persistent? Maybe using your (not updated) server?

**Comment by itemforty** [comment]
Yeah sorry should've clarified: after changing the summon's name it appears as expected. Totally workable, great feature. I meant that once the summon dies it reverts back to the default name when summoning them again e.g. "Shambling Skeleton."
