### ISSUE TITLE
Bug: Incorrect Health Value Displayed After Changing Scenario Level

### ISSUE THREAD

**Issue by OZ10** [Lurkars/gloomhavensecretariat#254]
Assume this happens on any scenario with objectives but I'll use my current scenario (10) as an example.

I started the scenario at level 1 (default) and then manually adjusted the level by changing the Scenario Level Adjustment = -1. The objectives max health changed but their current health stayed the same:

![original_194e99f4-aff4-4cae-9772-41cb486b8834_Screenshot_20230421-081852_Chrome](https://user-images.githubusercontent.com/3818583/233627300-f495244e-b114-4577-9a2c-023f98ec8bf2.jpg)

**Comment by Lurkars** [comment]
Thanks, will take look.

**Comment by Lurkars** [comment]
Should be fixed in  [v0.61.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.61.0), please verify and close issue if solved.

**Comment by OZ10** [comment]
Fixed
