### ISSUE TITLE
Bug? Only the first summon in the group expands for quick reference

### ISSUE THREAD

**Issue by itemforty** [Lurkars/gloomhavensecretariat#255]
When you have multiple summons, only the first one will expand when the turn comes: 
![image](https://user-images.githubusercontent.com/175024/233627622-33892323-3a2b-4f55-8474-77acce8ddff5.png)

Clicking on my character's face will collapse this first summon, but not expand the second. Since there's a setting for "Combine Summon Action," it seems like maybe this isn't the expected behavior? Otherwise I don't know what "Combine Summon Action" is supposed to do, since toggling it on and off doesn't seem to matter.

If it's not the original intention, then the feature request would be to cycle through each summon in order per face click, if feasible or worth the time. Thanks for looking!

**Comment by Lurkars** [comment]
Haha, okay. Need more explanation:
- Summon is active, it's in order of summons, so first first, etc.
- (currently) toggle active state of summon by double click (long press mobile, as for monster standees too)
- this behaviour is also triggered when using "tab" short key for toggling figures
- maybe makes more sense to still toggle through summons when clicking on character and add there a doubeclick event to end all summons turns...
- "combine summon action" is bound to "interactive abilities" and is meant for a summon action on a monster ability card, when it says "Summon 1 normal Ooze", every standee will do this. With "combine summon action" all summons are added at once, when disabled you would just create 1 summon per click and have to click *number of standees*-times to add all summons.

**Comment by itemforty** [comment]
Ah gotcha, thanks for clarifying! 

> maybe makes more sense to still toggle through summons when clicking on character and add there a doubeclick event to end all summons turns...

My instinct was to just tap through, since tapping once starts the first summon in the group, so that might make more sense for others? Definitely would be an easier turn flow than tapping character, long press on each summon, and then tapping character when done IMO. 

Technically my issue is handled here, but do you want to explore that change and use this for reference?

**Comment by Lurkars** [comment]
Yes, already improved the behaviour locally, will give you issue back for testing on new release 👍

**Comment by Lurkars** [comment]
Addressed in [v0.61.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.61.0), please verify and close if solved!

**Comment by itemforty** [comment]
That's great! Thank you so much!
