### ISSUE TITLE
Touch scrolling on active or inactive monster ability cards broken - 0.61.1

### ISSUE THREAD

**Issue by mbpen** [Lurkars/gloomhavensecretariat#257]
Similar to https://github.com/Lurkars/gloomhavensecretariat/issues/93 but now it is occurring for both active and inactive monsters. Issue from iPad using Safari on 0.61.1, have not tested on my usual touchscreen laptop yet.

**Comment by Lurkars** [comment]
Will check!

**Comment by Lurkars** [comment]
I wasn't able to reproduce on Android touch screen. Will try to fetch up an iPad of a friend to do some more testing.

**Comment by Lurkars** [comment]
I tried to improve by changing the touch stuff, so hopefully fixed in [v0.65.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.65.0)
