### ISSUE TITLE
Can`t assign more curse cards to characters

### ISSUE THREAD

**Issue by kbl42** [Lurkars/gloomhavensecretariat#262]
I am playing scenario 120 in the last room (157.1) with 2 characters and 1 absent. My characters both have 4 curses, and i can`t give them anymore. A red triangle are shown next to curses. If I remove one curse the triangle dissappears, but only if i remove one more, i can add 1 to a total of 3 for that character.
I have a suspicion that the absent character have been getting curses, when doors are opened.

i am on ipad ios, secretariat v 0.61.1

**Comment by Lurkars** [comment]
Thanks, I will take a look.

**Comment by Lurkars** [comment]
Yes definitively related to absent figures being still cursed. Will be fixed

**Comment by Lurkars** [comment]
Should be fixed in [v0.62.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.62.0). Please verify and close issue if solved.

**Comment by kbl42** [comment]
Yes, it seems to have fixed it 👍 

but i noticed that when opening a door, it will add curses to all actIve characters, even if it will exceed 10 curses total. It will show a red triangle, but still add them.

**Comment by Lurkars** [comment]
Damn, okay need to fix that too!

**Comment by Lurkars** [comment]
And again, should be fixed in [v0.62.1](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.62.1) now. Please verify and close issue if solved.

**Comment by kbl42** [comment]
Thank you, it works !
Awesome job with this site!
