### ISSUE TITLE
Feature request (Frosthaven): Ice Wraith "Shift Form"

### ISSUE THREAD

**Issue by dfannius** [Lurkars/gloomhavensecretariat#263]
Ice Wraiths have an ability card "Shift Form" which begins with "All elite Ice Wraiths become normal, and all normal Ice Wraiths become elite." It would be nice to automate this. (Currently, switching between normal and elite is awkward enough to do by hand in the app that we just don't bother and keep track of it by hand.)

**Comment by Lurkars** [comment]
Hey, you see that gray arrow next to the standees? That opens menu for applying certain actions to all standees... Take a look at action at bottom 😉

![IMG_20230423_163535.jpg](https://user-images.githubusercontent.com/2760570/233846113-85a666c8-d94f-419b-b9d7-be691ad12c17.jpg)

**Comment by dfannius** [comment]
Amazing! I had clicked on this arrow in the past but didn't understand what it was for.
