### ISSUE TITLE
Feature Request: Add Inspiration to post-scenario rewards table

### ISSUE THREAD

**Issue by mqstout** [Lurkars/gloomhavensecretariat#268]
It's super easy to forget to add inspiration. The rewards table GHS has after a scenario is great. Could you add inspiration to the XP/loot/etc chart? It's just 4-C.

**Comment by Lurkars** [comment]
Should be added in [v0.62.5](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.62.5) under new Bonus field. Please verify and close issue if solved.

**Comment by mqstout** [comment]
Tested a few random scenario wins with 2, 3, 4 characters and the inspiration displayed on the exit screen with the expected value.
