### ISSUE TITLE
Monsters can heal over the max health

### ISSUE THREAD

**Issue by N1k145** [Lurkars/gloomhavensecretariat#270]
I noticed that when I click on a heal action of a monster card, the monster can heal more than its max health.
In this specific case, I had two wind daemons, one at full health and a second one missing health. I clicked on a "Heal 1 Self" action of a monster card, and both monsters healed 1 point.

**Comment by Lurkars** [comment]
Thanks, will check and fix!

**Comment by Lurkars** [comment]
Should be fixed in [v0.62.6](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.62.6), please verify and close issue if solved.

**Comment by N1k145** [comment]
@Lurkars I did just test it, it works fine now. But the animation still happens for both monsters. I don't know if you would like to fix this one too?

The healing works fine now.

**Comment by Lurkars** [comment]
Thanks, I will fix this too

**Comment by Lurkars** [comment]
Animation should now only trigger on real heal in [v0.62.7](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.62.7). Please close issue if solved.

**Comment by N1k145** [comment]
@Lurkars Just tested it, looks great now 👍🏼
