### ISSUE TITLE
Wrong or missing scenario rewards

### ISSUE THREAD

**Issue by datenshi888** [Lurkars/gloomhavensecretariat#272]
As issue #237 has pivoted a bit, I thought I'd make a new thread with scenarios that have wrong or missing rewards on completion.

- [x]  Scenario 32 - missing reward:  item blueprint 069 (Feathered Cloak)
- [x]  Scenario 115 - instead of unlocking next scenario directly, should add section 66.2 to calendar in X+1 weeks (where X is the number of objectives destroyed) (incidentally the objectives are marked as escorts which seem wrong as they're enemies to your party)

**Comment by TheSquinter** [comment]
- Scenario 32 rewards are there, just needs the `itemBlueprints` label added so it displays!
- Scenario 115 reward is a good call out - there's a few others like that where the reward is based on objectives destroyed, crates looted etc. We can probably add this reward as free text for now like the others until there's a solution but I'll let Lurkars decide.
- Good point for the objectives - think it was more to identify that they're enemies to both you and monsters, and summons don't focus on them

**Comment by Lurkars** [comment]
Will be fixed today and also will add "manualCalenderSection" where you select number of weeks on summary page. I don't thinks it's worth the effort to fully automate this with all the X values...

**Comment by Lurkars** [comment]
Should be fixed in [v0.62.6](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.62.6)
