### ISSUE TITLE
Checking perks on mobile

### ISSUE THREAD

**Issue by mika1111** [Lurkars/gloomhavensecretariat#273]
It seems that there is some problem with checking perks on mobile devices (chrome). 
Info I gather so far:
* checking on the desktop seems to work fine 
* it occurs only for perks (battle goals and levels seem to be ok)
* if you check on the desktop you are able to uncheck on mobile

Great app. We love it :)

**Comment by Lurkars** [comment]
I will take a look how to improve this.

**Comment by Lurkars** [comment]
I tried to improve a bit and makes the boxes bigger in [v0.62.7](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.62.7). Please verify and report. If it's working well enough, please close issue.

**Comment by OZ10** [comment]
This is working much better now

**Comment by mika1111** [comment]
Yes it is working great that you :)

**Comment by AcidWeb** [comment]
@Lurkars I would like to re-open this ticket. Issue still affect perks with multiple boxes. First one work correctly. Next don't.

**Comment by Lurkars** [comment]
I now added in [v0.83.13](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.83.13) that you can also click the text of the perk to toggle the state. Hope stat helps.

**Comment by AcidWeb** [comment]
It works.
