### ISSUE TITLE
Random Item Blueprints Scenario and Treasure Rewards

### ISSUE THREAD

**Issue by TheSquinter** [Lurkars/gloomhavensecretariat#274]
Following up from #272 

I think the only reward type missing now is `"randomItemBlueprint": 1` - "Gain one random item blueprint" like in Scenarios 18 and 19.  The rewards have been added in, but label missing.

But I noticed an issue where FH treasures have randomItemBlueprint. It's treating it like a randomitemdesign and drawing a random item:

![image](https://user-images.githubusercontent.com/124784924/235811498-1717711d-72e2-4454-8eb1-ae35e64746bb.png)

In FH, there are Random Items (purple backs) and Random Item Blueprints (blue backs).  So the text for both treasures and scenario rewards should just be "Gain one random item blueprint" and the players can draw from the blueprint deck.

**Comment by Lurkars** [comment]
Okay, take a look. The item availability is also not correct on some parts.

**Comment by Lurkars** [comment]
Added value "blueprint" to items and draw from this now in [v0.62.7](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.62.7). Also added Scenario rewards for `randomItemBlueprint`.

**Comment by TheSquinter** [comment]
The blueprint items are split into 2 sets:
![image](https://user-images.githubusercontent.com/124784924/236618313-aa976fc6-8dbc-4eab-9de9-e477879b4272.png)
![image](https://user-images.githubusercontent.com/124784924/236618323-6ade5eae-9705-43eb-b4fd-22ec71b52be5.png)

That's why I thought it would be better to simply have the reward or treasure say "Gain one random item blueprint" like it is in the book rather than the app actually drawing from the list.

Firstly, you'd need to split the item list up so it doesn't draw from 059-065 (and I don't know when they get added). Secondly, if the players see the reward as 'Gain Laser Lens 052 blueprint" they'd need to spoil themselves by looking for that blueprint in the deck rather than drawing randomly.

Just my thoughts...

**Comment by Lurkars** [comment]
Grrr okay, will take a deeper look. Now working on performance update which will hopefully come later. So put this to backlog now.

**Comment by Lurkars** [comment]
Alchemist Upgrade to Level 3 will unlock the rest, so I will add check for this. Then this can hopefully be closed. Update will come today.

**Comment by Lurkars** [comment]
So should be now fixed in  [v0.63.1](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.63.1).

**Comment by TheSquinter** [comment]
All fixed
