### ISSUE TITLE
Lurker Wavethrower summon ability working incorrectly

### ISSUE THREAD

**Issue by datenshi888** [Lurkars/gloomhavensecretariat#281]
Lurker Wavethrowers have the following ability card

![image](https://user-images.githubusercontent.com/28595867/236821802-bb4b627c-5b95-47ea-ab70-d50e25bd8679.png)

Using the automatic summoning by clicking on the card works incorrectly. It summons for total number of Wavethrowers instead of per type (elite/normal).

Example:
There is 1 elite Lurker Wavethrower and 2 normal ones. Clicking the elite summon part will summon 3 Elite Lightning Eels (Instead of 1), while clicking the normal summon part will summon 3 normal Lightning Eels (instead of 2). 

I'm unaware if there are other monsters with similar summon abilities so I didn't test it on any other monsters.

**Comment by Lurkars** [comment]
Thanks, should be fixed in [v0.63.3](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.63.3). Please verify and close issue if solved.

**Comment by datenshi888** [comment]
Thanks, working now!
