### ISSUE TITLE
Frosthaven Character Summons Killed Upon Lost Focus

### ISSUE THREAD

**Issue by mast3rkryptos** [Lurkars/gloomhavensecretariat#287]
When selecting character summons in GHS, they are killed upon losing focus; the kill can be undo-ed. 

Running from Chrome 113.0.5672.64.

Steps to Recreate:
1. Add character who can summon
2. Add summon though '+' dialog
3. Click summon (can change statuses, etc., or not change anything)
4. Click away from summon details dialog --> Summon is killed.

**Comment by Lurkars** [comment]
Just created a hotfix 2 minutes ago, please wait for [v0.64.2](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.64.2) to be released and verify fix. Thanks.

**Comment by mast3rkryptos** [comment]
Well done, fixed! Thank you!
