### ISSUE TITLE
online Gloomhaven Secretariat not loading

### ISSUE THREAD

**Issue by aragorncan** [Lurkars/gloomhavensecretariat#288]
Hi,

After playing the first scenario (#00), I started the next one (#01) which then displayed the monsters, our characters etc. I shut down the browser since we finished playing for the night. When I launched the browser again later to https://gloomhaven-secretariat.de/ , nothing displays. It's an empty screen. I also tested this with https://ghs.champonthis.de/ and the same thing happens. It's fine if I didn't launch the next scenario though. I do have an older Firefox browser 78.15esr (64-bit) that I can't upgrade due to having an older Macbook Pro (Early 2015). Any ideas? Thanks.

**Comment by alexzhaohong** [comment]
I tried opening both webapps and setting a couple scenarios in Gloomhaven and JoTL campaigns. I am unable to recreate this bug on Safari. I wonder if this is a save data issue?

**Comment by Lurkars** [comment]
App is definetly not tested on older browsers. In general I would still think that a FF 78 should be working. Do you have any privacy settings/extension that may clear the sites data after closing? App is using IndexedDB as storage (with local storage as fallback). Both are local website data that gets stored per site (similar as cookies). This data gets only cleared in private/incognito session or when explicitly setup to do so. So you have other browser available to test?

**Comment by aragorncan** [comment]
I just tried both webapps using Safari 10.1.2. Both times it says that Safari couldn't establish a secure connection to the server for both urls.

**Comment by Lurkars** [comment]
Seems just to old for current state.

**Comment by jgwehr** [comment]
Confirming I have this issue on a pretty old iPad, also. It can't even load the page - just blank. To be expected, though! It'd be nice if apple allowed a different web engine or provided updates, but what are you going to do.

**Comment by TheSquinter** [comment]
It’s working fine on my old iPad Air 2 (2014) in both Safari and Microsoft Edge

**Comment by Lurkars** [comment]
I really want to help everyone, but I can say that I will definitely not start supporting outdated browsers. So I have to say sorry, I hope you understand. Maybe you can find a way to get some backports or so of a modern browser, or get a VM running with an updated OS.
