### ISSUE TITLE
FH Scenario 4 conclusion section link

### ISSUE THREAD

**Issue by odgregg** [Lurkars/gloomhavensecretariat#290]
Completing Scenario 4 leads to section 63.1 and you successfully unlock scenarios 7 & 8, and gain the 1 morale and prosperity

But it doesn't add the section link:
- Add 156.1 to the calendar in four weeks

And there doesn't seem to be a way to manually add sections to the calendar on the party sheet

**Comment by Lurkars** [comment]
Fixed in [v0.65.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.65.0).
