### ISSUE TITLE
Crimson Scale Hail Demon

### ISSUE THREAD

**Issue by JP-Ellis** [Lurkars/gloomhavensecretariat#292]
The hail demon's 6th card has a "target all enemies within {0} with chill". Unfortunately, it looks like there's a placeholder that's not being filled. Should be an easy fix 😁

**Comment by Lurkars** [comment]
Should be fixed in [v0.65.2](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.65.2). Please verify and close issue if solved.

**Comment by JP-Ellis** [comment]
Thank you!
