### ISSUE TITLE
Show/Apply Chill condition

### ISSUE THREAD

**Issue by JP-Ellis** [Lurkars/gloomhavensecretariat#294]
The 'chill' condition applies a -1 to all movements and attacks. I might've missed it, but I could not see a way to apply chill to enemies. It would be awesome as well if that could be automatically incorporated into the calculation that goes on the cards display 😁

Also, I think it would be nice to have if hovering over the calculated attack/move showed the calculation itself (to help remind what is/isn't applied). E.g. "Base 3 attack, with +2 from the ability, -1 from chill" (but with nice icons). Let me know if you want to have that in a separate ticket. I don't think this would be necessary on a phone, but on computer it would be nice.

**Comment by Lurkars** [comment]
I am now very confused by myself. I really thought chill can only apply to characters not monsters. But looking at it, I have no idea why I thought that. Will change this definetly. And than name make it's effect applyable or so to show changed stats. Will think a bit about that one.

**Comment by Lurkars** [comment]
So bug should be fixed in [v0.65.2](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.65.2). Happy about verifying. Keep this issue open to the enhancement of showing/applying Chill condition.

**Comment by JP-Ellis** [comment]
Awesome thank you! I can see the chill condition. And thank you for taking the suggestion on board regarding the calculation hover. I think it would be really good to help avoid confusion of "does this include X and Y effects?"

**Comment by TheSquinter** [comment]
I can think of at least 1 or 2 FH scenarios where monsters get -1 attack via special rules, so if you work out a way to display those effects we could use it for that too.

**Comment by JP-Ellis** [comment]
Very true, this would be wrong. I think the only edge case is in cases where all standees have it, but then it becomes awfully confusing as people would have to check whether _all_ standees have chill or not.

I'll close this ticket :) Thanks!
