### ISSUE TITLE
How to upgrade Barracks in Campaign Sheet

### ISSUE THREAD

**Issue by greatguitartist** [Lurkars/gloomhavensecretariat#297]
Unable to upgrade Barracks to level 2 since events aren't recorded in the app. Summer Outpost Event 15, Outcome A allows the barracks to be upgraded, but the campaign sheet has nowhere to record this outcome.
![Barracks Upgrade Disabled](https://github.com/Lurkars/gloomhavensecretariat/assets/47925938/9a56fb20-d855-4474-848c-5fabd9f45509)

**Comment by greatguitartist** [comment]
Summer Outpost Event 15, Outcome A.

**Comment by TheSquinter** [comment]
You can force upgrades by double clicking/long pressing on 'Upgrade Building'

**Comment by Lurkars** [comment]
I will add an hint for this!

**Comment by Lurkars** [comment]
Added a hint in  [v0.65.5](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.65.5).

**Comment by greatguitartist** [comment]
Thank you
