### ISSUE TITLE
Bug with spawning elite monsters while existing normal monsters have no standee number

### ISSUE THREAD

**Issue by datenshi888** [Lurkars/gloomhavensecretariat#299]
I accidentally found this while testing something else. I don't think it's very likely to happen during normal play. I'm not entirely sure what's going on but I can explain how to reproduce..

This is happening in scenario 16, start of turn 7, but I assume it's not scenario related.

At start of turn 7, a popup instructs you to open section 44.2. Upon applying the section, more popups appear. Applying the popup to summon 2 elite Ruined Machines at G applies incorrectly if there are existing normal Ruined Machines without standee numbers applied. Only one elite Ruined Machine is spawned, replacing an existing normal Ruined Machine.

Example: 
If there's 4 normal Ruined Machines already existing, without assigned standee numbers, only one elite Ruined Machine will spawn and replace one of the 4 normal Ruined Machines, resulting in a total of one elite and 3 normal Ruined Machines.
Existing elite Ruined Machines seem to have no effect on the outcome, regardless of having an assigned standee number or not.

![FrosthavenSpawningBug](https://github.com/Lurkars/gloomhavensecretariat/assets/28595867/4c12df28-eec8-4ce3-b965-0c13d4d98c89)

This issue does not occur if all the normal Ruined Machines have assigned standee numbers.

Additionally, earlier in the scenario one elite Ancient Artillery is spawned at the start of a turn. In this case the summoning worked without issue, even with the presence of two normal Ancient Artillery units without numbers assigned. The difference between the two situations that I can tell are that only one elite Ancient Artillery spawns, as opposed to 2 Ruined Machines, and that Ancient Artillery spawns automatically without any input from the user, as opposed to having to apply the summoning of the 2 Ruined Machines in the original example.

**Comment by Lurkars** [comment]
Maybe this is related to the unspecified standee numbers. I will investigate.

**Comment by Lurkars** [comment]
No chance for me to reproduce this. Played around a lot. Can you check your version?

**Comment by Lurkars** [comment]
Okay, found the issue. Will be fixed!

**Comment by Lurkars** [comment]
Should be fixed in [v0.65.7](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.65.7). Happy if you can verify and close issue if solved.

**Comment by datenshi888** [comment]
Looks to be working!
