### ISSUE TITLE
AMDs frequently don't initialize correctly at scenario start

### ISSUE THREAD

**Issue by tronic101** [Lurkars/gloomhavensecretariat#302]
Our group has now played 6 Frosthaven scenarios with GHS and we've encountered several issues with Attack Modifier Decks (AMDs) at scenario start.

- AMDs sometimes aren't shuffled (they're sorted, starting with the +0s)
- AMDs sometimes don't contain cards from perks selected just before the scenario
- AMDs sometimes remain in the state of the previous scenario (cards are already drawn; deck still contains curses/blesses from before)

**Comment by Lurkars** [comment]
I will take a look if something not working as expected.

**Comment by tronic101** [comment]
Thanks for the quick fix! Seem fine now in a quick test, so I'm closing the issue. I won't be able to test properly until the weekend though. If the issue pops up again, I'll reopen it.
