### ISSUE TITLE
Manual adding/moving/removing calendar events

### ISSUE THREAD

**Issue by tronic101** [Lurkars/gloomhavensecretariat#303]
For the calendar to be truly useful it's required to manually add/move/remove events calendar events (from event cards etc.). Otherwise one has to track those in a second calendar, making this one essentially useless.

**Comment by Lurkars** [comment]
Double click (long press on mobile) on a week to add/exit sections.

**Comment by Lurkars** [comment]
Please close issue if this solves your problem.

**Comment by tronic101** [comment]
Yes, it does. Thanks!
