### ISSUE TITLE
Building from character resources

### ISSUE THREAD

**Issue by tronic101** [Lurkars/gloomhavensecretariat#304]
Currently you can only choose to build, if Frosthaven has all the required materials. This means you must first transfer them from individual characters.

It would be a significant QoL improvement to always be allowed to click the "build" button and then get a dialog which not only asks for the gold from the characters but also all other remaining required resources. Obviously supplies in FH should be used first and preselected, but if those aren't enough the players pick who contributes what for the remaining materials.

**Comment by Lurkars** [comment]
Should be now implemented in  [v0.67.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.67.0). Please verify and close issue if solved. (I hope I didn't break any stuff with this)

**Comment by tronic101** [comment]
It works when the town already has all the required resources (except gold), in which case you wouldn't use character resources anyway. But when the town doesn't, the build/upgrade option is greyed out, even if the town+characters combined have the resources.

**Comment by Lurkars** [comment]
Right, I just added the dialog, but of course also need to fix that logic!

**Comment by Lurkars** [comment]
Should now work correctly in [v0.67.1](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.67.1). Please close issue if test confirm.

**Comment by tronic101** [comment]
It works now. If you want to make a small improvement: it would be nice if town resources were preselected.

Otherwise the issue can be closed. :)

**Comment by Lurkars** [comment]
@tronic101 added that in [v0.67.2](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.67.2)

Please check if it's working as you meant. Then you can close the issue.

**Comment by tronic101** [comment]
Works great, thanks a lot!
