### ISSUE TITLE
Permanently show AMDs

### ISSUE THREAD

**Issue by tronic101** [Lurkars/gloomhavensecretariat#305]
Currently, you need to click to show the AMD of a character and then click elsewhere to close it again, so you can change health or initiative.

It would be nice to always see the AMDs without obstructing other functions (as an optional setting). Maybe the AMD could be to the right next to the character bar?

**Comment by Lurkars** [comment]
Added a setting in  [v0.65.5](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.65.5) under *Interface*: `Permanent Character AM Deck`, when checked the deck can still be opened and close per character but is then shown under the character and the character itself is accessible. Please close issue, if this is solved for you this way.

**Comment by Lurkars** [comment]
Are you syncing settings with server? I may forgot to keep the local value. Setting should not be synced though.

**Comment by Lurkars** [comment]
Okay, should be fixed in [v0.65.6](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.65.6)

**Comment by tronic101** [comment]
Looks good. Thanks!

**Comment by Lurkars** [comment]
Just short info on this, for the old view, the character AMDs are closed on every new round, so in current version, this also closes the permanent view, which seems wrong. So this will be fixed in the next hours!
