### ISSUE TITLE
Tranquil Shoes (item 178) is healing twice

### ISSUE THREAD

**Issue by jorge-graca-sky** [Lurkars/gloomhavensecretariat#309]
https://github.com/Lurkars/gloomhavensecretariat/blob/66a205a7d208c2e2df79287670bdaef0330e3aee/src/app/game/businesslogic/EntityManager.ts#L391

In our last play session the item was triggering but not very well... It sometimes did not trigger correctly, and whenever it triggered it did so at the start of the charater's turn (correctly) and at the end/start of the next one too (effectively healing twice).

Can provide the DataDump of our session, probably still has the turns in the undo queue.

**Comment by Lurkars** [comment]
Thanks, I am already working on a similar issue regarding applying of long rest, so I can reproduce this. This also happens when toggling through summon turns. So will be fixed soon!

**Comment by Lurkars** [comment]
This one was harder then I thought, I hope it didn't break any condition applying, but need fixing for those too, so condition also got applied multiple times. Problem for me is to test every use case and combination, so I really hope I fixed all stuff and don't create new issues. The applying should now work correctly in  [v0.66.3](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.66.3). Please verify and close if solved.
