### ISSUE TITLE
Click on monster ability card to summon opens ability card deck

### ISSUE THREAD

**Issue by tronic101** [Lurkars/gloomhavensecretariat#314]
When a monster has drawn an ability to summon another monster, you can click on the ability text to add that monster as a new summon. However the ability deck also opens unnecessarily.

Examples: Lurker Wavethrower, Prince of Frost

**Comment by Lurkars** [comment]
Should be fixed in  [v0.67.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.67.0). Please verify and close issue if solved.

**Comment by tronic101** [comment]
Works great, thanks a lot!
