### ISSUE TITLE
Crafting cost for item 90

### ISSUE THREAD

**Issue by tronic101** [Lurkars/gloomhavensecretariat#316]
Item 90 should have a crafting cost of 1 Flamefruit and 1 Axenut (and no Rockroot).

**Comment by Lurkars** [comment]
Thanks, will check and fix.

**Comment by Lurkars** [comment]
Should be fixed in  [v0.67.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.67.0). Please verify and close issue if solved.

**Comment by tronic101** [comment]
Fixed, thanks!
