### ISSUE TITLE
"Coral" Class perk not working correctly

### ISSUE THREAD

**Issue by tronic101** [Lurkars/gloomhavensecretariat#317]
When Coral perk "Ignore Item -1 effects..." is selected no item should add -1 cards to AMD. However, equipping item 12 does add -1 cards.

**Comment by Lurkars** [comment]
Will check, must be a bug. Thanks.

**Comment by Lurkars** [comment]
Should be fixed in  [v0.67.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.67.0). Please verify and close issue if solved.

**Comment by tronic101** [comment]
Fixed, thanks!
