### ISSUE TITLE
Adding to Town Guard Deck due to Class retirement

### ISSUE THREAD

**Issue by tronic101** [Lurkars/gloomhavensecretariat#318]
Retiring Bannerspear should add a +20 to the Town Guard Deck. It doesn't seem to be possible to add this card.

**Comment by Lurkars** [comment]
Thanks, currently not implemented. There are also other cards added from events. I will add a menu to manually add those!

**Comment by Lurkars** [comment]
This is now implemented in  [v0.67.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.67.0). 

Go to Global Campaign Sheet and add corresponding section as conclusion. This should add the card.

Please verify and close issue if solved.

**Comment by tronic101** [comment]
There still is one issue: the newly added card has no image.

**Comment by Lurkars** [comment]
Ah, will be fixed!

**Comment by Lurkars** [comment]
Should now work correctly in [v0.67.1](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.67.1). Please close issue if test confirm.

**Comment by tronic101** [comment]
Working as expected now, thanks!
