### ISSUE TITLE
"Random Item Blueprint" received scenario changes over time?

### ISSUE THREAD

**Issue by itemforty** [Lurkars/gloomhavensecretariat#319]
After completing a scenario which rewards a **random item blueprint** and hitting "Success," we see the item blueprint name and number on the **Scenario Summary** page. However, we've noticed that if we let the Summary page sit for too long the blueprint name and number will change. 

We're over WiFi, 4 players' devices, w/ 1 device casting to a Chromecast. Tried testing at home with my wired desktop and two WiFi Android devices and can't get it to reproduce at all. I am seeing each client has their own reward. Canceling and trying again seems to randomize the reward. Closing the app down and reopening seems to sync them up. 

As a side bar for this issue, is there an item database we can manipulate? That could be helpful. Easiest workaround right now is to take the first item we see and if we get a duplicate we pick a different one, but having it all in app is nice. 

Thanks!

**Comment by Lurkars** [comment]
First off all, seems a bug, that it changes. Technically you shouldn't care much. The result only gets applied after clicking the apply button. Afterwards the item get added to available supply. All your unlocked items are visible on the global campaign sheet. Click on the party sheet and then on the campaign sheet title to open the "backside". There you can also manually unlock or remove unlocked items.

**Comment by Lurkars** [comment]
I hopefully found and fixed in issue in [v0.67.7](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.67.7). Happy if you are able to re-test this and close the issue.

**Comment by itemforty** [comment]
We haven't seen it since so I'm going to assume it's all done. Sorry for the late close!
