### ISSUE TITLE
FH party sheet unlock building text box unreadable

### ISSUE THREAD

**Issue by tronic101** [Lurkars/gloomhavensecretariat#321]
Any text entered into the unlock building text box on the FH party sheet is invisible (or white on white).

**Comment by Lurkars** [comment]
Should be fixed in  [v0.67.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.67.0). Please verify and close issue if solved.

**Comment by tronic101** [comment]
Fixed, thanks!
