### ISSUE TITLE
Banner Spear Solo Scenario: Vermling Scout Monster Ability Deck

### ISSUE THREAD

**Issue by sahilthapar** [Lurkars/gloomhavensecretariat#322]
According to the scenario rules, the first card to be pulled from the monster ability deck for the Vermling Scouts is predetermined. 
It should be the card named Rancid Arrow, we were able to resolve this by using "Shuffle" many times till we got Rancid Arrow as the first card but I couldn't figure out a way to set this.

**Comment by Lurkars** [comment]
Already heard of that mechanic. Currently there is no way on setting that up by GHS directly. Maybe it will come, but by now it has to be done manually. You can also use the `edit` function,`reveal all cards` and manually drag the correspond card on top.

**Comment by Lurkars** [comment]
Added special rule for this in [v0.70.5](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.70.5).

**Comment by keinkurt** [comment]
I had test it and it works. Thanks for this fix!
