### ISSUE TITLE
Stacked Poison/Wound Icon Enhancement

### ISSUE THREAD

**Issue by JP-Ellis** [Lurkars/gloomhavensecretariat#326]
With the possibility of stacking poisons and/or wounds, the small icon becomes quite crowded and difficult to read:

![image showning two crowded diamonds with the icon for poison/wound and the stack number below](https://github.com/Lurkars/gloomhavensecretariat/assets/3196162/3c5f1c6d-28db-49fe-8bfd-57aab6856a33)

I think it might look better if this was changed to just a number, with the background colour making it clear whether this is poison/wound (might need to test this for colourblind people):

![image showning the improved poison symbol with only a number](https://github.com/Lurkars/gloomhavensecretariat/assets/3196162/81311b55-abc7-4f28-9444-e0aa0e3ad9ee)

(showing my suggestion for the poison icon, vis-a-vis the old wound)

**Comment by Lurkars** [comment]
Thanks, I see the issue, but doesn't like the suggestion that much. I will play around a bit with it, resizing etc.

**Comment by Lurkars** [comment]
I made the icons a little bigger, but most important, add an hovering state to increase icon size. How that helps.

**Comment by JP-Ellis** [comment]
Thanks! The number is improved a bit, I'll let you know what the other players think the next time we play 😄

I wasn't expecting the hover feature, and it is useful when I'm just inspecting an individual monster; but sometimes it is nice to identify at a glance "who has the most poison so my Attack 0 is effective" or "who don't I need to attack as they will die from their wounds next round".

While testing out the changes, I did notice that the stacks don't show for the players:

![image](https://github.com/Lurkars/gloomhavensecretariat/assets/3196162/bb6f46d6-163f-41ca-8d93-02b2e1035679)

A couple of observations while testing:

- The frost doesn't show up as a stack either (I didn't test that out earlier, just thought of it now).
- When it is hovered, it is difficult to switch to another state. For example, with the wound zoomed in above, I can't switch to the poison easily. Might it be better to zoom all of the effects?

**Comment by JP-Ellis** [comment]
Looks good 🚀
