### ISSUE TITLE
Group Apply Stacked Poison/Wound

### ISSUE THREAD

**Issue by JP-Ellis** [Lurkars/gloomhavensecretariat#327]
The possibility to apply condition(s) to all within a group is great, except that it doesn't apply to difference; instead it overrides the condition for the entire group.

For example, consider an action with adds 1 poison and 1 wound to all creates. If I start with:

![three enemies with wound 1, 2, 3 and poison 0, 1, 4](https://github.com/Lurkars/gloomhavensecretariat/assets/3196162/6d6d076d-491d-4d3c-865b-6bfafe2be883)

and then wish to add one wound and one poison to all with the group action, it ends up overriding the poison and wound status for all:

![three enemies with woudn 1, 1, 1 and poison 1, 1, 1](https://github.com/Lurkars/gloomhavensecretariat/assets/3196162/d22792c7-990d-452a-949a-63e69681a3b9)

These should have wound 2, 3, 4 and poison 1, 2, 5 respectively.

**Comment by Lurkars** [comment]
I am not completely sure, I understand the issue, because that's first all sounds to me like "work as designed". If you select all and change all this of course overwrites previous state! 

What do you think about adding the standees on top of menu to select some to not be affected? A bit like in the character menu? 

![IMG_20230624_141409.jpg](https://github.com/Lurkars/gloomhavensecretariat/assets/2760570/06a2ea59-6ea6-40c4-b93f-faca3973f459)

**Comment by JP-Ellis** [comment]
I think the misunderstanding here is that I'm talking about the group action for the monsters (the black and gray `^` symbols on the right in the images I posted, with `monsters.selectedStandees.all` when you hover):

![image](https://github.com/Lurkars/gloomhavensecretariat/assets/3196162/1df1d816-3154-4d02-a7c6-467b4b5142a3)

Specifically for the stackable effects (e.g., poison and wound), the addition of an effect overrides the individual standees' number. So for example the three Giant Vipers in the above screenshot have:

| Giant Viper | Poison | Wound |
| ----------- | ------ | ----- |
| Elite 7     | 1      | 1     |
| Normal 1    | 2      | 2     |
| Normal 2    | 3      | 3     |

If a character has an action which is "Apply 1 wound and 1 poison to all enemies", I would have expected that the selection as shown in the above screenshot to add 1 wound and add 1 poison to the existing stacks:

| Giant Viper | Poison | Wound |
| ----------- | ------ | ----- |
| Elite 7     | 2      | 2     |
| Normal 1    | 3      | 3     |
| Normal 2    | 4      | 4     |

Instead, the group action overrides the stacks:

| Giant Viper | Poison | Wound |
| ----------- | ------ | ----- |
| Elite 7     | 1      | 1     |
| Normal 1    | 1      | 1     |
| Normal 2    | 1      | 1     |

PS: The same logic should apply to chill.

**Comment by Lurkars** [comment]
Currently there is no "add +1 wound" functionality. There is a "set wound X" functionality. And you can set it to all entities or not. There was no misunderstanding from my side. I just told, that this is work as designed currently. You set a condition for all and overwrite existing state. The condition is then "Wound 2" for example. There is no addition, there is a functionality to set quantity of stackable conditions, this is no addition to existing value.

**Comment by JP-Ellis** [comment]
Oh, sorry I misread then. Happy to close this issue if it works as intended.
