### ISSUE TITLE
Building wall in frosthaven did not add 5 defense

### ISSUE THREAD

**Issue by ronderksen** [Lurkars/gloomhavensecretariat#333]
Last night, we built our first wall in Frosthaven. Walls add +5 defense to the town, however it seems that this is not automated. Maybe a nice feature to add?

**Comment by Lurkars** [comment]
Added now dialogs on building and upgrading buildings with corresponding bonuses. Please check out [v0.78.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.78.0) and give feedback if this solves this issue. Thanks.

**Comment by ronderksen** [comment]
It shows it nicely in the build dialog, but it doesn't actually make a change to this section:
![image](https://github.com/Lurkars/gloomhavensecretariat/assets/16542568/8c5b27a6-c484-4825-b045-12f30527181c)

**Comment by likeaRAINBOW** [comment]
@ronderksen this section contains for morale, walls +5 defense goes to total defense.

@Lurkars in the latest version, morale defence value does not added/removed to/from total defence

**Comment by Lurkars** [comment]
> @ronderksen this section contains for morale, walls +5 defense goes to total defense.
> 
> @Lurkars in the latest version, morale defence value does not added/removed to/from total defence

Thanks for the clarification. Will be fixed! Short question: I assume it's correct that defense can be negative?

**Comment by Lurkars** [comment]
So should be fixed now in [v0.79.5](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.79.5): morale value now gets added to total defense.

**Comment by ronderksen** [comment]
Checked: both morale value and walls update the total defense value! Nice work again, @Lurkars
