### ISSUE TITLE
ToA Ice Meteor - Missing Brittle Condition

### ISSUE THREAD

**Issue by Sr0sh** [Lurkars/gloomhavensecretariat#334]
After adding Rimehearth from Trails of Ashes to a scenario, the brittle condition does not show up as an applicable condition even though it is a condition that's part of several of this class's cards.

**Comment by Lurkars** [comment]
Which edition is set? (Main Menu - Set edition). By now available conditions are set per edition (so base GH don't have brittle available), but of course you're right, that playing a character from different edition should make it's used conditions available. I will fix this. In the meantime as workaround, set edition to "all editions" and all conditions should be available.

**Comment by Lurkars** [comment]
Was definitely a bug in ToA, so missing the conditions there. This should be fixed now in [v0.67.9](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.67.9). I also added feature to toggle specific conditions under "Set Edition", this is first step solving the issue with different characters playing in other editions. As seconds step, I am planning a "smart condition" feature, to only show conditions available for/from current acting figure. But no idea when this will come.

I am happy, if you can test this in [v0.67.9](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.67.9) and close issue if solved. Thanks.

**Comment by Lurkars** [comment]
Damn, thanks for testing. Should be fixed in  [v0.67.10](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.67.10).
