### ISSUE TITLE
FH Solo scenario #16 - Error in escort objectives

### ISSUE THREAD

**Issue by EFinley** [Lurkars/gloomhavensecretariat#337]
As I read the scenario rules, you get six numbered tokens - "place a numbered token in each (b) and (c)".  As coded, it provides two single escorts, with one being sub-labeled (b) and one sub-labeled (c).  Should get fixed such that it provides six escorts numbered 1-6, four of them sub-labeled (b) and two sub-labeled (c) [or omit the sub-labeling entirely].  Their stats appear to be correct, just the quantity of them is off.

Excellent product otherwise, by the way!  Using it heavily for two concurrent FH campaigns with great success.

**Comment by Lurkars** [comment]
Thanks, should be fixed in [v0.67.9](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.67.9). Please verify and close issue if solved. Thanks!
