### ISSUE TITLE
[Firefox] Popup blocker prevents opening character sheet, but no warning given

### ISSUE THREAD

**Issue by Darantius** [Lurkars/gloomhavensecretariat#338]
In Firefox, if you have the standard popup blocker on, character sheets cannot be viewed. This makes sense as it's a popup, but there's no indicator that a popup was blocked or required to view the sheet. I spent a very long time searching for the character sheets before finding where they were and why they weren't opening!

If there's a different way to classify these so that they aren't stopped by popup blockers that would be great. Otherwise, is there an indicator you can use to show the user the character sheet is being blocked?

From a general UI perspective, I feel items like the character sheet should also have dedicated link in the main menu. The character icon shortcut is great, but it should still 'live' somewhere. The same goes for party sheets.

**Comment by Lurkars** [comment]
Hello, I can't imagine that this is related to any default behaviour in Firefox. The sheet is a pop-up from UX perspective, but not in a sense of browser pop-ups requesting to open a new window. Also from  technical POV, the character sheet is same kind of pop-up as the menu, standee menu, character menu etc, so if browser Willie generally block those *pop-ups* the complete app would be useless and not working, not only the character sheet. 

I am using Firefox for most testing etc. and even with *uBlock Origin* enabled, the app is working fine. So please check your extensions and if you accidentally blocked parts of the page. I don't think this is a normal behaviour for other Firefox users and not related to anything wrong on the app.

Besides I like the idea of making the sheets available from menu. Will think about it.

**Comment by Darantius** [comment]
I thought so too, but disabling the blocker allowed me to open the character sheet.

Testing again now however the sheets are loading whether the setting is on or off. Apologies, just a glitch on my end! Perhaps the initial refresh was all that was needed. I'll let you know if I encounter it again. Will close this issue and create the menu improvement separately.
