### ISSUE TITLE
Dedicated menu links for party and character sheets

### ISSUE THREAD

**Issue by Darantius** [Lurkars/gloomhavensecretariat#339]
The buttons to reach the party and character sheets are handy shortcuts, but only once you know them. The character sheet especially requires experimentation or research to find.

Suggest to also add links in the main top-left menu to access both of these resources.

**Comment by Lurkars** [comment]
Added sheet menu in [v0.67.9](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.67.9), please verify and close issue if satisfied. Thanks!

**Comment by Darantius** [comment]
Functionality looks great! Just the terms missing:

sheets -> Sheets
sheets.party -> Party Sheet
sheets.campaign -> Campaign Sheet
sheets.character -> Character Sheets

**Comment by Darantius** [comment]
Love the improved terms! Closing this issue.
