### ISSUE TITLE
Perk Checks Allocated Incorrectly

### ISSUE THREAD

**Issue by sahilthapar** [Lurkars/gloomhavensecretariat#341]
Looks like a new bug has been introduced.

In the finish scenario screen, the characters which were marked as having their battle goals completed did not get those on their character sheet whereas the ones that failed got two marks instead. Looks like the booleans have been reversed or something.

v0.68.0

https://github.com/Lurkars/gloomhavensecretariat/commit/d163f140094d6a18741d4f06cf29dd3037c410ca

**Comment by Lurkars** [comment]
I think was come with https://github.com/Lurkars/gloomhavensecretariat/commit/695476e155d9fbd3f4f886e858115b203084bc3d where I sorted chards on summary. Hopefully fixed in v0.68.1

**Comment by sahilthapar** [comment]
Thanks, will test it over the weekend and close if no issues.

**Comment by sahilthapar** [comment]
Works fine now, thanks
