### ISSUE TITLE
Importing from files not working

### ISSUE THREAD

**Issue by Solmyr14** [Lurkars/gloomhavensecretariat#348]
First off, great app, love it.

My issue is I'm trying to import my backup files on a different computer and nothing happens. I follow these steps:
1) open Data Management,
2) double-click <Import Game from file!>, or <Import Settings from File!>, or <Import Data Dump!>,
3) choose file to import (one of the following: ghs-autobackup-2023-07-23T00 09 42.776Z.json, ghs-game.json, ghs-settings.json, ghs-data-dump.json),
4) click Open

Then nothing happens. If I start a new game, add a couple of characters, then <Reset All Data!>, the page refreshes and all is reset. I expected something similar if I imported a game or data dump, but in reverse where the screen would refresh but with all my imported data now on screen.

As an added note, I'm using Firefox and both computers are running version 115.0.2 (64-bit) if that is an affecting factor.

**Comment by Lurkars** [comment]
I cannot reproduce, can you send me your files please so I can verify? just mail to issue@gloomhaven-secretariat.de

I am using FF myself and mostly do developing with FF, so should not be browser related. Are the files from an older version? Maybe I have some migration bug or so.

**Comment by Solmyr14** [comment]
I've sent the four files I've tried. Both computers are running version 0.69.1.

**Comment by Lurkars** [comment]
Really weird, everything is working fine for me. Can you open the browsers developer console (with F12) and take a look if it outputs something when you import a file?

**Comment by Solmyr14** [comment]
I used the correct files, except for the autobackup, I thought that was a Game file, however I just tried it with Data Dump and still nothing.

I opened the developers console (F12), but unfortunately I don't know much about it and don't know what I'm looking for.

**Comment by Lurkars** [comment]
There should be a Tab "Console", just open it. Then perform import and see if the output there changes, if so, just copy paste here or make a screenshot.

**Comment by Solmyr14** [comment]
Nothing output in there. I cleared the output and tried importing the autobackup, data dump, and game file but nothing appeared in the console. If I reset all data a whole bunch of stuff outputs, same if I do something like add a character, but nothing for importing.

**Comment by Solmyr14** [comment]
Click around the below error would appear sometimes, but didn't seem to affect anything. I also tried a few more times importing, and still nothing showing up in the console.

![Secretariat white space error](https://github.com/Lurkars/gloomhavensecretariat/assets/71523647/be142cc1-a95e-497b-90e9-11861b9a80be)

**Comment by Lurkars** [comment]
Can you try just a different browser? Do you have any extensions installed?

**Comment by Solmyr14** [comment]
I've tried turning off all my extensions (even tried in FF's Troubleshoot mode) and the same thing. Also tried it on a third computer using FF and the same thing again.

It works in Edge, so I'll just use that. 

Thank you for your help.

**Comment by Lurkars** [comment]
Sorry I cannot help you further. I assume you're on windows? Because I run FF on a linux machine, maybe that is making a difference. Do you know, if it worked before? I will try to test this on a Windows machine myself.

**Comment by Solmyr14** [comment]
No problem, thanks for trying.

I am on Windows and tried it on 3 different machines all running the same version of FF. I have no doubt it's somewhere in my settings/config.

I've never tried it until now, but as I said above, it works with Edge, so I'll just use that for running it.

**Comment by Lurkars** [comment]
I changed something about this in https://github.com/Lurkars/gloomhavensecretariat/commit/57b2eee9e13e8e7432f1dc42aeba13cbcd9d2682#diff-08fa8abdae1f340703373f500f509e6334ce264888247a25ef4e428a269aecc4 so maybe you can re-test if you're open to. I had case to reproduce the issue in Chrome, so I was able to investigate a bit further.

**Comment by Solmyr14** [comment]
Just tried and it now works. I was able to <Reset all Data> then tried importing with both the <Import Game from File> and <Import Data Dump> (using the appropriate files) and they loaded up with no problems.

Cheers!
