### ISSUE TITLE
Party sheet

### ISSUE THREAD

**Issue by RobertasKuzmisnkas** [Lurkars/gloomhavensecretariat#349]
Turned on secretariat today. And noticed that party sheet is empty. Also completed scenarios are gone. Tried loading backups (that worked for sure) and same thing. Also after opening one of back up dumps, party sheet information seems to be there.

Edit. Tried web version and desktop app

**Comment by Lurkars** [comment]
Can you send me backups/dumbs to issue@gloomhaven-secretariat.de so I can try to investigate further? Also version, browser and OS information is always useful.

**Comment by Lurkars** [comment]
Hopefully all fixed in [v0.70.1](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.70.1). Please verify and close if solved!

**Comment by RobertasKuzmisnkas** [comment]
Updated client, uploaded back up and everything is back to normal. Thank you
