### ISSUE TITLE
(Bug?) Initiative 99 is automatically a long rest.

### ISSUE THREAD

**Issue by Solmyr14** [Lurkars/gloomhavensecretariat#350]
I noticed that if you put in a 99 initiative it auto-long rests, unfortunately this isn't always the case. The Blink Blade has an initiative 99 card while in Slow Mode (Drive Recharge). I've just been entering 98 to prevent the auto "Long Rest Heal", but it would be nice to not have 99 be long rest since there is already a button to select long rest.

And while I have your ear, I love how when you equip certain items that prevent negative conditions, it will cross them out and actually prevent you from applying them (for example, if you are immune to stun, you can't actually click stun for that character). Is it possible to do the same for perks? The Blink Blade has a perk that prevents being immobilized, it would be great if it would cross out the Immobilize condition like with items.

Cheers.

**Comment by Lurkars** [comment]
Hey thanks,
For the99 initiative: just click on the long rest icon, to disable long rest and make it to normal initiative!

The perks is in backlock, see #315!

Hope that helps, if so please close issue.

**Comment by Solmyr14** [comment]
Just tried the 99/long rest...perfect.

As for the perks, sorry about that, it was late and only looked at the first few.

Thank you again for a great app and your constant work on it.
