### ISSUE TITLE
After successful completion of the scenario in casual mode, rewards are still applied 

### ISSUE THREAD

**Issue by ZabludaNikita** [Lurkars/gloomhavensecretariat#356]
### Describe the bug

When you decide to get back to an already finished scenario and try it again in casual mode, all rewards are applied after successful completion

### To Reproduce

1. Go to "Set scenario"
2. Click on "Disable company mode", select any already completed scenario, successfully complete it
3. Rewards from a scenario are applied to the party

### Expected behavior

Rewards should not be applied if successfully completed in casual mode

### Gloomhaven Secretariat Version

v0.71.6 (or maybe it was previous one, we played yesterday)

### Used Browser

Chrome 115.0.5790.114 (Official Build) (arm64)

### OS

macOS 13.4.1

**Comment by Lurkars** [comment]
Can you please provide edition and scenario? Thanks.

**Comment by ZabludaNikita** [comment]
Sure, the Gloomhaven edition and scenario number 27, but this happened with other scenarios as well, I can't remember which ones though

**Comment by Lurkars** [comment]
Should hopefully be fixed in  [v0.72.2](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.72.2). Please verify and close issue if solved.

**Comment by ZabludaNikita** [comment]
Verified on v0.72.2, issue is fixed

**Comment by ZabludaNikita** [comment]
Verified on v0.72.2, issue is fixed
