### ISSUE TITLE
Unable to Craft Item

### ISSUE THREAD

**Issue by JP-Ellis** [Lurkars/gloomhavensecretariat#357]
### Describe the bug

The new itemshop page is amazing! For items with regular gold costs, it works amazingly; however it does not appear to work for items which must be crafted in Frosthaven.

### To Reproduce

1. Go to a character with at least 1 metal
2. Navigate to the character's item shop
3. Scroll to any item which requires a single metal (e.g. 'Spyglass'). It is surrounded by a red box and cannot be selected regularly:
   
   ![image](https://github.com/Lurkars/gloomhavensecretariat/assets/3196162/5a3cfb0c-bdc7-4487-b955-f3f7296cc0a1)

4. A double click does select it, but the 'Craft' button at the top is greyed out:

    ![image](https://github.com/Lurkars/gloomhavensecretariat/assets/3196162/32bac859-b02e-4cf7-b159-2bedbe608dbe)

### Expected behavior

The 'affordable items' filter should take into account items which are available to be crafted.

### Gloomhaven Secretariat Version

v3.72.1

### Used Browser

116.0.2 (64-bit)

### OS

Windows 10

**Comment by Lurkars** [comment]
Thanks, did some brackets wrong on code migration, will provide a fix today! Thanks for noticing.

**Comment by Lurkars** [comment]
Should hopefully be fixed in  [v0.72.2](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.72.2). Please verify and close issue if solved.

**Comment by JP-Ellis** [comment]
Thanks, looks good to me now!
