### ISSUE TITLE
Assisted Frosthaven support?

### ISSUE THREAD

**Issue by pvh** [Lurkars/gloomhavensecretariat#358]
### Is your feature request related to a problem? Please describe.

I'm a fan of Gloomhaven Secretary but I've started playing in TTS via the Assisted Frosthaven mod which integrates with X-Haven. I don't want to switch, but I'd like to try the integration. I wonder if there's a way to add support?

### Describe the solution you'd like

It'd be great if I could connect to a Gloomhaven Secretary server from the TTS mod and have it help manage my game.

### Describe alternatives you've considered

I guess I could switch to X-Haven but mostly I've been just living without :)

**Comment by Lurkars** [comment]
Since I have no idea about how the mod is working, I don't think I can easily add integration. Have you asked the Dev of the mod, what it thinks about integration? I am open for an integration, but of course busy enough with other stuff, that I won't put high priority on this.

**Comment by Lurkars** [comment]
I will move this issue to the discussion on the corresponding project. If any new issues came up by an integration, then new issues should be created. Until then, it's more up to the TTS mod devs to integrate other helpers (which they seem open to): see https://github.com/gudyfr/fhtts/discussions/32
