### ISSUE TITLE
Improve Summons

### ISSUE THREAD

**Issue by JP-Ellis** [Lurkars/gloomhavensecretariat#36]
While playing through a scenario yesterday, there were a few things about the summons that could be improved:

- [x] There is currently no support to have repeated summons, which is needed in cases where an ability summons multiple creates (for example, the diviner's "Ghost Falcon" summons two at once).
- [x] It would be good to show whether a summon is flying.
- [x] Some items have the ability to summon (which is not linked to any class), but these are not listed anywhere and we have to put in the name and stats manually. This is not really a big issue, but it would be nice if there was an easier way of adding this.

**Comment by Lurkars** [comment]
- For the repeated summons: I already have this info, but just don't do more, then that you can simple add another summon of same type again. So solution would be to just don't close the summon dialog because anyways one need to choose a different token for the other summons.

- Yeah, good idea with flying, I will think about this. Currently the summon actions are only on cards and not on the character summons, I will definetly change this.

- yes I know about the item summons. I wanted to link them only if character has item equipped, but didn't find time. Will definitely come!

**Comment by Lurkars** [comment]
with [v0.25.1](https://github.com/Lurkars/gloomhavensecretary/releases/tag/v0.25.1) I added the item summons, so open character sheet and add item and summon should be available.

More improvements on summons planned, to show also all actions etc. available and also let summon actively act before character.

**Comment by Lurkars** [comment]
In [v0.46.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.46.0) I added active state for summons and showing its stats then. On multiple standees, first is active, double click (long press on mobile) toggle active state.


Example:
![IMG_20230217_205530.jpg](https://user-images.githubusercontent.com/2760570/219778692-b06ece03-2330-4316-a941-c67fd05a0496.jpg)

**Comment by itemforty** [comment]
If it helps, I can confirm that item summons appear to work as suggested, after putting them on the character's sheet. Very handy.

I don't know what "active state" means exactly, and double click/long press don't seem to do anything? Was that abandoned or lost on subsequent updates?

**Comment by Lurkars** [comment]
> I don't know what "active state" means exactly, and double click/long press don't seem to do anything? Was that abandoned or lost on subsequent updates?

Active summon opens the summon sheet as in screenshot. Currently only during round and if summon is already available. Can change that always possible with double click if this helps. For now, just add summon, start round set character active, summon should automatically open. (Can be disabled in settings "active summons", so check if not accidentally disabled)

**Comment by itemforty** [comment]
I was just about to come and edit my comment because I'm a dummy! I threw in a new character, mid-round, but hadn't given them initiative, so it wasn't triggering like you mentioned. Once I added initiative I was able to access that feature. Awesome implementation IMO.

**Comment by Lurkars** [comment]
@JP-Ellis I mark this as solved now. Please re-open if still issues.
