### ISSUE TITLE
Scenario Issues in Forgotten Circles

### ISSUE THREAD

**Issue by mentonin** [Lurkars/gloomhavensecretariat#364]
### Describe the bug

Scenario 96 is missing the 10 exp reward
Scenario 97 shows conclusion selection even though there is only one conclusion possible
Scenario 108 shows only one possible conclusion
Scenario 111 shows only one possible conclusion (may be intended in this particular case?)

### Game Enviroment

Forgotten circles, many scenarios, campaign mode

### To Reproduce

Finish those scenarios as successful

### Expected behavior

All rewards should be applied; Single conclusion scenarios shouldn't ask which conclusion; All possible conclusions should be shown.

### Gloomhaven Secretariat Version

v0.73.0

### Used Browser

Firefox 116.0.3

### OS

Windows 11

**Comment by Lurkars** [comment]
Did you already checked all scenarios or should I check for mistakes in others too?

**Comment by Lurkars** [comment]
I found some more issues with rewards in FC, hopefully that is now all fixed in [v0.74.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.74.0). Happy, when you can verify and close issue on success.

**Comment by mentonin** [comment]
I did some searching of my own and found more issues, I'm working on it on PR #374. Would appreciate your feedback.

**Comment by Lurkars** [comment]
Thanks, I keep this open until PR finished!

**Comment by Lurkars** [comment]
Open issues (from #374):
- [ ] scenario 104 special rules should be changed depending of when the sections were activated.
- [ ] section 132 needs custom special rule to draw extra card

**Comment by Lurkars** [comment]
Special rules for scenario 104 and section 132 added in [v0.75.7](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.75.7). Happy about feedback and please close issue if solved.
