### ISSUE TITLE
Autocomplete when adding achievements

### ISSUE THREAD

**Issue by mentonin** [Lurkars/gloomhavensecretariat#365]
### Is your feature request related to a problem? Please describe.

When adding Party/Global achievements manually (for city/road events, for example), It is frustrating to have to type the whole achievement name, and prone to typos.

### Describe the solution you'd like

A dropdown showing fuzzy matches when adding achievements

### Describe alternatives you've considered

A search button could also work. Blocking non-existent achievements is an option, but why take that freedom away

**Comment by Lurkars** [comment]
I am unsure about party achievements being spoiler? Global achievements are definitely public knowledge cause of the sticker, but anyway one could also argue to handle that as spoiler. So still a bit unsure, need to check/play around a bit maybe with on how many typed chars auto complete starts etc. How difficult it is to detect typos on beginning etc. like for `First Steps` start typing `Fris...` or so. Should it detect? If there isn't a good library for stuff like this. I don't think it's worth the effort. But yeah, in general I will definitely consider adding an auto-complete here. 

Small additional notice: this also applies to FH stickers.

**Comment by Lurkars** [comment]
I now implemented a first draft locally and really run into the spoiler concerns at least for party achievements. I mean global achievements and stickers are not that much a problem I think because you have the sticker sheets out there. But for party achievements I think this will definitely bother some users when entering and see multiple unknown achievements.

**Comment by mentonin** [comment]
That looks like a good approach. For the future, it could be worth changing the achievement system to cover more automations: achievements that can be obtained multiple times could show their number instead of multiple entries, completed achievements could be excluded from the autocomplete list, achievements that replace another achievement could be automated

**Comment by mentonin** [comment]
Issues with the current implementation:

- Hover does not work for mobile. Maybe require 1 click to reveal and another click to select?
- Navigation with arrow keys does not reveal selected item

**Comment by Lurkars** [comment]
I addressed your issues in [v0.75.3](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.75.3). Please verify and give feedback. The counter will be added later maybe, so we can keep this issue open.

**Comment by Lurkars** [comment]
Added show numbers for multiple achievements in [v0.75.6](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.75.6).
