### ISSUE TITLE
Better Personal Quest tracking

### ISSUE THREAD

**Issue by mentonin** [Lurkars/gloomhavensecretariat#366]
### Is your feature request related to a problem? Please describe.

When tracking personal quests, it is easy to forget what you already achieved

### Describe the solution you'd like

Ideally, you would be able to choose a PQ number, and then a button in your sheet to track it would open up, showing quest info and progress track

### Describe alternatives you've considered

Using notes is enough to track your quest, but clumsier. Some quests could also take a lot of space under notes to track.

**Comment by Lurkars** [comment]
In general adding the PQs card information and rewards is definitely on my backlog to-do list. Data input is as always biggest issue on stuff like this. Maybe you can spoil some example, which are hard to track, because we behalf our self also with using the notes feature and in most cases it's just like `kills: 3` for example, so not difficult to track. But also I only directly know the GH PQs...

**Comment by mentonin** [comment]
Even easy to track quests could still benefit from tracking their number and what they are tracking, instead of needing to use notes. For example, just showing something like this:

```
PQ: 513 (Finding the Cure)
Forest Imps killed: 3/8
```

Examples of some difficult to track ones in GH:

- 510, 518, 521, 522, 526, 528, 529: Track which scenarios were already completed for this PQ, which are open, and (optionally) which will open in the future
- 517, 523, 533: track which monsters were killed

**Comment by Lurkars** [comment]
> ```
> PQ: 513 (Finding the Cure)
> Forest Imps killed: 3/8
> ```

I really like that short view without requiring to show the whole card. Will definitely think about adding it like this. Additionally add a line like `"Unlocks: Open Envelope X"` for example.

**Comment by Lurkars** [comment]
So I started with Gloomhaven Personal Quest in [v0.79.1](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.79.1). Happy if you can provide some feedback. Retirement is automatically now when all requirements are fulfilled. 

If you're fine with the result, then we can start adding other editions data. For now, I first want to get some feedback.
