### ISSUE TITLE
Enable more than one edition at the same time

### ISSUE THREAD

**Issue by mentonin** [Lurkars/gloomhavensecretariat#367]
### Is your feature request related to a problem? Please describe.

When playing Forgotten Circles, only FC scenarios show up when setting a scenario. I have to go under campaign management to change over to Gloomhaven, even though FC is an expansion campaign. Under campaign management, it would also be cool to select multiple campaigns to select everything that is in either of them.

### Describe the solution you'd like

Under campaign management, have the edition checkboxes be multiple selection. Scenarios, conditions, characters and others are available according to selection. When selecting from content such as items and scenarios, show selected editions as filters, also multiple selection.

### Describe alternatives you've considered

Careful exclusion of content and selection of All Editions option can solve some problems, but is hacky. Allowing edition swap from scenario selection screen should help, but is probably not enough.

**Comment by Lurkars** [comment]
Forgot about this, as I already added a small change in [v0.74.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.74.0): In scenarios menu, I now just added extended editions to the selection menu. What issue exists by now, is for example the scenario requirements of FC relating to GH which is not implemented yet. So I need to check that. Anyways, the use case of completely mixing edition is to rare to me, to focus on this. In character menu and item menu, you can always toggle to all editions to select what you need and the condition menu is enough to cover the feature of other editions.

**Comment by Lurkars** [comment]
Published now in [v0.75.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.75.0). Happy about feedback and please close issue if satisfied.

**Comment by mentonin** [comment]
On the scenario screen:

- Would like to select GH and FC at the same time
- "Show open scenarios only" should be renamed to "show playable scenarios only" or "Show unfinished scenarios only". Or just "playable/unfinished only".
- "Campaign mode" could be similarly renamed "open only", though that actually changes campaign mode state and I do not know what other effects campaign mode has (but maybe those side effects should not be toggled from scenario selection menu?)

On the itemshop:

- Same as scenario selection, I want the option to filter for FC, GH, or both
- At first I believe it showed an option to toggle between GH and FC items, but now it just shows all items together, I don't know if that is a bug or what

Party/Campaign sheet:

- The scenario list shows only FC scenarios. The dropdown to the right can swap to any other campaign, including GH, but changes the actual campaign instead of just showing GH scenarios (which blocks FC scenarios from scenario select)
- Item section can freely swap between editions without changing campaign, but treasure section cannot, the dropdown is greyed
- Cannot add GH treasures to campaign, uless you change campaign to GH, add treasure, then change back

In general, "All editions" does not fix those problems, because one would want only GH/FC content to be there

**Comment by Lurkars** [comment]
> Would like to select GH and FC at the same time

This is very small comfort for the effort I need to put into this. You can already easily switch edition. The whole scenario menu is designed for single edition and when no edition set and all editions visible, multi-select will just be a mess.

>  "Show open scenarios only" should be renamed to "show playable scenarios only" or "Show unfinished scenarios only". Or just "playable/unfinished only".

Will change to `Only unfinished scenarios`. Hope that will make things clearer.

> "Campaign mode" could be similarly renamed "open only", though that actually changes campaign mode state and I do not know what other effects campaign mode has (but maybe those side effects should not be toggled from scenario selection menu?)

This is added on purpose, the opposite of `Campaign Mode` (to when toggled off) is `Casual Mode` and I wanted an easy toggle on that, if you want to play a scenario in `Casual Mode` that you don't need to navigate through more menus. So will stay. If you don't want casual play, ignore the button.

> Same as scenario selection, I want the option to filter for FC, GH, or both
> At first I believe it showed an option to toggle between GH and FC items, but now it just shows all items together, I don't know if that is a bug or what

Yes this is also on purpose: The Item Shop will list your campaign shop, so all available items. I will leave this also as it is. There is search field, when you need specific items and filter for showing all items which will then be filtered by edition.

>  The scenario list shows only FC scenarios. The dropdown to the right can swap to any other campaign, including GH, but changes the actual campaign instead of just showing GH scenarios (which blocks FC scenarios from scenario select)

Yes, relict before I added the campaign menu entry. So this was meant as complete campaign switch before. But I see that this should be done over Campaign Management Menu. So I will change to just toggle campaign for the sheet.

> Item section can freely swap between editions without changing campaign, but treasure section cannot, the dropdown is greyed

Don't know why, will be fixed.

> Cannot add GH treasures to campaign, uless you change campaign to GH, add treasure, then change back

Related to issue above. 

> In general, "All editions" does not fix those problems, because one would want only GH/FC content to be there

You will be able to select Item and Treasure edition independent of sheet edition.

**Comment by Lurkars** [comment]
The mention fixed should be available in [v0.75.3](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.75.3). Please verify and close issue if solved.
