### ISSUE TITLE
Adding to Town Guard Deck due to SO-62

### ISSUE THREAD

**Issue by oni-23** [Lurkars/gloomhavensecretariat#372]
### Is your feature request related to a problem? Please describe.

Summer Outpost Event 62 (SO-62) concludes to modify the town guard deck.
Option A and Option B modify it differently.

Problem: Our group didn't find a way to modify the town guard deck to add the specific card.

### Describe the solution you'd like

Solution A)
Add a possibility to add cards to the town guard deck.

Solution B)
Add a list of all events (Road+Outposts) where u can mark what u choose and the app acts accordingly.

### Describe alternatives you've considered

Playing with manual cards.

**Comment by mentonin** [comment]
I believe solution A is necessary, even if solution B is implemented

**Comment by Lurkars** [comment]
A quick solution with Option A implemented without further logic will come later today. Option B will come way in future when I started adding event cards (which is planned, but a hell of work).

**Comment by Lurkars** [comment]
Added in [v0.75.3](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.75.3). You should now be able to add different cards in the edit menu of the Town Guard Deck. This is of course a quick solution, but hopefully fixes your issue. If solved, please close. Detailed management with events etc. will be handled on different issue if so.

**Comment by oni-23** [comment]
Thanks, @Lurkars, for this very fast implementation.
At first glance, we couldn't find a +30 without an icon on it. Still, the one with an icon is working fine for us!

Tomorrow I'll research a list of which cards are openly available in the game and mark differences.

Gute Nacht :)

**Comment by Lurkars** [comment]
It seems I overlooked the +30. Anyways, I will just add all cards available regardless of reward type (skipped some scenario reward cards, but maybe easier to just add all).

**Comment by Lurkars** [comment]
Had to add some hotfixes and already added the missing cards in [v0.75.5](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.75.5). So please test with this release to not report already added AMs :wink:

**Comment by oni-23** [comment]
Well done!

open box content ( ✅ if it's in the app)
- -20 ✅
- -20 / +1 resource  ✅
- -10 ✅
- Sucess ✅
- Wreck ✅
- +0 ✅
- +1 hide rolling ✅
- +1 wood rolling ✅
- +1 metal rolling ✅
- +10 ✅
- +10 rolling ✅
- +10 rolling icon(icy shield?) ✅
- +10 advantage rolling ✅
- +20 ✅
- +20 icon(icy shield?) ✅
- +30 ✅
- +30 icon(icy shield?) ✅
- +50 icon(Lurker) ✅
- +50 icon(Unfettered) ✅
- +50 icon(Algox) ✅

there is 1 more in the app – not sure if it's an envelope content
- +50

**Comment by oni-23** [comment]
Well done!

open box content ( ✅ if it's in the app)
- -20 ✅
- -20 / +1 resource  ✅
- -10 ✅
- Sucess ✅
- Wreck ✅
- +0 ✅
- +1 hide rolling ✅
- +1 wood rolling ✅
- +1 metal rolling ✅
- +10 ✅
- +10 rolling ✅
- +10 rolling icon(icy shield?) ✅
- +10 advantage rolling ✅
- +20 ✅
- +20 icon(icy shield?) ✅
- +30 ✅
- +30 icon(icy shield?) ✅
- +50 icon(Lurker) ✅
- +50 icon(Unfettered) ✅
- +50 icon(Algox) ✅

there is 1 more in the app – not sure if it's an envelope content
- +50
