### ISSUE TITLE
chest can't be assigned

### ISSUE THREAD

**Issue by strikegun** [Lurkars/gloomhavensecretariat#377]
### Describe the bug

to assign a chest to an hero, the select is not working. after the scenario, the chest line is empty.

### Game Enviroment

after collecting a chest

### To Reproduce

1. click on the yellow chest item
2. click in the window on a hero
3. nothing happens

### Expected behavior

a hero should be highlighted and in the final scenario sumup the chest should be assigned

### Gloomhaven Secretariat Version

v0.74

### Used Browser

Chrome + Opera

### OS

Android

**Comment by Lurkars** [comment]
You have to select the chest to be looted. There are scenarios with multiple chests, so you need to select chest first before selecting character. I see a qualify of life improvement here to pre-select the chest if only one is listed. Please verify, if it is working as design, so in your steps, you just missed one step. Should work like this:
1. click on the yellow chest item
2. click on the yellow chest in chest window (numbered or `G`)
3. click in the window on a hero
4. click confirm to loot the chest with selected hero.

**Comment by mentonin** [comment]
Can confirm that the current UX is confusing, particularly for scenarios with a single treasure. Maybe adding instruction text would help it? Also allow selecting char and chest in any order.

> **Select Chest:**
> 62
> **Select Character:**
> _Brute_
> Scoundrel
> 
> Cancel ~Confirm~
>

**Comment by strikegun** [comment]
so, I testet it. Forgotten Circles scenario 98. Can be that I miss the selection of the cest.
it works.
Thanks

**Comment by strikegun** [comment]
can be closed
