### ISSUE TITLE
Scenario FH 120 Monster spawns

### ISSUE THREAD

**Issue by mqstout** [Lurkars/gloomhavensecretariat#378]
### Describe the bug

Monster spawns incorrect. On filing, first room should have 1 normal 1 elite hound; GHS only adds one regular.

### Game Enviroment

Web, your hosted.

### To Reproduce

Load GHS, FH Scenario 120, 3 players.

### Expected behavior

Correct hound count.

### Gloomhaven Secretariat Version

075.2

### Used Browser

ffx 1146

### OS

win10

**Comment by Lurkars** [comment]
Thanks, will be fixed in next release (I think today).

**Comment by mentonin** [comment]
#379 should be a straightforward fix

**Comment by Lurkars** [comment]
Please check for issue labels. https://github.com/Lurkars/gloomhavensecretariat/labels/in%20progress means that I am already working on it.

**Comment by mentonin** [comment]
I sent the PR before that, but no problem

**Comment by Lurkars** [comment]
Should be fixed in [v0.75.3](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.75.3). Please verify and close issue if solved.

**Comment by mqstout** [comment]
Loading a new instance of FH 120 with 3 characters has the proper hound spawns for starting the scenario.
