### ISSUE TITLE
Valrath tracker ability card unreadable on FH style

### ISSUE THREAD

**Issue by mentonin** [Lurkars/gloomhavensecretariat#382]
### Describe the bug

The layout for the ability card when FH style is active is different, which can create readability issues, as can be seen in the attached images

GH style:
![image](https://github.com/Lurkars/gloomhavensecretariat/assets/25513875/56c7fe48-984f-40a8-b4aa-d6e1417c07d3)

FH style:
![image](https://github.com/Lurkars/gloomhavensecretariat/assets/25513875/6f806acf-b265-4e79-b46f-478703b8df58)

The text could easily be wrapped earlier.

### Game Enviroment

FH style on

### To Reproduce

With FH style on, add an elite Valrath tracker and reveal its ability card deck.

### Expected behavior

All text should show up on the card. When text doesn't fit, the card should be scrollable and clearly show that some info is hidden.

### Gloomhaven Secretariat Version

v0.75.2

### Used Browser

Firefox 116.0.3

### OS

Windows 11

**Comment by Lurkars** [comment]
Should be fixed in [v0.75.3](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.75.3). Please verify and close issue if solved.
