### ISSUE TITLE
Frosthaven Scenario 66 Section 144.4 Monster spawns

### ISSUE THREAD

**Issue by TobiasRiedl** [Lurkars/gloomhavensecretariat#383]
### Describe the bug

For 4 Players there should be 2 Normal Wind Demons and 1 Elite, but only the Elite one spawns.

### Game Enviroment

Edition: Frosthaven
Scenario: 66
Section: 144.4

### To Reproduce

Play the scenario with 4 characters

### Expected behavior

Spawn all 2 Normal and 1 Elite Wind Demons for 4 players

(Same behaviour like Section 162.4 but with Night Demons instead of Wind Demons)

### Gloomhaven Secretariat Version

v74.0

### Used Browser

Chrome

### OS

Android 13

**Comment by Lurkars** [comment]
Should be fixed in [v0.75.6](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.75.6). If possible, please verify and close issue if solved.

**Comment by TobiasRiedl** [comment]
![image](https://github.com/Lurkars/gloomhavensecretariat/assets/56067484/987553b2-49cc-4cca-803e-735e28fa8765)

Looks good. Thanks!
