### ISSUE TITLE
Frosthaven Scenario 60 - Missing Scenario Reward

### ISSUE THREAD

**Issue by itemforty** [Lurkars/gloomhavensecretariat#384]
### Edition

Frosthaven

### Type of data

Other

### Describe the data affected

Missing Scenario Reward

### Describe the error

There was an errata here https://boardgamegeek.com/thread/3001013/official-faq-frosthaven-no-rules-questions-please that states: 

`Scenario 60 should have Item 224 as a scenario reward`

I noticed that it's not provided upon completing the scenario and wanted to mention it. Thanks for looking!

**Comment by Lurkars** [comment]
Should be fixed in [v0.75.8](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.75.8). As usual, happy about checking and closing if solved. Thanks.

**Comment by itemforty** [comment]
Nailed it, thank you!
