### ISSUE TITLE
Empower/Enfeeble modifier cards

### ISSUE THREAD

**Issue by glenn-fredrx** [Lurkars/gloomhavensecretariat#386]
### Describe the bug

There are certain classes in Crimson Scales/Trail of Ashes that allow you add Empower cards to your own character or those in your party and give Enfeeble cards to the monster deck.  Right now you can only give those cards to the specific characters that have that ability and not to other party members or add them to the monster deck.

### Game Enviroment

This is for any scenario using the specific Crimson Scales or Trail of Ashes characters with empower/enfeeble.

### To Reproduce

Click on any character and unable to add empower or enfeeble chards

### Expected behavior

This should be on all characters and monsters

### Gloomhaven Secretariat Version

0.76.2

### Used Browser

Edge

### OS

Windows 11

**Comment by Lurkars** [comment]
Okay, I think I need to re-read the rules. I thought only the character with the deck can empower and enfeeble itself. It will of course make things a bit more complicated, when multiple characters have an empower/enfeeble deck, need to add dialogs to choose etc. So I think this will take a while for me, to find a good solution.

**Comment by Lurkars** [comment]
So this should now be implemented in [v0.77.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.77.0). I hope I made it right. As before, to use Empower/Enfeeble, a character with corresponding deck must be at the party. Currently this is only ToA Three Eyes and CS Bleeding Claw (with only empower). Anyways if multiple characters with such deck are in the same party, the active figure determine the deck. If no active figure present, you have to select the deck before adding a modifier. I think in most cases this will not be necessary and is not really required, but to keep GHS flexible for custom data and future changes, I added this now. I am happy about feedback, if everything is working as expected. Please still consider, that the AM Card Design is not finally finished, so the cards still look a bit different then the original cards.

**Comment by glenn-fredrx** [comment]
This looks fantastic.  It did some quick testing on both characters and monsters and it is working as expected.  I saw both types of cards being added to the decks.  I am very impressed with how quick you got this enabled.  I really appreciate this app.  It is tremendous what you have created.
