### ISSUE TITLE
Trail of Ashes 3 Eyes Character

### ISSUE THREAD

**Issue by glenn-fredrx** [Lurkars/gloomhavensecretariat#387]
### Describe the bug

Last perk shows as ignore scenario effects.  Should be ignore negative item effects.

### Game Enviroment

Perks

### To Reproduce

View perks for Trail of Ashes 3 Eyes character.  Last one in the list

### Expected behavior

Last perk should say ignore negative item effects.

### Gloomhaven Secretariat Version

0.72.9

### Used Browser

Edge

### OS

Windows 11

**Comment by Lurkars** [comment]
Thanks, will be fixed in next release!

**Comment by Lurkars** [comment]
Should be fixed in [v0.77.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.77.0). Please verify and close issue if solved.

**Comment by glenn-fredrx** [comment]
Looks great.  Super fast response.
