### ISSUE TITLE
Missing Localization for Name of Monster Attacks

### ISSUE THREAD

**Issue by H-K-47** [Lurkars/gloomhavensecretariat#390]
### Describe the bug

![image](https://github.com/Lurkars/gloomhavensecretariat/assets/16805053/90d383d5-d0cf-47d0-96c5-c7e39fcac07b)
![image](https://github.com/Lurkars/gloomhavensecretariat/assets/16805053/c6fb5e97-4b43-4b0b-b546-907854aba083)
![image](https://github.com/Lurkars/gloomhavensecretariat/assets/16805053/2b1f197f-7d53-41e5-8c9d-400fe47840e0)

The name of the attacks add much to the gamplay. They are still in english even when the language has been changed (in this case, german)

Also seems to be the case for static objectives/enemies (stones in scenario 4, sorry havent played far yet)

### Game Enviroment

Jaws of the Lion, e.g. Scenario 3

### To Reproduce

1. Change to German
2. See Monster Attack Cards Names

### Expected behavior

See Translated Monster Attack Card Names

### Gloomhaven Secretariat Version

0.77

### Used Browser

setup.exe

### OS

Win10

**Comment by Lurkars** [comment]
This is not a real bug, more a lack of data. Do you have source for German card names? I am happy to add them, but just have no sources (and don't like free translations on stuff like this...).

**Comment by H-K-47** [comment]
Thank you for answering.

I only have the cards myself. Do you have a property file or something where i could easily see english translation text or a excel sheet where i add the translations in a second column with the monster name/ability (in case they are not literal translations and i have to guess otherwise)

**Comment by Lurkars** [comment]
For JOTL:

```json
  "ability": {
    "Accelerated Power": "Accelerated Power",
    "Angry Howl": "Angry Howl",
    "Black Hex": "Black Hex",
    "Black Tendrils": "Black Tendrils",
    "Boil Blood": "Boil Blood",
    "Booming Scream": "Booming Scream",
    "Calculated Strike": "Calculated Strike",
    "Careful Throw": "Careful Throw",
    "Chilling Breath": "Chilling Breath",
    "Constrict": "Constrict",
    "Coupled Chain": "Coupled Chain",
    "Cripple": "Cripple",
    "Dark Charm": "Dark Charm",
    "Defensive Strike": "Defensive Strike",
    "Drain Life": "Drain Life",
    "Dual Daggers": "Dual Daggers",
    "Explosive Blisters": "Explosive Blisters",
    "Feed": "Feed",
    "Find Cover": "Find Cover",
    "Flashing Claws": "Flashing Claws",
    "Greed": "Greed",
    "Ground Pound": "Ground Pound",
    "Hasty Assault": "Hasty Assault",
    "Heat Blast": "Heat Blast",
    "Hex Whip": "Hex Whip",
    "Hungry Maw": "Hungry Maw",
    "Icy Glare": "Icy Glare",
    "Leech Warmth": "Leech Warmth",
    "Lingering Strenth": "Lingering Strenth",
    "Mana Explosion": "Mana Explosion",
    "Nothing Special": "Nothing Special",
    "Nothing Speical": "Nothing Speical",
    "Noxious Blade": "Noxious Blade",
    "Parry": "Parry",
    "Patch Wounds": "Patch Wounds",
    "Phase Out": "Phase Out",
    "Plasma Ward": "Plasma Ward",
    "Rancid Arrow": "Rancid Arrow",
    "Rapid Bolts": "Rapid Bolts",
    "Reckless Charge": "Reckless Charge",
    "Release Gas": "Release Gas",
    "Restoration": "Restoration",
    "Rotting Embrace": "Rotting Embrace",
    "Runic Draw": "Runic Draw",
    "Runic Feedback": "Runic Feedback",
    "Sacrificial Hurl": "Sacrificial Hurl",
    "Sap Strength": "Sap Strength",
    "Screaming Shot": "Screaming Shot",
    "Seismic Punch": "Seismic Punch",
    "Septic Hex": "Septic Hex",
    "Short Bow": "Short Bow",
    "Spiked Pit": "Spiked Pit",
    "Surround": "Surround",
    "Swarm": "Swarm",
    "Swift Fangs": "Swift Fangs",
    "Taxing Advance": "Taxing Advance",
    "Tip The Scales": "Tip The Scales",
    "Toxic Explosion": "Toxic Explosion",
    "Toxic Frenzy": "Toxic Frenzy",
    "Twin Missiles": "Twin Missiles",
    "Unholy Flame": "Unholy Flame",
    "Unstable Frenzy": "Unstable Frenzy",
    "Unstable Scratch": "Unstable Scratch",
    "Vicious Spear": "Vicious Spear",
    "Vile Scourge": "Vile Scourge",
    "Violent Slam": "Violent Slam",
    "Weakening Bite": "Weakening Bite",
    "Whirlwind": "Whirlwind"
  }
```

Right side become German and then this must be added in https://github.com/Lurkars/gloomhavensecretariat/blob/main/data/jotl/label/de.json#L39

If you are not familiar with PR, you can also just comment the translations here and I will add!

**Comment by H-K-47** [comment]
I made a pull request https://github.com/Lurkars/gloomhavensecretariat/pull/393

Oh boy, now I know why i generally play with the english translation - the translations are just awful I only play the german edition because of my kids. Some bad translation examples: "Rancid Arrow": "Grausiger Pfeil" or "Sacrificial Hurl": "Selbstloser Wurf" or  "Toxic Frenzy": "Giftraserei" - curiously some things are correct which do not require a literal translation like Tip The Scales is correctly translated to be the same meaning in german

Anyway, great Project - thanks for doing this.

**Comment by Lurkars** [comment]
Should be done with [v0.77.1](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.77.1). Please verify and close issue if solved.

**Comment by H-K-47** [comment]
Yup works, thanks

![image](https://github.com/Lurkars/gloomhavensecretariat/assets/16805053/26920928-05b0-4880-85f3-9c47f66c79b1)

**Comment by H-K-47** [comment]
BTW there are two times the same key for doing nothing:

 "Nothing Special": "Nichts Besonderes",
    "Nothing Speical": "Nichts Besonderes",

i think the second one is just a typo from your supplied default and could also be removed. not sure tho

**Comment by Lurkars** [comment]
> BTW there are two times the same key for doing nothing:
> 
>  "Nothing Special": "Nichts Besonderes",
>     "Nothing Speical": "Nichts Besonderes",
> 
> i think the second one is just a typo from your supplied default and could also be removed. not sure tho

Thanks, will be fixed in next release...
