### ISSUE TITLE
Sync Character Attack Modifier Draws to All Clients

### ISSUE THREAD

**Issue by rdoll** [Lurkars/gloomhavensecretariat#391]
### Is your feature request related to a problem? Please describe.

Just played FH with GHS last night and it went well, but we missed seeing each others AM draws. Part of the fun is the cheers on crits and boos on misses.

### Describe the solution you'd like

Same UX, just sync opening the AM deck and drawn cards to all clients.

### Describe alternatives you've considered

As a stopgap improvement, we could just flash the drawn cards to other clients, either in the characters nameplate or in/near the footer.

### Additional context

If you aren't already working on or planning to work on this, I may be able to help. Please feel free to describe any solution nuances or details that could help.

**Comment by Lurkars** [comment]
So the draws should be already synced. The only thing that's not synced (on purpose) is the expanded state. This is mainly for the use case of people managing their deck on mobile and having a main screen that's shouldn't get distracted. To get what this issue is asking for, every client who wants to see the deck can just expand it with one click. So changing this can break other's usage. The only solution could be adding a setting for this, but this will require some server and logic changes. So I would first ask if you have considered using the "Permanent Character AM Deck" setting and just expand the deck on every client once. Maybe this is enough for you.

**Comment by rdoll** [comment]
Great info, thanks. Permanent AM deck is the way to go today, but there may be some alternatives.

Solutions with shortcomings:
- Permanent AM deck alone
  - Definitely works on desktop, tablet and mobile viewports
  - Setting is intentionally client local, so all clients would have to enable it
  - Takes up a lot of vertical space, esp with 4 characters

- Sync nameplate overlay
  - Would want a client local setting to control this
  - Would be too small for mobiles
  - Def not doing this

Possible solutions:
- Flash remotely drawn AM cards inside character's nameplate
  - When a remote AM card is drawn, animate it coming out of the crossed swords button, flipping over and showing the drawn card nearly the full height of the nameplate. It would fade after a few seconds or on click.
  - New client local setting to enable/disable this behavior. If Permanent AM deck is enabled, this is force disabled.
  - If AM deck is already open, this new alert is not shown; the alert is only shown if you cannot otherwise see the drawn card

- Broadcast AM deck opens/closes to all clients
  - When Permanent AM deck is selected, enable a sub-setting for "and match remote clients open/close"
  - When any client opens or closes any character's AM deck, remote clients with "and match remote clients open/close" would open or close it too
  - I'd want to be careful about remote actions modifying the local UI, so we'd have to see how this feels

- Flash remotely drawn AM cards on/above the footer
  - Temporary alert dialog would be character class color, show class icon, character name and drawn cards
  - Would have a new setting for "always show", "never show" or "only show if character's AM deck isn't already visible"; maybe force to "never show" if Permanent AM decks is enabled
  - Temporarily consumes screen space, but could be minimized by making it overlay the footer
  - I can't think of a case where this would happen in a real game, but multiple characters drawing AM cards would either overlay each other's alerts or alerts would stack up towards screen top

I'm leaning towards flashing the drawn AM cards inside the character's nameplate, but lemme know what you think. This has enough complexity that I don't want to rush anything that might negatively impact the UX. I don't know the roadmap, but we could also park this if other things have priority. But if you are up for it and we can arrive at a good approach, I'm game for trying :).

**Comment by Lurkars** [comment]
So I played around a bit yesterday and just added a setting to enable/disable sync the `opened state`. If disabled on a client, the deck state is just not synced. In general this is working fine and should solve this issue. Now I only have one problem:
- to sync the state, every open/closing will add a new `undo` game state
- a client with disabled settings has then an `undo`-list to "control" other's AM deck state without any visible state on it's client (is this understandable what the problem is?)

So User A has sync enabled, User B not

- A opens/closes deck multiple times
- visible state in B is same, but undo-history is full with the changes from A
- B clicks undo, visible state doesn't change for B, but the AM Deck of A opens/closes...

Not sure if this is a real problem when using the app, was just my test environment, where I run it and it felt just really weird controlling the others AM deck state without any visual state change (because AMD sync disabled). Maybe you can also put some thoughts in this.

General to your feedback: I really like the idea with the flashing cards, will think about this also.

**Comment by rdoll** [comment]
Ah, right. If all multi-client events are communicated as game state changes, we'd end up with a lot of game state changes that effectively do nothing but clutter up the undo stack. Alternatively, if we added the ability for clients to broadcast non-game state events to each other (through a new server endpoint), clients that joined after the broadcast will start "out of sync". I'm not a fan of either solution.

So that leaves nameplate flash and footer flash. I slightly prefer a nameplate flash, but I think a footer flash would work well too. The trick is to make the flash alert eye catching, yet unobtrusive, while being readable on a mobile.

Slightly different idea: what if there was a client local setting for "show the current character's AM deck below their nameplate", which can only be enabled if "Permanent AM deck" is enabled? Since there is only one currently active character, this alleviates the vertical space concerns and ensures all remote draws are shown. This doesn't solve every client having to enable it to see remote AM draws, but this could be done in addition to flashing a remotely drawn AM card.

Regardless of "show the current character's AM deck below their nameplate", nameplate and/or footer flashing could be useful. Let me know how you want to proceed. Thanks.

**Comment by Lurkars** [comment]
I really like the idea with the active characters toggle. Directly tested it now and will come later! Seems at least to be the fasted solution to solve the problem in general for you. 

And yeah, as said besides all that, I also like the flashing idea, but this will be put to backlog for now I think.

**Comment by rdoll** [comment]
Awesome! I'll look forward to those changes and I'll be sure to validate them.

And thanks for being so willing to hear out new ideas. Your efforts are appreciated.

**Comment by Lurkars** [comment]
You can directly checkout the new [v0.77.2](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.77.2). The setting is directly under `Permanent AM Deck` as `Autom. active AM Deck`.

**Comment by rdoll** [comment]
Validated it locally with one client, with two clients and with someone helping remotely. It works perfectly and exactly as designed. I even noticed that if a client manually opened the AM deck, the auto-close when the character is no longer active does _not_ close the AM deck. That feels like a nice touch for clients that, for example, always want their AM deck open.

I think the `Auto. active AM Deck` option is closed in this issue. If you want to close this issue, I can open a new one just for flashing. Or I'm happy to keep this open too. Either way -- thanks for the feature add. I hope others enjoy it as much as me and my group will!

**Comment by Lurkars** [comment]
Added a draw animation on closed character AM decks in [v0.77.5](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.77.5). Can be disabled in settings. Happy about feedback.

**Comment by rdoll** [comment]
This is fantastic; it's just what I had in mind! I validated it and it looks great. 

My only note is that I found that 2500ms felt a bit better than 3500 millis, esp. when simulating Advantage/Disadvantage drawing. I can do a PR for that, but I suspect you'll want to see how it feels for yourself, so probably just as easy for you to do it while there -- if not, lemme know.

Thanks!

**Comment by Lurkars** [comment]
I'll check and pay around. My initial thought was, that it should be long enough, that if you're not focusing and see "some movement" on screen, that's it's still long enough to recognise the card. Of course that come to the price, that's it's long if you're already focusing.

**Comment by Lurkars** [comment]
Okay, I played a bit around and confirm now that 2500ms felt better! So changed now in  [v0.77.7](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.77.7). Please verify and close.

**Comment by rdoll** [comment]
Verified. And I also verified the bug fix for the AM draws showing on the nameplate when the permanent AM deck was shown. I was gonna fix that, but you beat me to it! 😄
