### ISSUE TITLE
Enemy doesn't die if they have shield

### ISSUE THREAD

**Issue by mhalttu** [Lurkars/gloomhavensecretariat#396]
### Describe the bug

When you drag the health of an enemy to zero, they don't die if they have the shield. The problem seems to be line 90 in EntityManager.ts. Is this intentional so we can show the shield animation? Should the enemy die after the animation has completed?

### Game Enviroment

Scenarios with enemies with shield

### To Reproduce

1. Go to scenario 32
2. Click on a frozen corpse and adjust their health by dragging
3. Drag the health to 0

### Expected behavior

The entity is removed (as dead)

### Gloomhaven Secretariat Version

v0.77.2

### Used Browser

Chrome

### OS

OS X

**Comment by Lurkars** [comment]
Ouch, thanks for noticing! Will be fixed ASAP!

**Comment by Lurkars** [comment]
Should hopefully be fixed correctly in [v0.77.3](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.77.3). Happy if you can verify and close issue if solved.

**Comment by mhalttu** [comment]
Fixed, thank you!
