### ISSUE TITLE
Scrolling cancels the "drag to adjust health" gesture

### ISSUE THREAD

**Issue by mhalttu** [Lurkars/gloomhavensecretariat#397]
### Describe the bug

On an iPad, any vertical touch scrolls the UI. It's very easy to accidentally scroll instead of adjusting the HP of an enemy by dragging horizontally. What's worse, the HP adjustment action is "cancelled" and the number representing the health change just floats in the UI without affecting the health of the enemy. 

Perhaps scrolling could be completely disabled if you touch a standee? At the very least, the drag should not be cancelled when scrolling starts.

I think the problem is line 136 in main.ts where we call `this.pointerInputService.cancel();` which causes `dragHpEnd` not to get called in `standee.ts`.

### Game Enviroment

Any scenario as long as you have enough characters and enemies to enable scrolling.

### To Reproduce

The easiest is to just use an iPad, but if you don't have one available you can do as follows as long as you have a laptop:

1. Use Chrome on a PC
2. Use the trackpad of your laptop to start scrolling. Stop scrolling but keep your fingers on the trackpad.
3. Use your mouse to adjust the health of an enemy by dragging. Don't let go of the mouse button.
4. Move your fingers on the trackpad to scroll more.

### Expected behavior

The scrolling should be prevented or at the very least, the dragging action should not be canceled.

### Gloomhaven Secretariat Version

v0.77.2

### Used Browser

Chrome

### OS

Windows 11

**Comment by Lurkars** [comment]
I think, I really have issue solving this. So first, it's clearly a bug to be fixed, that the `pointerInputService.cancel();` do not clear the drag state and I will definitely address that.
Now changing the general behavior with dragging and scrolling will end up in one of two new issues
- you accidentally change values while trying to scroll (so exact the opposite issue than now, but I definitely think that accidentally change of values is worse then accidentally cancel adjusting and scrolling instead)
- disabling scrolling while dragging will disable scrolling on those elements, which will lead to issue like "Scrolling is not working"

I had both issue before, that's why I ended in this behavior. The only solution I can think of is like a scroll "threshold", have to check if this is supported somehow or if I do it manually: so that scrolling only starts after a certain distance or duration...

**Comment by mhalttu** [comment]
Agreed. Based on what you wrote, I think it might be enough to simply fix the bug with the `pointerInputService.cancel()` clearing the drag state.

**Comment by Lurkars** [comment]
So the cancel stuff should be implemented in [v0.77.3](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.77.3). If this is enough for you, then please close issue. Otherwise we can discuss further improvements here.

**Comment by mhalttu** [comment]
Unfortunately, this fix did not work as I hoped. The drag action is now cancelled, which is arguably better than before but it's still next to impossible to adjust health by dragging on an iPad. Please see the attached video: https://github.com/Lurkars/gloomhavensecretariat/assets/848708/682e41dc-0f9e-4b13-9ad4-30a006a2e0cc

My hope was that the drag action would not be cancelled. Instead, it would just continue even with the scrolling and the final `dragHpEnd` method would be called when the finger is lifted. I believe this would solve the issue properly without causing unintended side-effects.

Another option would be to look into making the scrolling less sensitive so you can't trigger it accidentally. However, I believe my previous suggestion would be the better fix.

**Comment by Lurkars** [comment]
Investing/Testing futher, I am really confused how iPad (Safari) is acting. In general I now see, that I already implemented that if you start dragging, the body element gets the class `no-pointer` with
```css
.no-pointer * {
   pointer-events: none;
}
```
Which should prevent any scrolling effects. Adjusting HP and scrolling etc. is working really fine on my Android Phone.

**Comment by Lurkars** [comment]
@mhalttu possible that there is a setting like "smooth scrolling" or so? Would be happy now with the report that it's working fine on other iPad, that you can check your settings, version etc.

**Comment by mhalttu** [comment]
I don't think I have customized any settings in Safari, i.e. I couldn't figure out a setting such as "smooth scrolling". The iPadOS version is 16.6.1 and this is an iPad Pro (11-inch). I also tested with an iPhone 14 Pro running iOS 17 and was able to consistently reproduce the same issue. 

@Sr0sh can you test with an iPhone?

**Comment by mhalttu** [comment]
I was now able to reproduce the situation @Sr0sh described. It's still unclear to me what changed. I think it may have something to do with with "zoom level". I can (intentionally or accidentally) pinch the screen which changes the size of the UI elements. It seems like on some zoom levels, the scrolling is locked properly and on others it is not. But it's very difficult to figure out the exact logic.

**Comment by mhalttu** [comment]
I tried resetting the zoom and it didn't make any difference. I'm sure there is a pattern, but the behavior seems almost random to me. Sometimes the scrolling is properly disabled for multiple zoom levels and at other times it is broken and changing the zoom level doesn't seem to help.

I do have one additional insight: It's much easier for me to reproduce the problem when I'm using the app added on the home screen. If I simply use it from the browser, it works much more reliably. 

@Sr0sh could you try to add the app on your home screen and try reproduce the issue? Try fiddling with the zoom level too.

**Comment by Lurkars** [comment]
Okay, make at least some sense. For me now an obvious solution: don't allow more zooming than full width (so no side scrolling possible). Do you find any reason, that a higher zoom level than the full width is required? 

I mean I can also let the menu zoom be force-able with double-click/long press or so, that would mean, one cannot accidentally zoom over full width, but if one really wants this, still possible...

**Comment by mhalttu** [comment]
A couple of observations:

- Good job with the theory, @Sr0sh. Unfortunately, it isn't as clear cut for me. I've had this bug happen to me even when there is no apparent horizontal scrolling. However, I do think you may be onto something.
- This issue is still much more prominent for me when using the home screen shortcut. I played a session yesterday straight from the browser and it worked like a charm.

All in all, we could try to limit zooming to more than the full width and see if it makes a difference. Personally, I can just keep playing in the browser instead of the home screen app but of course it would be nice to get this resolved.

**Comment by Lurkars** [comment]
So at least I now added the zoom cap in [v0.77.8](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.77.8). Still confused how you are able to vertical scroll in any way when zoomed out. Is there really something scrolling? Sound really strange to me, do you have changed the barsize or so that there is less space somehow?

**Comment by mhalttu** [comment]
Thank you for trying to fix this issue. First of all, I do think it makes sense to limit the maximum zoom to a reasonable value. Unfortunately, the change did not seem to help. When I've added the app on the home screen and I reset the zoom level, I can still scroll horizontally a bit. And even if I zoom out so I can't scroll horizontally, I can still reproduce the bug pretty reliably. On the other hand, it is much harder to reproduce the issue when running the app in Safari.

This turned out to be a much more difficult issue than what I expected. I'm happy keep using the app in the Safari, and I'm OK with closing this issue for now. Alternatively, you can try to take another stab at it when you have access to an iPad yourself. 

Either way, I truly appreciate all the effort you've put into making this wonderful app!

**Comment by Lurkars** [comment]
So I'm now having access to an iPad. Besides I am currently unable to really get a Debugger running, because I only have power cable but no real data cable, I first thought, that I can easily reproduce this issue. But it just appeared once and now I am unsure if am just used to the touchscreen, but I just cannot reproduce. At least not more as on my Android Phone like "forcing" to really do bad acting with scrolling up and down instead of left right.

**Comment by mhalttu** [comment]
It's a weird issue because sometimes it doesn't happen at all and sometimes it happens all the time. Some suggestions:
1. When on the website on Safari, press the "Box with an up-arrow" at the bottom and select "Add to Home Screen"
2. Start from the home screen and select a scenario with enough opponents. Consider unlocking multiple rooms at once to make it easier.
3. If you still can't reproduce this, use the pinch to zoom to zoom in to the maximum zoom level.

If you still can't reproduce this, perhaps it's ok to close this issue. I can live with the current functionality even though it still does get a bit frustrating sometimes. :)
