### ISSUE TITLE
Geminate x2 perk 

### ISSUE THREAD

**Issue by ARMD76** [Lurkars/gloomhavensecretariat#402]
### Describe the bug

Game is autoshuffling at the end of the round after x2 perk shows up (no additional null or natural x2 showed during round). I can’t find anywhere an official rule for this card modifier, but the symbol for shuffling is not present on this card, this is why I think this isn’t the right behavior.

### Game Enviroment

Any scenario, just add geminate with this perk.

### To Reproduce

1. Add geminate with perk and auto shuffling on
2. Start a round and draw until any x2 or null card shows up
3. If it is not the perk one end the round and repeat 2
4. Once the perk one shows up end the round and see how deck modifier autoshuffles 

### Expected behavior

It should not shuffle modifier deck as in blessing effect

### Gloomhaven Secretariat Version

v0.77.5

### Used Browser

Safari 

### OS

iOS 16

**Comment by Lurkars** [comment]
Thanks for the report, will be fixed soon!

**Comment by Lurkars** [comment]
Thanks for the report, will be fixed soon!

**Comment by Lurkars** [comment]
Should be fixed in [v0.77.6](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.77.6). Happy if you can verify and close issue if solved. Thanks.

**Comment by ARMD76** [comment]
Fixed for v0.77.7. Thanks!
