### ISSUE TITLE
Touch Devices: Long Pressing Conditions for Removal Opens Native Share Dialog

### ISSUE THREAD

**Issue by Sr0sh** [Lurkars/gloomhavensecretariat#407]
### Describe the bug

If the _Long press for double-click (Touch)_ setting is enabled, long pressing a condition will open up the native Share dialog for image files. Condition is still removed after closing that dialog.

### Game Enviroment

Crimson Scales QA2 Mother Lode

### To Reproduce

1. Add a condition to a figure
2. Long press on the condition

### Expected behavior

Long pressing won't open the native Share dialog.

### Gloomhaven Secretariat Version

v.0.77.8

### Used Browser

Safari

### OS

iOS 17.0.2

### Additional

Tested on iPad 10

**Comment by Lurkars** [comment]
I really start hating Apple...The context menu should be disabled in general to avoid this. I can only test on Android by now, but seems working. Anyways, I have a few Safari specific issues I need to address and will therefore borrow an iPad to address those. But to say, this will take a longer time than other issues now.

**Comment by Lurkars** [comment]
I now have access to an iPad and I hope to solve this  concrete issue in [v0.78.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.78.0). Happy about feedback!
