### ISSUE TITLE
Cannot finish Scenario

### ISSUE THREAD

**Issue by pikdonker** [Lurkars/gloomhavensecretariat#408]
### Describe the bug

We've been using your excellent app for a while now for our campaign, but it seems we've hit upon a strange bug. Whenever we want to finish a Frosthaven scenario we just get an empty modal and an error in the console:

![image](https://github.com/Lurkars/gloomhavensecretariat/assets/58171422/8525f2c0-deec-4f6b-8bd3-921ab984251e)

![image](https://github.com/Lurkars/gloomhavensecretariat/assets/58171422/86649f5a-98ff-4c01-941b-391f7acf4aba)

I have force updated the app, reset our campaign, manually reset the index DB, tried in private mode with the first scenario, but always with the same result.. 

### Game Enviroment

Frosthaven 001.

### To Reproduce

Open a private window, set the game to frosthaven, manually set the first scenario, click the scenario name in the footer, click on Success.

### Expected behavior

Scenario should be succesfully finished.

### Gloomhaven Secretariat Version

0.77.10

### Used Browser

Firefox 118

### OS

Win 10

**Comment by Lurkars** [comment]
I cannot reproduce with characters, but without characters. Do you play without characters? I hope so, then bug will be fixed "in a minute" and I'll ping you here again to verify.

**Comment by Lurkars** [comment]
So [v0.77.11](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.77.11) is currently deploying and should fix the issue. Happy if you can verify and close issue if solved.

**Comment by pikdonker** [comment]
> I cannot reproduce with characters, but without characters. Do you play without characters? I hope so, then bug will be fixed "in a minute" and I'll ping you here again to verify.

Yeah, we play without characters. So yes, this is fixed. Thanks very much for the quick fix!
