### ISSUE TITLE
Scenario 68 boss hit points incorrect

### ISSUE THREAD

**Issue by dfannius** [Lurkars/gloomhavensecretariat#409]
### Edition

FH

### Type of data

Monster Stat/Ability

### Describe the data affected

Scenario 68 boss hit points

### Describe the error

v0.77.11. The boss in Frosthaven scenario 68 has "H×C×3/2 hit points (rounded down)". For our party of 3 characters at level 4 (where an elite Chaos Demon has 21 hit points), this should be 94.5 rounded down = 94. Instead it is rounded up to 95.

**Comment by Lurkars** [comment]
Thanks for noticing will be fixed in next release!

**Comment by Lurkars** [comment]
Should be fixed in [v0.77.12](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.77.12)

**Comment by dfannius** [comment]
Looks good, thanks!
