### ISSUE TITLE
When receiving an random item during the loot, make it optional to draw an item for you.

### ISSUE THREAD

**Issue by skahunter** [Lurkars/gloomhavensecretariat#411]
### Is your feature request related to a problem? Please describe.

It feels when you loot an random item, you get an item but it is not shown.

### Describe the solution you'd like

At this stage I believe an item automaticly unlocks, but we much prefer to draw a random item ourselves. It would be nice to get a prompt asking, do you want to draw an random item? and alternatively give an input field that can be used to input what item you have (physically) picked.

### Describe alternatives you've considered

Display what item is unlocked or gained.

**Comment by Lurkars** [comment]
Definitely thought about this before, but just forgot about this! Will add a  popup showing the received item for sure. And yes, than I can also easy add a button to decline this, so you can pick physically.

**Comment by Lurkars** [comment]
So in [v0.78.2](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.78.2) I now added dialog with item. If you want to draw your own item, disable "Draw Random Item on Loot" under Frosthaven Section in Settings! Happy about feedback and if this is solved for you, please close issue.

**Comment by skahunter** [comment]
Seems to work!
