### ISSUE TITLE
Building 85 isn't taken into account when creating new buildings

### ISSUE THREAD

**Issue by skahunter** [Lurkars/gloomhavensecretariat#412]
### Is your feature request related to a problem? Please describe.

When creating a new building when building 85, the carpenter has been build, you should receive 1 discount to any of the material costs. At this moment it doesn't take that into account.

### Describe the solution you'd like

Add a column when the Build dialog that allows you to make one of the materials costs lower.

### Describe alternatives you've considered

At the moment we will pay for it and either increase one of the items we have in FH or refund it after building it .

**Comment by Lurkars** [comment]
Short question on this: "Construction costs" only include Building and Upgrading, not Repair/Rebuild or does it include all?

**Comment by Lurkars** [comment]
Implemented in [v0.78.2](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.78.2). Please provide feedback and close if solved.

**Comment by skahunter** [comment]
Even a better solve! Thanks
