### ISSUE TITLE
Gloomhaven - Error when trying to see the Campaign page

### ISSUE THREAD

**Issue by luisfernandoquintero** [Lurkars/gloomhavensecretariat#413]
### Describe the bug

We are unable to see the "Campaign" page for our Gloomhaven game.  We just get an empty sheet where it usually displayed all the scenarios we have played so far, our current prosperity level and the unlocked items and treasures.

I am attaching the exported JSON files for your reference (extensions renamed to .TXT so it allows uploading)

[GH-2023-10-02-ghs-settings.json.txt](https://github.com/Lurkars/gloomhavensecretariat/files/12796979/GH-2023-10-02-ghs-settings.json.txt)

[GH-2023-10-02-ghs-data-dump.json.txt](https://github.com/Lurkars/gloomhavensecretariat/files/12796981/GH-2023-10-02-ghs-data-dump.json.txt)

[GH-2023-10-02-ghs-game_Lyd Masters.json.txt](https://github.com/Lurkars/gloomhavensecretariat/files/12796982/GH-2023-10-02-ghs-game_Lyd.Masters.json.txt)

### Game Enviroment

We are using version v0.77.12 and we are using it to play GloomHaven.  See the description for the uploaded JSON files and the description of the problem.

We have tried with both Chrome and Firefox and the bug is there all the time.

### To Reproduce

1. Go to the Party Sheet
2. Click Campaign
3. The Campaign page apperas, but it's not showing any data at all...
4. After closing it, a blank small square appears at the top-left section where the main menu icon appears

[SEE ATTACHMENTS]

![Image - 2023-10-03 16-16-02](https://github.com/Lurkars/gloomhavensecretariat/assets/433633/940305c8-b086-4f9a-bfd3-0050aeeaf6c3)

![Image - 2023-10-03 16-16-53](https://github.com/Lurkars/gloomhavensecretariat/assets/433633/4584b390-36d5-49c9-a7e5-02ead38c8baa)

### Expected behavior

We should be able to see the Campaign page fully populated, but we are just receiving an empty page instead.

### Gloomhaven Secretariat Version

0.77.12

### Used Browser

Chrome Version 117.0.5938.92 (Official Build) (64-bit)

### OS

Windows 11

### Additional

Please let me know if you require something extra and I will be glad to send it to you.

Thank you for this wonderful tool!

**Comment by Lurkars** [comment]
Hopefully this is fixed now in [v0.77.13](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.77.13). Happy if you can verify and close issue if solved.

**Comment by luisfernandoquintero** [comment]
Thank you!  The bug is fixed.  Ko-Fi is on me!  Please keep up the good work, much appreciated.
