### ISSUE TITLE
FH Scenario 42 Night Demons are Allies

### ISSUE THREAD

**Issue by rdoll** [Lurkars/gloomhavensecretariat#414]
### Edition

FH

### Type of data

Scenario/Section

### Describe the data affected

Scenario 42, section 63.3

### Describe the error

Night Demons spawned as allies.

![image](https://github.com/Lurkars/gloomhavensecretariat/assets/7015158/81c2ff85-56a6-404b-8593-14f727759f22)

### Additional

It's possible we did this by toggling it ourselves. If the GHS data is correct, there may be value in discussing ways to make this a tad clearer, since it's pretty easy to swap ally/enemy on the main screen.

**Comment by Lurkars** [comment]
Must be done by accident. When I start Scenario 42 and add Section 63.3, Night Demons are no allies and data also doesn't contain any ally data!

**Comment by rdoll** [comment]
Great, thanks.

Any thoughts minimizing the chance of this type of user error? There should be very few times where you need to swap allies/enemies, so it's not something that warrants main screen control, IMHO. What about moving it to the monster stats dialog, something like this?

<img src="https://github.com/Lurkars/gloomhavensecretariat/assets/7015158/d97d61f1-85eb-4eee-98bf-baa35b36d3cf" width="200px" /> <img src="https://github.com/Lurkars/gloomhavensecretariat/assets/7015158/ac4e09a2-9e50-40e7-b939-106167636c80" width="200px" />

**Comment by Lurkars** [comment]
Yes also valid concern. This initially comes before I added automatic adding of standees and marking monsters as allies. So before, it was important to easy switch ally to fulfill the scenario rules manually. Now that this is automated, there isn't really a requirement for this, so moving to the sheet seems reasonable. I add a point to #160
