### ISSUE TITLE
When playing Frosthaven, itemshop doesn't show unlocked Gloomhaven items

### ISSUE THREAD

**Issue by TheHankerChief** [Lurkars/gloomhavensecretariat#415]
### Describe the bug

I started a Frosthaven campaign and manually added items 10,25,72,105,109,116 unlocked for Gloomhaven through the Global Campaign Management link at the top of the Party Sheet.
Despite this, accessing the Itemshop from a character sheet doesn't show those gloomhaven items as available.

### Game Enviroment

Frosthaven

### To Reproduce

1. Campaign Management
2. Click Fosthaven
3. Click Party Sheet
4. Click Global Campaign Management
5. Under Unlocked Items, Click Frosthaven and change dropdown to Gloomhaven
6. Write 10 into the box and click +
7. Add a character
8. Click on large character class icon to access character sheet
9. Click on Itemshop
10. Gloomhaven item 10 (Warhammer) should be shown

### Expected behavior

Unlocked Gloomhaven items should show up in the default itemshop view for a Frosthaven character

### Gloomhaven Secretariat Version

v0.77.15

### Used Browser

Firefox 118.0.1 64-bit

### OS

Windows 11

**Comment by Lurkars** [comment]
There is no need to unlock those item manually (and it won't work as you reported). You can simply go to "Settings" and enable "Add Gloomhaven Items" in the "Frosthaven Rules" Section. Then the Gloomhaven Items should be available!

**Comment by TheHankerChief** [comment]
I thought I had checked settings, but I see it now. It is disabled unless
you enable Character Items (management of items during combat rounds). I
found this relationship by reading line 754 of Settings.html. These
settings probably shouldn't be tied together. Our group will want to run
the physical cards at the table, but still track which cards their
characters own on Secreteriat.

Thanks!

**Comment by Lurkars** [comment]
Yes, you're right! Unsure why I bound this. Will be changed!

**Comment by Lurkars** [comment]
So I directly addressed this in [v0.78.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.78.0). First I just removed the check, but now I just bound this to either "Character Sheets" or "Character Items" being enabled, because if BOTH are unchecked, then there really isn't any item management available to address this setting. Hope this is now solved for you. If so, please close issue.

**Comment by TheHankerChief** [comment]
Thanks! looks like it is working nicely.
