### ISSUE TITLE
Frosthaven Building 88 UX Tweaks

### ISSUE THREAD

**Issue by rdoll** [Lurkars/gloomhavensecretariat#416]
### Is your feature request related to a problem? Please describe.

In Frosthaven, only after building 88 is unlocked does the net icon on enemies become useful information. While the physically printed assets chose to have the net icon printed on the monsters (to limit spoilers of yet-unseen enemies, I'm assuming), we can eliminate all spoilers in the app.

Also, there is no way to see the net icon while on a mobile; the icon only shows on hover.

### Describe the solution you'd like

1. When building 88 is locked, hide all traces of the net icon -- it won't even show on hover
2. When building 88 is unlocked, the net icon is always shown on applicable monsters

I don't know if this warrants a setting or not, but I lean towards not.

Also, note that AFAICT, you don't require building 88 to be constructed to "use" the net icon. You obviously don't get the results, but since it could be a viable strategy, IMHO we don't want to tie the net icon to the construction of building 88.

### Describe alternatives you've considered

Can't think of any worth mentioning

### Additional context

If you agree, I'm happy to do this one, but no worries if you or someone else wants to do it.

Thanks.

**Comment by Lurkars** [comment]
Yeah this is a good valid point. You can of course create a PR if you want to contribute on this!

**Comment by Lurkars** [comment]
Done in [v0.78.2](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.78.2). Please verify and close if solved.

**Comment by rdoll** [comment]
Validated. Two observations:

1) The implementation is that building 88 has to be built and not wrecked to see the net icon. I double checked some posts and the FAQ and IMHO this is still an open question. However, I think what's implemented is a very sensible default until there is an official ruling.

2) You chose to not show the net icon at all if building 88 was built, but is currently wrecked. Per point 1, I think it would be a tad clearer to show the net icon, but show it as "disabled" or "blocked". I tried making the net icon red when blocked, which looked ok, but I think an overlaid red-circle-with-slash icon would look better. And then I thought this was not worth it for too narrow of a use case. 

Is it worth me finishing out something for point 2 or just close this and deal with any possible change requests later. I can see it either way, so I defer to your judgment.

Thanks.

**Comment by Lurkars** [comment]
Okay, I didn't even think about any ruling, it was just a Copy&Paste behavior when considering other buildings.
