### ISSUE TITLE
Failed/Lost scenario works wrong in Frosthaven Edition

### ISSUE THREAD

**Issue by likeaRAINBOW** [Lurkars/gloomhavensecretariat#418]
### Describe the bug

When scenario ends, characters gain XP and gold loot from cards.

If Scenaro Lost you have 2 option:
- Return to Frosthaven (gain resources)
- Replay scenario (lose resources)

When click on 'restart scenario (lose resources)' characters lose XP and gold too.

### Game Enviroment

Frosthaven

### To Reproduce

Start a new game, set a scenario, add some XP and loot cards to charaters, click on Failure and restart scenario (lose resources) and check XP and gold

### Expected behavior

Gold and XP still need to add to characters if failed the scenario and restart immediately.

### Gloomhaven Secretariat Version

v0.79.0

### Used Browser

Chrome/Safari

### OS

MacOS

**Comment by Lurkars** [comment]
Thanks for noticing, will be fixed today!

**Comment by Lurkars** [comment]
Should be fixed in [v0.79.1](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.79.1). Happy if you can verify and close issue if solved.
