### ISSUE TITLE
Consistency in back/close button

### ISSUE THREAD

**Issue by Jaerin** [Lurkars/gloomhavensecretariat#419]
### Is your feature request related to a problem? Please describe.

Currently it appears that many of the screens do not have consistent visual references on how to get out of a screen back to your character sheet or out of the menu that you are in.   While clicking somewhere else does work it is not very clear when the screen takes up the majority of the screen already.

Some screens seem to have a dim red circle with an X in the upper right, but its not always on the window that is actually on top so it can be difficult to see/find.  Not to mention being a webpage it can often be even more confusing when there are the normal browser back buttons and things to potentially distract you.

### Describe the solution you'd like

Maybe the red X needs to be brighter or more obvious?

### Describe alternatives you've considered

Consistent usage across all interfaces if its not already used

**Comment by Lurkars** [comment]
Since I am bad at UX, I have no really good idea, how to make it look more obvious without being distracted. But I will make it brighter and add more contrast with shadow. And of course, I will add the icon to every dialog! Seems that I just forgot it on some places, but found a way, to automate this, so I don't have to care in future for new dialogs.

**Comment by Lurkars** [comment]
Please checkout [v0.79.2](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.79.2) and if this is enough change, please close this issue, otherwise provide some more feedback. Thanks.

**Comment by Jaerin** [comment]
Looks great!  Just tested it out and it appears to be working every place I could think of.

**Comment by Jaerin** [comment]
Looks great! Just tested it out and it appears to be working every place I could think of.
