### ISSUE TITLE
Scenario 4B has incorrect allies

### ISSUE THREAD

**Issue by dfannius** [Lurkars/gloomhavensecretariat#42]
In scenario 4A, some monster types are allies. In scenario 4B, there should be no allies, but the app acts as if the ally types from 4A are in effect. `fh/scenarios.json` appears to be correct, so perhaps there is a code bug when multiple scenarios share an `index`.

**Comment by Lurkars** [comment]
Thanks, should be fixed with [v0.30.8](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.30.8). I just split index to 4A and 4B. Index must be unique for scenario.

**Comment by dfannius** [comment]
Thanks. If scenario indices must be unique, scenario 93 will have to be split as well.
