### ISSUE TITLE
Frosthaven: Show building operations somewhere for the outpost phase.

### ISSUE THREAD

**Issue by Kafei56** [Lurkars/gloomhavensecretariat#420]
### Is your feature request related to a problem? Please describe.

No.

### Describe the solution you'd like

This amazing app is almost feature complete for my use case. The building functionality is almost there! It would be really nice to have the building operations listed next to them so we can reference this app during that phase instead of using a different method.

### Describe alternatives you've considered

Currently I'm using (https://gloomhaven-storyline.com/tracker/#/buildings) for this but it would be nice too have it all in one place in my preferred app of Gloomhaven Secretariat.

Thank you for considering!

**Comment by mentonin** [comment]
Should probably be separated into two issues

**Comment by Kafei56** [comment]
> Should probably be separated into two issues

Done, thank you.

**Comment by Lurkars** [comment]
So you just mean the effects triggered and available, right? (The stuff next to 🌞 and 🌘). Definitely on agenda, since I am still planning how to implement some of those to work (#163), I may prioritize now to just show them first.

**Comment by Kafei56** [comment]
Correct! Oh I see, that's awesome. I can be patient then =] Thank you!

**Comment by Lurkars** [comment]
Sorry, that it took so long. In [v0.89.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.89.0) I just added two more columns which just show the corresponding effects/interactions as tooltips when you hover/tap on them. Hope this is enough for you in the first step here:
![buildings](https://github.com/Lurkars/gloomhavensecretariat/assets/2760570/56ae514d-579d-4dea-ab98-eb3853fee098)

**Comment by Kafei56** [comment]
Thank you!

**Comment by Lurkars** [comment]
If you are satisfied with the result you can close the issue, otherwise happy about feedback. Thank you.

**Comment by Kafei56** [comment]
It would be nice to have the information for each building visible without hovering over each one individually, but I understand that that is probably a more intensive process than the quick way you've done it. Maybe a toggle to display the full text for those who want it this way? Since the information is at the bottom of the party sheet it would be fine for it to be long vertically.

**Comment by Lurkars** [comment]
Yes, I'll add a toggle to the header.

**Comment by Lurkars** [comment]
Checkout  [v0.89.4](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.89.4). You should see some eye icons in header to toggle visibility on and off.

**Comment by Kafei56** [comment]
Incredible, thank you!
