### ISSUE TITLE
Scenario 94: can't draw monster cards

### ISSUE THREAD

**Issue by oni-23** [Lurkars/gloomhavensecretariat#425]
### Describe the bug

We choose scenario 94 and set our initiative. With the press of the button "draw" nothing happend. After fruitless troubleshooting we chose a different scenario where it worked.

### Game Enviroment

- Scenario 94
- Characters: Prism lvl6, Snowdancer lvl5 and Shackles lvl7 (absent)

### To Reproduce

1. set scenario 94
2. set characters initiative
3. click "draw" to get monster cards

### Expected behavior

monster cards get revealed

### Gloomhaven Secretariat Version

v0.79.5

### Used Browser

Chrome Version 118.0.5993.89 (Official Build) (64-bit)

### OS

Windows 11

### Additional

![Gloomhaven Secretariat Scenario 94 Screenshot 2023-10-26 180200](https://github.com/Lurkars/gloomhavensecretariat/assets/93731791/f32c8b4e-49a3-445b-ba11-a38b7f2bd5b7)

**Comment by oni-23** [comment]
Last Gamebackup:
[ghs-autobackup-2023-10-26T15_31_20.114Z.json](https://github.com/Lurkars/gloomhavensecretariat/files/13179864/ghs-autobackup-2023-10-26T15_31_20.114Z.json)

**Comment by Lurkars** [comment]
Thanks for the report. Issue is very simple: the Flaming Bladespinner Objective does not have initiative set, so this show multiple bugs:
- missing initiative data for scenario objective
- no warning for missing objective initiative

So I'll will fix, in the meantime, you can just set the initiative of the Bladespinner Objective and it should work.

**Comment by Lurkars** [comment]
So should be fixed in [v0.79.6](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.79.6) by setting Initiative to `1`. Please verify and close issue if solved.

**Comment by oni-23** [comment]
Solved.
✅ Without set initiative, I get a popup with the info of missing initiative. 
✅ Set initiative of the Bladespinner did draw the cards.
