### ISSUE TITLE
Item sell prices are wrong for items with only required items to craft

### ISSUE THREAD

**Issue by kimmathiassen** [Lurkars/gloomhavensecretariat#427]
### Edition

FH

### Type of data

Character Stat/Sheet

### Describe the data affected

Cured Leather Armor (017) 

### Describe the error

The sell price for Cured Leather Armor is wrong, should be 8 gold is 0 gold.
![image](https://github.com/Lurkars/gloomhavensecretariat/assets/2360557/5331a7e7-1abb-4ffa-acd7-eb59eea38973)

The Item:
![image](https://github.com/Lurkars/gloomhavensecretariat/assets/2360557/cc91f866-a72b-44fa-a11b-2fe03872c73b)

Component items:
![image](https://github.com/Lurkars/gloomhavensecretariat/assets/2360557/52914a34-770e-4b70-b82c-d9015c58de74)
![image](https://github.com/Lurkars/gloomhavensecretariat/assets/2360557/99fadcb8-8529-4d92-8fa2-81a05ea6f02b)

**Comment by Lurkars** [comment]
Selling for 0 is obviously wrong, but 8 is also wrong. Should be 4 (2 gold for every resource or item used, you don't cont the resources of the required item, see P.67)! I'll check what's going wrong there and fix.

**Comment by kimmathiassen** [comment]
I can verify that the price is right
![image](https://github.com/Lurkars/gloomhavensecretariat/assets/2360557/69699931-3e34-46d6-b451-9e0275b8bc1c)
Thanks alot.
