### ISSUE TITLE
Error: Uncaught (in promise): TypeError: ut.collectiveResources.forEach is not a function

### ISSUE THREAD

**Issue by kimmathiassen** [Lurkars/gloomhavensecretariat#429]
### Describe the bug

![image](https://github.com/Lurkars/gloomhavensecretariat/assets/2360557/53c6f9bc-ac6d-405f-ba7a-335e6fbf1eac)
When pressing finish, the following error is thrown:

main.482ce573e36f81fa.js:54 ERROR Error: Uncaught (in promise): TypeError: ut.collectiveResources.forEach is not a function
TypeError: ut.collectiveResources.forEach is not a function
    at Ut.finishScenario (main.482ce573e36f81fa.js:1:57856)
    at main.482ce573e36f81fa.js:1:60362
    at Array.forEach (<anonymous>)
    at Ut.finishScenario (main.482ce573e36f81fa.js:1:60223)
    at main.482ce573e36f81fa.js:39:820287
    at Generator.next (<anonymous>)
    at t (main.482ce573e36f81fa.js:54:123680)
    at X (main.482ce573e36f81fa.js:54:123899)
    at main.482ce573e36f81fa.js:54:123968
    at new c (polyfills.bed2a72d06ede870.js:7:18262)
    at Y (polyfills.bed2a72d06ede870.js:7:15874)
    at polyfills.bed2a72d06ede870.js:7:14964
    at polyfills.bed2a72d06ede870.js:7:15070
    at t (main.482ce573e36f81fa.js:54:123718)
    at X (main.482ce573e36f81fa.js:54:123899)
    at main.482ce573e36f81fa.js:54:123968
    at new c (polyfills.bed2a72d06ede870.js:7:18262)
    at main.482ce573e36f81fa.js:54:123835
    at a.finish (main.482ce573e36f81fa.js:39:820650)
    at main.482ce573e36f81fa.js:39:801089

### Game Enviroment

Scenario 014
[ghs-game_The A team.json](https://github.com/Lurkars/gloomhavensecretariat/files/13236927/ghs-game_The.A.team.json)

### To Reproduce

Load attached gamefile
Press "#14 Jagged Shoals" (In bottom mid screen)
Press Success
Press finish 

### Expected behavior

Scenario is marked as finished as normal.

### Gloomhaven Secretariat Version

v0.80.2

### Used Browser

Chrome Version 118.0.5993.118 (Official Build) (64-bit)

### OS

Windows 11

**Comment by Lurkars** [comment]
Thanks for adding your game state. Was really important to resolve the issue, because it is not related anyhow to scenario 14, but to section 185.4. You have this section in your calendar for the next week and finishing a scenario will trigger this section which just has invalid reward data to raise the error. So I will now create new version with a fix.

**Comment by Lurkars** [comment]
So should be fixed in [v0.80.3](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.80.3). Happy if you can test yourself and close issue if solved.

**Comment by kimmathiassen** [comment]
It works, you are awesome.
