### ISSUE TITLE
Filter buttons when viewing itemcards

### ISSUE THREAD

**Issue by kimmathiassen** [Lurkars/gloomhavensecretariat#430]
### Is your feature request related to a problem? Please describe.

No.

### Describe the solution you'd like

At some point in the game the number of available items becomes quite high and it is difficult to find items that might work well for your class. I suggest Item type buttons that can be toggled on or off when viewing itemcards. 
![image](https://github.com/Lurkars/gloomhavensecretariat/assets/2360557/5196f8b5-59da-48da-94d5-2a81742141aa)

### Describe alternatives you've considered

A dropdown menu would also work.

**Comment by Lurkars** [comment]
Implemented in [v0.80.4](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.80.4). You just select a single slot with click, when none is selected all slots are shown. If you want to select multiple slots, just double click (long press on mobile) on a slot icon to add it to current selection. Happy about feedback and please close issue if satisfied.

**Comment by kimmathiassen** [comment]
I tested the features, it it works without error. It is awesome, thanks :D
