### ISSUE TITLE
Expire conditions

### ISSUE THREAD

**Issue by TrollerCoasterGR** [Lurkars/gloomhavensecretariat#437]
### Describe the bug

During our last session the app did not auto expire conditions like muddle, disarm, stun and immobilize but it did trigger wound and regenerate as normal while the appropriate setting (Automatic expire conditions) was "On" and we are always careful with active palyers and monsters.  This was not an issue in previous editions.

### Game Enviroment

Frosthaven, scenario 16

### Expected behavior

It should automatically expire conditions.

### Gloomhaven Secretariat Version

v0.80.9

### Used Browser

Chrome 119.0.6045.106 (64-bit)

### OS

Windows 11

**Comment by Lurkars** [comment]
Damn, must be introduced with #434. Will fix asap!

**Comment by Lurkars** [comment]
Should be fixed in [v0.80.10](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.80.10). Happy if you can verify and close issue if solved.

**Comment by TrollerCoasterGR** [comment]
Just tested it, works perfectly.
