### ISSUE TITLE
Auto remove conditions.

### ISSUE THREAD

**Issue by TrollerCoasterGR** [Lurkars/gloomhavensecretariat#438]
### Is your feature request related to a problem? Please describe.

I think it would be really useful if the app could remove conditions that cancel each other.

### Describe the solution you'd like

The app could remove conditions like if a player has regenarate and/or increases his/her health manually while also has poison/wound/brittle/bane then the negative conditions would be removed automatically. Or if a player has regenerate/ward/brittle and his/her health is decreased manually then it would remove these conditions because it would mean that the playing group calculated the final amount of health increase or decrease manually and it would not delay further by removing each of these conditions one by one.

### Describe alternatives you've considered

If a figure has poison then no auto healing should occur. This should apply for monsters' scripted cards as well (even though I'm not entirely sure if this happens already.

### Additional context

Thank you for all your great and hard work you have done so far and for all the great features that I'm sure will come in due time!

**Comment by Lurkars** [comment]
This should already work. Not sure, if now bugged as side effect of #437. In general, if you should be asked on inc. HP if it is a heal action. It will then remove corresponding conditions and not inc. HP if poisoned for example. Setting is "confirm applicable conditions"

**Comment by TrollerCoasterGR** [comment]
Works. We have setting "Confirm Applicable Conditions" checked and have all the conditions below it disabled (poison, brittle , ward etc.) because we do the math manually and just want the basic auto-removal functionality.
