### ISSUE TITLE
Building buildings broken

### ISSUE THREAD

**Issue by tronic101** [Lurkars/gloomhavensecretariat#440]
### Describe the bug

All resources required are available in Frosthaven supply. They are automatically selected. Clicking "Confirm" does nothing.

As a workaround we built the building with doubleclick and manually subtracted the resources.

### Game Enviroment

Frosthaven
Carpenter with building cost reduction is built.

### To Reproduce

1. Open Campaign sheet
2. Add enough material resources to build 
3. Click on "Build" for the building
4. Click "Confirm"

-> Nothing happens.

### Expected behavior

Dialogue should close and building should be built.

### Gloomhaven Secretariat Version

0.81.0

### Used Browser

Firefox 119.0.1

### OS

Linux

### Additional

Selfhosted (GHS 0.80.1)

**Comment by Lurkars** [comment]
So should be fixed in [v0.81.1](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.81.1). Happy if you can verify and close issue if solved!

**Comment by TrollerCoasterGR** [comment]
Confirm, it works. We just upgaded a building and all resources were subtracked correctly from both the available town's recourses and the corresponding ones from personal supplies.
