### ISSUE TITLE
Add options to hide player HP, XP, Loot, Summons.

### ISSUE THREAD

**Issue by LeoDanielsson** [Lurkars/gloomhavensecretariat#442]
### Is your feature request related to a problem? Please describe.

We use the app only to track initiative order (including monster ability deck). For everything else we prefer to use the physical components. That includes player HP, player XP, player conditions, player summons, loot deck, monster AMD.

That means there is a lot of clutter in the UI that is not relevant for our game. It can also be confusing when HP values are shown on the screen that doesn't reflect the actual gamestate.

### Describe the solution you'd like

It would be nice to have options to hide these things in the UI. It might also allow for reducing the size of the player bars, so that more can fit on the screen.

### Describe alternatives you've considered

Just ignore the UI elements that we don't use.

**Comment by Lurkars** [comment]
This is similar to #381.

Some stuff can already be done:
-*Settings* under *Additional Gameplay* you can disable 
   - **Character Attack Modifier Deck**
   - **Loot Deck**
- compacter character boards can already be enabled in *Settings* under *Theme* with **Compact Character Boards**

In general, I suggest to take deeper look at settings, because there is already a ton. What I see missing and will add for you is:
- Monster AM Deck
- Character elements like HP, XP, Loot, Summon Button

For conditions, I would just assume: don't add them to a character, then they are not shown ;-)

**Comment by Lurkars** [comment]
So I added options in [v0.82.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.82.0) to
- hide HP, Loot and XP on character Board (*Settings* -> *Theme* -> **Hide Character ...**)
- disable (so also hide) Monster AM Deck (*Settings* -> *Additional Gameplay* -> **Monster Attack Modifier Deck**)
- disable (so also hide button on character board) Summons (*Settings* -> *Additional Gameplay* -> **Character Summons**)

Happy if you can provide feedback and close issue if solved!

**Comment by LeoDanielsson** [comment]
Thank you! It works great and is exactly what I wanted.

The only piece of feedback I have is that the options for selecting what is shown on the characters are pretty spread out across different sections. Some are under "Character", some under "Additional gameplay" and the new ones are in an unlabeled section at the bottom. I had to scroll around a bit to find them.

On a more general note, it's a bit inconsistent whether settings are worded as "enable X" or "disable/hide X". It would be simpler if they were all "positive". E.g. "Enable character XP" (default true), "Enable monster standees", and so on.

**Comment by LeoDanielsson** [comment]
I just noticed that checking these options looks a bit broken with the modern theme.

<img width="799" alt="bild" src="https://github.com/Lurkars/gloomhavensecretariat/assets/6597255/5ed5eae7-6d14-495a-95dd-acee0fbb9616">

**Comment by Lurkars** [comment]
Thanks, will fix the modern theme. And you're totally right with the other points. I will definitely change that "disable.." settings to the opposite. Was already mentioned somewhere other. For the ordering, this is also correct, but for now I am lacking a bit of good UX ideas, how to improve the settings.

Maybe, I need to make multiple menus, or split the sides to decide between visual and gameplay affecting settings. Anyways, the disable stuff will come soon. The re-ordering still needs some thinking. Happy about more input on this too of course.

**Comment by Lurkars** [comment]
in  [v0.83.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.83.0):

- fixed issue with modern theme
- switched all *disableX* settings to *X*

**Comment by Lurkars** [comment]
For the spread out settings, I created a separate issue #447 because I also need more input. So if the other stuff is solved for you here, please close the issue.
