### ISSUE TITLE
Creating character after retirement

### ISSUE THREAD

**Issue by tttopuz** [Lurkars/gloomhavensecretariat#444]
### Describe the bug

The starting level of a new character is calculated wrongly. In my case, I started the Fist character after retiring Boneshaper. My prosperity was at level 2, with 8 crosses, not at level 3. The starting character should be at 1/2 * prosperity level (rounded up), in my case level 1. The starting character was set on level 2.

### Game Enviroment

Frosthaven

### To Reproduce

The starting level of a new character is calculated wrongly. In my case, I started the Fist character after retiring Boneshaper. My prosperity was at level 2, with 8 crosses, not at level 3. The starting character should be at 1/2 * prosperity level (rounded up), in my case level 1. The starting character was set on level 2.

### Expected behavior

The starting level of a new character is calculated wrongly. In my case, I started the Fist character after retiring Boneshaper. My prosperity was at level 2, with 8 crosses, not at level 3. The starting character should be at 1/2 * prosperity level (rounded up), in my case level 1. The starting character was set on level 2.

### Gloomhaven Secretariat Version

0.8.2

### Used Browser

-

### OS

Windows

**Comment by Lurkars** [comment]
Thanks, I think I didn't adapt Frosthaven Rules because on Gloomhaven (and other editions) it's just prosperity, not prosperity/2. Will check and fix!

**Comment by tttopuz** [comment]
Verified. Thank you!
