### ISSUE TITLE
Fist always Regenerate

### ISSUE THREAD

**Issue by tttopuz** [Lurkars/gloomhavensecretariat#445]
### Is your feature request related to a problem? Please describe.

One of the key elements of the Fist character (after playing the One with the Mountain card), is that he always has regenerate. To state more clearly: Whenever he doesn't has regenerate, he should get Regenerate.

It would avoid a lot of clicking if this could be automatically handled .

### Describe the solution you'd like

-

### Describe alternatives you've considered

-

**Comment by Lurkars** [comment]
Please check out the "permanent" symbol (<img width="20px" src="https://github.com/Lurkars/gloomhavensecretariat/raw/main/src/assets/images/condition/permanent.svg">)  in the character menu. With this, you can set the condition to permanent and achieve exactly what you asked for. Please close the issue if this is solved for you.
