### ISSUE TITLE
Disable draw random item blueprint

### ISSUE THREAD

**Issue by tttopuz** [Lurkars/gloomhavensecretariat#446]
### Is your feature request related to a problem? Please describe.

We like to draw random items and random items blueprints manually. It would be nice to disable to automatically drawing of these items, so these are not spoiled. 

### Describe the solution you'd like

Option in the settings to disable draw random items blueprints

### Describe alternatives you've considered

Removing the automatically drawn item in the party sheet and adding the manually drawn item. This suffices but spoils the other item.

**Comment by Lurkars** [comment]
You mean on drawing a loot card? Because there is already setting **Draw Random Item on Loot** in *Settings* (*Frosthaven Rules* section).

**Comment by tttopuz** [comment]
This happens on drawing a treasure or scenario reward. For example treasure chest 44 in scenario 7.

Now that I'm thinking of it, the same occurs when rewarding a random side scenario.

**Comment by Lurkars** [comment]
Ah you're right. I will add setting for this too. Thanks.

**Comment by Lurkars** [comment]
Added settings to disable separately for treasures and scenario rewards in [v0.83.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.83.0). Please close issue if solved.

**Comment by tttopuz** [comment]
Verified. Thank you.
