### ISSUE TITLE
Automatically add/remove time token at Blinkblade

### ISSUE THREAD

**Issue by keinkurt** [Lurkars/gloomhavensecretariat#451]
### Is your feature request related to a problem? Please describe.

It's possible to implement the change of amount of Blinkeblades time token based on his declaration of Fast or Slow?

### Describe the solution you'd like

Change the amount of time tokens based on the decision of Fast or Slow move at Blinkblade as follow:
- At the start of scenario BB has 1 time token
- If BB declare Fast remove 1 time token (and maybe refuse to declare Fast, if BB has no time token)
- If BB declare Slow add 1 time token, but not add 1 time token if BB has already 2 time tokens

Hopefully I don't miss any rule...

### Describe alternatives you've considered

None

**Comment by Lurkars** [comment]
Yes, this was asked before. I will add a toggle to the character menu to enable/disable this behavior.

**Comment by Lurkars** [comment]
Should now be added in [v0.83.4](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.83.4). You need to activate in the character menu.

**Comment by keinkurt** [comment]
Hey Lurkars, thanks for your work so far, but it's not working corretly. In your implementation, the amount of time tokens only changes if you click on the fast/slow icon. But it should change for every round. Maybe the efect should trigger every round after draw. But I don't know exactly what to do, if the Blinkblade declaring fast and has no time tokens...

**Comment by keinkurt** [comment]
Yes, this is nearly I want to have see. I have some improvement point...
> 
>     * time tokens are only added/subtracted after click on _Draw_, depending on slow/fast
> 
>     * when out of tokens and fast is set, on _Draw_ automatically declare slow (and add token)
Maybe it's better to not allow to set to fast, if there is no time token left OR if it will automatically change after drawing, then it will be good to see a warning to confirm these change. (But I would prefer the first solution)
> 
>     * not possible to toggle state during round (so need to be declared "correctly" before round starts, e.g. before _Draw_)
> 
>     * cap max. tokens to five
Yes the maximum total amount of time tokens are 5, but you can only collect up to 2 time tokens from declaring fast. So, in your implementation you have only to check against the 2 tokens cap. If I declare slow and I have already 2 tokens, then I will not earn 1 additional token. The 5 token cap is only for collecting tokens from abilities.
> 
> 
> Hope that make the mechanic works as you wish.

I hope it will not to complicated to implement this!

**Comment by Lurkars** [comment]
> Yes, this is nearly I want to have see. I have some improvement point...
> >     * when out of tokens and fast is set, on _Draw_ automatically declare slow (and add token)
> Maybe it's better to not allow to set to fast, if there is no time token left OR if it will automatically change after drawing, then it will be good to see a warning to confirm these change. (But I would prefer the first solution)

Okay, maybe we need to define, that you're automatically go slow after end of round. By now it doesn't change and so if you're fast (from before) and don't change, then start round, it automatically switches as described (without warning). But if you're automatically slow and then cannot define fast because of no tokens, it should be more clear, right?

> >     * cap max. tokens to five
> Yes the maximum total amount of time tokens are 5, but you can only collect up to 2 time tokens from declaring fast. So, in your implementation you have only to check against the 2 tokens cap. If I declare slow and I have already 2 tokens, then I will not earn 1 additional token. The 5 token cap is only for collecting tokens from abilities.

Yes, but you need to add the tokens in GHS anyways (manually) and by now you can add more then 5, so I'll cap that.

**Comment by keinkurt** [comment]
> > Yes, this is nearly I want to have see. I have some improvement point...
> > > ```
> > > * when out of tokens and fast is set, on _Draw_ automatically declare slow (and add token)
> > > ```
> > 
> > 
> > Maybe it's better to not allow to set to fast, if there is no time token left OR if it will automatically change after drawing, then it will be good to see a warning to confirm these change. (But I would prefer the first solution)
> 
> Okay, maybe we need to define, that you're automatically go slow after end of round. By now it doesn't change and so if you're fast (from before) and don't change, then start round, it automatically switches as described (without warning). But if you're automatically slow and then cannot define fast because of no tokens, it should be more clear, right?
> 
Yes, that looks fine!
> > > ```
> > > * cap max. tokens to five
> > > ```
> > 
> > 
> > Yes the maximum total amount of time tokens are 5, but you can only collect up to 2 time tokens from declaring fast. So, in your implementation you have only to check against the 2 tokens cap. If I declare slow and I have already 2 tokens, then I will not earn 1 additional token. The 5 token cap is only for collecting tokens from abilities.
> 
> Yes, but you need to add the tokens in GHS anyways (manually) and by now you can add more then 5, so I'll cap that.
Yes, I'm full agree with this!

Thanks a lot for your work!

**Comment by Lurkars** [comment]
Should be now implemented in [v0.83.6](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.83.6)

**Comment by keinkurt** [comment]
I test it a little bit and it seems to work. But I have one small improvement suggestion, please let the blinkblade has one token at the beginning of the scenario, as it described on the character mat. Thanks!

**Comment by Lurkars** [comment]
Yes, will be added. It was there before, but due to the changes I forgot about this!

**Comment by Lurkars** [comment]
Thanks, should be implemented now in [v0.83.8](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.83.8).

**Comment by keinkurt** [comment]
Thank you very much! I seems to work as expected.
