### ISSUE TITLE
Adding Items from ItemShop

### ISSUE THREAD

**Issue by dhyanna** [Lurkars/gloomhavensecretariat#452]
### Describe the bug

As part of Frosthaven road event WR-16, my character gained Item 231 (Skinning Knife). After adding the item to the Unlocked Items, I entered the Itemshop via my character sheet. After searching for the item, I was unable to add this item to my character's equipment, presumably because my character did not have enough gold to purchase it. The Select Item option was grayed out and the only option was to Cancel. Upon temporarily adding enough gold to my character to purchase, I was able to Select the item and then add the item without purchasing it. 

### Game Enviroment

Frosthaven Edition

### To Reproduce

1. Go to Itemshop and see that an item cannot be selected unless there is enough to purchase
2. Add enough gold to character sheet to purchase
3. Return to itemshop and select item
4. Item can then be added to equipment without purchase

### Expected behavior

Items should be able to be selected and added to the character sheet without having enough gold to purchase

### Gloomhaven Secretariat Version

0.83.2

### Used Browser

Firefox 119.0.1

### OS

Windows 10 Pro

**Comment by Lurkars** [comment]
Yes, I understand the issue and will address this beside the workaround. Because when I add the possibility to add an item without costs, then this should be available even when item is not purchasable.

**Comment by Lurkars** [comment]
Should be fixed in [v0.83.4](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.83.4).

**Comment by stonie73** [comment]
I just played around with the item shop a lot. I can approve that you have both option in the item shop:
- add (without paying any gold)
- buy

Issue seems to be fixed
