### ISSUE TITLE
Distribute collective resources in scenario rewards

### ISSUE THREAD

**Issue by tttopuz** [Lurkars/gloomhavensecretariat#456]
### Is your feature request related to a problem? Please describe.

After finishing a scenario including collective resources in the scenario rewards, these resources can be distributed among the players or put in the frosthaven supply. These resources are now automatically put in the frosthaven supply. Maybe there could be an option to distribute these among the players in the scenario summary screen.

![image](https://github.com/Lurkars/gloomhavensecretariat/assets/6255709/10eb845e-1d4d-42ed-a294-f6a5277b1b8a)

### Describe the solution you'd like

-

### Describe alternatives you've considered

-

**Comment by Lurkars** [comment]
Should be implemented in [v0.83.6](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.83.6).

**Comment by tttopuz** [comment]
It is possible in its current implementation to distribute more resources than rewarded if you type in a number. This could cause some issues with negative numbers if distributed more than is available in frosthaven supply.

**Comment by Lurkars** [comment]
Thanks for noticing this. Should be fixed in [v0.83.7](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.83.7). Happy if you can test again.

**Comment by tttopuz** [comment]
Fixed.
