### ISSUE TITLE
Player Attack Modifier Animation When First Clicked

### ISSUE THREAD

**Issue by BraunMichael** [Lurkars/gloomhavensecretariat#46]
Hi,

When using the character attack modifier deck, clicking on the circle modifier deck icon causes the card draw animation to play when the activity window switches. This animation makes it appear as though that is the drawn card, but this is actually the previous card. Could this be changed to a static image to make it clear the displayed visible attack modifier is the previous one drawn not the active draw?

Thank you!

**Comment by Lurkars** [comment]
Should be fixed with [v0.30.10](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.30.10). Please verify if this if what you meant and it's working for you. If so please close the issue.

**Comment by BraunMichael** [comment]
Hi, definitely an improvement! Although, I think the already flipped cards should also stay static to make it clear these were already flipped cards. Shown with current animation attached (also here in case of issues https://streamable.com/eb4mg4).

https://user-images.githubusercontent.com/64288950/207199963-ea92d3a8-443f-4513-a709-d0d2835e3cc7.mp4


Thank you!

**Comment by BraunMichael** [comment]
Perfect! Thank you so much! Truly excellent work overall on this app!
