### ISSUE TITLE
Automatically passing of time after finishing a scenario

### ISSUE THREAD

**Issue by tttopuz** [Lurkars/gloomhavensecretariat#460]
### Is your feature request related to a problem? Please describe.

After finishing a scenario, and clicking finish on the scenario summary screen, time automatically passes on the frosthaven campaign sheet. I would like to have an option to do this manually. 

Most of the time, our party stops the session after finishing a scenario and start the next session with the outpost phase.

The passing of time on the campaign sheet is the start of the outpost phase, with occassionally a section, which could have some consequences. It would be nice to have more control about when the x-mark is set and do it manually for example.

### Describe the solution you'd like

-

### Describe alternatives you've considered

-

**Comment by Lurkars** [comment]
Added **Automatic pass calendar time* * to *Settings* under FH Section that should solve this for you. Should be available in [v0.83.5](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.83.5). Happy if you can verify and close issue if solved.

**Comment by tttopuz** [comment]
Verified. Thanks!
