### ISSUE TITLE
Size text and icons on monster cards

### ISSUE THREAD

**Issue by tttopuz** [Lurkars/gloomhavensecretariat#461]
### Is your feature request related to a problem? Please describe.

The information on the monster cards is hard to read on large screens and doesn't scale with the font size settings. Especially, the icons for immunity (for example below) are hard to read. Also, the numbers for hp, attack and movement could be a bit bigger for better readibility. 

It would be nice if these could scale with the ability font size setting for example

![image](https://github.com/Lurkars/gloomhavensecretariat/assets/6255709/09ad7ed9-e996-4e0c-97cc-8e3ce21b1341)

### Describe the solution you'd like

-

### Describe alternatives you've considered

-

### Additional context

-

**Comment by keinkurt** [comment]
You can adjust it in the settings with the option "Ability fontsize": 
![image](https://github.com/Lurkars/gloomhavensecretariat/assets/6031362/2262eff8-d276-49ec-a76e-56decca22712)

**Comment by Lurkars** [comment]
In [v0.83.5](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.83.5) Stat values and immunity icons should now scale with font-size. Can lead to some artifacts, so is a bit a try-out what size is your sweat spot. And don't forgot to also check the general zoom function! Please close issue if solved.

**Comment by tttopuz** [comment]
Thank you so much for this. This is such an improvement. Still noticing that with some font size/zoom settings combinations the icons and numbers are a little bit off-grid, but I can imagine that that is a complex thing to solve.
