### ISSUE TITLE
Unable to import backup

### ISSUE THREAD

**Issue by mogul** [Lurkars/gloomhavensecretariat#464]
### Describe the bug

When I import my `ghs-data-dump.json` backup, I see a flash of our characters, and then an empty campaign. Above the "Undo" menu item is a red warning icon, and text with the message `Missing states: 5002`.

### Game Enviroment

Frosthaven, backup made 11.17.2023, happens in both Chrome and Firefox.

### To Reproduce

1. Go to `Server Connection`
2. Select `gloomhaven-secretariat.de:8443`
3. Enter game code `[ourcode]`
4. Select `Connect`
5. Go to `Data Management`
6. Select `<Import Data Dump(!)>` twice
7. Select the attached file
[ghs-data-dump-redacted.json](https://github.com/Lurkars/gloomhavensecretariat/files/13621731/ghs-data-dump-redacted.json)

### Expected behavior

Our campaign state would be restored.

### Gloomhaven Secretariat Version

v0.83.5

### Used Browser

Chrome 119.0.6045.200 and Firefox 119

### OS

Windows 11 and iOS

### Additional

Our backup file: 
[ghs-data-dump-redacted.json](https://github.com/Lurkars/gloomhavensecretariat/files/13621732/ghs-data-dump-redacted.json)

Screenshot post-import:
![Screenshot post-import](https://github.com/Lurkars/gloomhavensecretariat/assets/47762/e5546b00-8b06-4dc9-bc29-21d20ce1bf58)

**Comment by mogul** [comment]
(I edited the initial post to put up a `-redacted` version of our JSON file that removes our party name, just to avoid collisions if someone else works with this file.)

**Comment by Lurkars** [comment]
So first some clarifications:
The data dump is a full backup of all data stored including current state, undos, redos and settings. It's meant as backup due to data loss. There is now an edge case when you use server connection: if the game state on server is newer than from backup, it get's overwritten with the latest server data. The missing states is a hint, that you have `5002` state changes between your latest backup state and the server state. If you want to force an undo, you can click on the missing states message in the undo window to ignore it and the latest backup change should be loaded. Anyways, I would ask first what you really want to achieve. Why you have an old backup that doesn't seem to be in sync with server etc.

**Comment by Lurkars** [comment]
Alternatively if you're already on editing the JSON file, you can change `"serverAutoconnect"` to `false` or remove the value from `"serverPassword"` to disable the server connection to overwrite the state.

**Comment by mogul** [comment]
> Anyways, I would ask first what you really want to achieve. Why you have an old backup that doesn't seem to be in sync with server etc.

One game night we were seeing chaotic behavior from the server: updates were registered haphazardly and everyone was seeing slight variations on their own device. Everyone was frustrated and as the host responsible for using GHS in the first place, I felt like it was my fault. I thought "well, I have the automatic backup; let's try resetting the game state on the server, reload the backup, and see if that fixes things". That's how I got into this state. The 5002 changes probably refer to everything we did since the backup was made.

I'll try changing the values in the JSON. Thanks for your prompt response!

**Comment by mogul** [comment]
> Alternatively if you're already on editing the JSON file, you can change `"serverAutoconnect"` to `false` or remove the value from `"serverPassword"` to disable the server connection to overwrite the state.

That worked, I think... I am able to load the backup file in a disconnected state:
![image](https://github.com/Lurkars/gloomhavensecretariat/assets/47762/6d18b527-1ad3-4fa0-b99b-9db00cb94a3e)

However, it's not clear to me what we should do then... If I click `Connect` then I am in the same situation; the state is overwritten by the server. Should I just select a different game code for persisting our campaign on the server?

**Comment by mogul** [comment]
> Should I just select a different game code for persisting our campaign on the server?

I tried that and it worked... So I guess we're good to go!
