### ISSUE TITLE
Scenario 57: Escort should be present only for 2 players

### ISSUE THREAD

**Issue by sahilthapar** [Lurkars/gloomhavensecretariat#465]
### Edition

FH (Frosthaven)

### Type of data

Scenario/Section

### Describe the data affected

Scenario 57 - Escort

### Describe the error

The escort / ally should only be added for a 2 player game.

**Comment by Lurkars** [comment]
Thanks, should be fixed in [v0.83.6](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.83.6).
