### ISSUE TITLE
Element icon borders not showing until second click

### ISSUE THREAD

**Issue by LeoDanielsson** [Lurkars/gloomhavensecretariat#467]
### Describe the bug

When activating an element, it does not show the white border around it, making it difficult to see if it's active or not. Especially the "Dark" element which has very poor contrast against the brown background.

When clicking an active element again, a white border gets added which improves visibility a lot. I assume this border is supposed to always be shown for strong/waning elements.

Hover:
<img width="352" alt="bild" src="https://github.com/Lurkars/gloomhavensecretariat/assets/6597255/ac3177c1-002e-4eb4-b59a-c9e14afbaa2c">

After clicking once:
<img width="363" alt="bild" src="https://github.com/Lurkars/gloomhavensecretariat/assets/6597255/84fa7246-e712-4d23-a590-b71d49a8011c">

After clicking a second time:
<img width="345" alt="bild" src="https://github.com/Lurkars/gloomhavensecretariat/assets/6597255/a2bf433d-1c19-4734-8d24-196a28dbd237">

The third click sets it to waning (or consumed if in an active round)
<img width="338" alt="bild" src="https://github.com/Lurkars/gloomhavensecretariat/assets/6597255/d711edaa-71e8-4573-96b7-f3813c75423c">

### Game Enviroment

Frosthaven Theme

### To Reproduce

1. Click on an inert element once. It fills but does not show a white border.
2. Click it again. It shows the white border.

### Expected behavior

The first click should set it to strong and show the white border.

The second click should set it to waning/inert.

### Gloomhaven Secretariat Version

0.83.6.

### Used Browser

Firefox 120.0.1 (64-bit)

### OS

MacOS 13.4 (Apple Silicon)

**Comment by Lurkars** [comment]
This is actually on purpose. When you activate an element during your turn, it is not strong. It becomes strong after you end turn. This is to make clear, that you cannot use the element. I may add a white or maybe gray border to try to make it look more obvious.

**Comment by LeoDanielsson** [comment]
Ah, It's just a case of me misunderstanding the UI then. Closing.

**Comment by Lurkars** [comment]
Thanks, I still added now a bit darker border in [v0.83.7](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.83.7).
