### ISSUE TITLE
Incorrect Scenario Reward 

### ISSUE THREAD

**Issue by itemforty** [Lurkars/gloomhavensecretariat#468]
### Edition

FH

### Type of data

Scenario/Section

### Describe the data affected

Scenario Reward for 93B is incorrect

### Describe the error

`Scenario 93` is split between `93A` and `93B` depending on a decision you make at the beginning.

We chose B and completed it. The reward for `93B` is supposed to be `"Roasted Fowl" blueprint (item 079)` but GHS provides `"Small Rat" (item 235)`, the reward for `93A` instead.

**Comment by Lurkars** [comment]
Thanks, should be fixed in [v0.83.7](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.83.7). Happy if you can also verify and close issue if solved.

**Comment by itemforty** [comment]
Confirmed fixed. Thank you!
