### ISSUE TITLE
Setting: Confirm applicable condition double poison

### ISSUE THREAD

**Issue by kimmathiassen** [Lurkars/gloomhavensecretariat#469]
### Describe the bug

In the settings menu: Confirm applicable condition, the poison icon is there twice.
![image](https://github.com/Lurkars/gloomhavensecretariat/assets/2360557/f26610aa-3218-41aa-b109-a52c5b244bb7)
The second icon marked with purple does not seem to affect the poison condition.

### Game Enviroment

Not applicable

### To Reproduce

On a computer in chrome open https://ghs.champonthis.de/ in incognito mode.
Go to settings.

### Expected behavior

I expect each condition only to appear once.

### Gloomhaven Secretariat Version

v0.83.6

### Used Browser

Chrome Version 118.0.5993.118 (Official Build) (64-bit)

### OS

Windows 11

**Comment by Lurkars** [comment]
Actually these are two different conditions: POISON and POISON_X. Poison X is a condition especially for Crimson Scales/Trail of Ashes.

![Screenshot from 2023-12-13 10-09-48](https://github.com/Lurkars/gloomhavensecretariat/assets/2760570/0823ed58-ae54-4e45-bfad-da4ded1519fd)

In [v0.83.7](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.83.7) I changed now, that only activated conditions are listed there to avoid confusion (and also fixed description and iconography for those X conditions.

**Comment by kimmathiassen** [comment]
Thanks for the explanation and the fix.
