### ISSUE TITLE
Turn timer is now synced between clients

### ISSUE THREAD

**Issue by patrickdevarney** [Lurkars/gloomhavensecretariat#47]
Two clients join the public server. Their turn timers are incrementing locally but not synced on joining and not synced when phases change.
1. Pressing "Draw" or "Next Round" on Client1 resets Client1's turn timer to 0 but fails to reset Client2's turn timer to 0.
2. Pressing "Draw" "Next Round" on Client2 resets Client2's turn timer to 0 but fails to reset Client1's turn timer to 0.

Thank you for your work! This is amazing

**Comment by Lurkars** [comment]
Thanks, should be fixed in [v0.31.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.31.0).

**Comment by patrickdevarney** [comment]
When phases change, time resetting to 0 is now synced correctly.

Bug: When joining, the joining client's time will always be set to 0.

**Comment by Lurkars** [comment]
Okey, I will recheck.

**Comment by Lurkars** [comment]
I changed server and client now, so that new client always request latest update from an already connected client to get the current state and time. So please verify with [v0.35.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.35.0)

**Comment by Lurkars** [comment]
Since I got no feedback and no other complains, I will close this issue. Please reopen if issue isn't solved for you.
