### ISSUE TITLE
Boss cards show negative movement (boss spoiler)

### ISSUE THREAD

**Issue by kimmathiassen** [Lurkars/gloomhavensecretariat#470]
### Describe the bug

![image](https://github.com/Lurkars/gloomhavensecretariat/assets/2360557/0b94a9c7-90a6-4d21-8051-cfe64c3c78df)
I don't know if it is really a bug, but wanted it to mention it anyways.
The Lord of Chaos cannot move, but some of the boss ability cards have movement on them. Since the boss has no movement value, the movement value on the cards just show "minus movement icon". 

### Game Enviroment

Scenario 34 boss card number four.

### To Reproduce

Start scenario 34, edit boss deck.

### Expected behavior

I guess it should be "0 movement icon" or not show the movement line at all.

### Gloomhaven Secretariat Version

v0.83.6

### Used Browser

Chrome Version 118.0.5993.118 (Official Build) (64-bit)

### OS

Windows 11

**Comment by Lurkars** [comment]
Thanks, should be fixed in [v0.83.7](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.83.7). Happy if you can verify and close if solved.
