### ISSUE TITLE
Morale increase

### ISSUE THREAD

**Issue by TrollerCoasterGR** [Lurkars/gloomhavensecretariat#471]
### Describe the bug

Our morale was raised more than it should have after the completion of a certain scenario. (4 players)

### Game Enviroment

Frosthaven, scenario 120

### Expected behavior

The morale was at 17 before the scenario and was raised to 20 instead of 18 after the scenario.

### Gloomhaven Secretariat Version

0.83.4

### Used Browser

Έκδοση 120.0.6099.71 (64-bit)

### OS

Windows 11

**Comment by Lurkars** [comment]
Can you check your calendar? Maybe you had a section in the next week for gaining 2 morale or so? If not, please provide a data dump. In general, I cannot reproduce the issue by now.

**Comment by TrollerCoasterGR** [comment]
Indeed, 1 of the 2 sections that are marked in the calendar grants 2 morale. Are all of the sections marked in the calendar applied automatically?

**Comment by Lurkars** [comment]
Yes all those section rewards are applied automatically when a week is checked. This can be disabled indirectly via #460: "Automatic pass calendar time"
