### ISSUE TITLE
GHS resets and shuffles loot deck if user opens the "Change Loot Deck" screen regardless if any changes were made

### ISSUE THREAD

**Issue by itemforty** [Lurkars/gloomhavensecretariat#475]
### Describe the bug

Having a hard time summarizing this accurately, but the behavior is unexpected. 

After a player has looted something and the loot deck is lower than its max, if you open the area that lets you make changes to the Loot Deck then it resets the deck entirely and shuffles all the cards:
![image](https://github.com/Lurkars/gloomhavensecretariat/assets/175024/33f33eb4-590d-44ad-8ef8-6a11c9577d94)

This will happen regardless if you make any edits, reveal any cards, or do anything to the deck at all. It will happen during a round (if you click the gear icon) OR in between rounds if you click the deck itself.

If you immediately undo that action, which GHS calls "Change Loot Deck," then GHS will go through the animations to re-draw all the cards previously pulled. 

Any edits you make to the deck at this point won't work, as the deck will shuffle and reset again no matter what you do.

### Game Enviroment

Playing in Frosthaven, tried this on multiple scenarios (72, 18, 111), tested on Chrome mobile and Chrome desktop. Using own server, but it's up to date.

### To Reproduce

1. Start a scenario with any number of players and a loot deck with `X` number of cards
2. Give players initiatives, start a round by clicking "Draw," and have a player draw `Y` loot cards. The Loot Deck should now be `X - Y` loot cards. 
3. Click on the edit gear icon near the Loot Deck to open the area that lets you reveal, shuffle, or edit, and then **close it out immediately** without making any changes. Loot Deck will now be back to `X` cards. 

OR

3. End the round and before starting the next one, click on the Loot Deck to open the area that lets you reveal, shuffle, or edit, and then **close it out immediately** without making any changes. Loot Deck will now be back to `X` cards. 

### Expected behavior

Opening and closing the Loot Deck before clicking edit, reveal, or making any changes should not change the number of loot cards, reset them, or shuffle them

### Gloomhaven Secretariat Version

0.83.8

### Used Browser

Chrome desktop AND mobile

### OS

Win 11 AND Android

**Comment by itemforty** [comment]
I don't know if it matters, but we also have loot card #1419 in the deck.

**Comment by Lurkars** [comment]
Ouch, sounds like a real issue. Provided a fix in [v0.83.9](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.83.9). As usual, happy if you can verify.

**Comment by itemforty** [comment]
Testing ok! Thanks for the quick turnaround!
