### ISSUE TITLE
Monster stat default stats values are hidden if a monster standee is present

### ISSUE THREAD

**Issue by Kkspike** [Lurkars/gloomhavensecretariat#476]
### Describe the bug

The persistent bonuses of monsters are hidden if a standee is present on the board. They are shown if the monster if greyed (to show inactive). 
![MonsterAbsent](https://github.com/Lurkars/gloomhavensecretariat/assets/35116060/3d2cc8d6-8250-43f9-bc88-3902bd345670)
![MonsterPresent](https://github.com/Lurkars/gloomhavensecretariat/assets/35116060/749daa20-0f45-45a7-9ddd-56e54a98230d)

I don't think it was like that before (our last session was a couple of weeks ago and there were a couple of updates since.

### Game Enviroment

GHS version : v0.83.13
Edition : Frosthaven
Scenario : Any scenario (even if no scenario is set and monsters are added without a scenario)

### To Reproduce

1. Add monster : Lurker Clawcrusher
2. Notice that the stats are showing
3. Spawn one monster (normal or elite) with any number standee
4. Notice the stats are not showing anymore

### Expected behavior

The stats used to be shown all the time, either if a standee was present or not.

### Gloomhaven Secretariat Version

v0.83.13

### Used Browser

Firefox (121.0 (64-bit)), Chrome (120.0.6099.130 (Build officiel) (64 bits)), Safari on iPadOS

### OS

Windows 10, iPad

**Comment by mhalttu** [comment]
The stats are not correctly shown even when the card is drawn - for example here it seems like the Living Bones would be doing just a single attack instead of targeting multiple characters.

![IMG_9211](https://github.com/Lurkars/gloomhavensecretariat/assets/848708/73cddc69-c2a1-45a9-8d5d-13d7cfff4539)

I would rank this bug report quite high in the severity scale.

**Comment by Lurkars** [comment]
Yes can reproduce. Will investigate and fix

**Comment by Kkspike** [comment]
> Yes can reproduce. Will investigate and fix

I really hate submitting bug reports because I always think I'm the problem (I missed some setting somewhere) and I waste everybody's time. I'm happy it was justified. Thanks !

**Comment by Lurkars** [comment]
Sorry for taking so long, really bad timing with holidays. I hopefully fixed this issue in [v0.83.14](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.83.14). Happy if you can test and close issue if solved properly. Thanks for reporting.

**Comment by Kkspike** [comment]
@Lurkars Don't be sorry, it's not like you owe anyone anything and you're more than allowed to have a holiday! On my part, on v0.83.14 seems to have fixed everything from the monster cards (looks both complete while active and inactive) to the monster attack card also (can see the right targets and calculated values).

**Comment by Kkspike** [comment]
![image](https://github.com/Lurkars/gloomhavensecretariat/assets/35116060/0ed6e3a7-ba45-4a79-be2f-4c459ce2b27c)
![image](https://github.com/Lurkars/gloomhavensecretariat/assets/35116060/d711c879-0309-4dc9-9247-5ddb2a3b2b43)

**Comment by mhalttu** [comment]
@Lurkars There is absolutely no reason to apologize! I can also confirm that the fix seems to work. Thank you for looking into it, and happy new year!
