### ISSUE TITLE
Character Shield/Retaliate

### ISSUE THREAD

**Issue by TrollerCoasterGR** [Lurkars/gloomhavensecretariat#477]
### Is your feature request related to a problem? Please describe.

It would be cool and useful if we could add Shield/Retaliate to our characters and be shown as a reminder like with the monsters.

### Describe the solution you'd like

We could add Shield/Retaliate round/scenario-long to the characters/summons via their respective screens as a reminder.

### Describe alternatives you've considered

This could be a setting to be tracked like poison or like with what happens with the monsters.

**Comment by Lurkars** [comment]
Cool idea, just have to think about it a bit what's best way to do it.

**Comment by TrollerCoasterGR** [comment]
It could also include a range setting for the Retaliate to implement certain item or card abilities (hello Drifter!!)

**Comment by obstel** [comment]
Well I guess the best way but not the easiest or smallest task would be to add the ability cards properly, then it would work the same as for the monster abilities

**Comment by Lurkars** [comment]
> Well I guess the best way but not the easiest or smallest task would be to add the ability cards properly, then it would work the same as for the monster abilities

Sadly, "not the easiest/smallest" sound to me like an understatement: implementing now a quick way to add Shield/Retaliate for a Character in Character Menu will take max. a few hours. Adding all Character ability cards properly will just take month of just inputting data manually (plus development for matching/supporting the new FH design).

**Comment by Lurkars** [comment]
I added a first implementation for this in [v0.84.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.84.0). Happy about feedback. Current state
- Enable feature in *Settings* under *Character* section **Shield and Retaliate (work in progress)**
- now in character menu, shield and retaliate are available on the right side
- multiple retaliates can be set with small arrow down (for different ranges)
- shield and retaliate values are shown next to character name

**Comment by itemforty** [comment]
This isn't my ticket but I do like the effort and the idea. UI implementation looks good, easy to spot, easy to use. My suggestion is to make Shield/Retaliate expire for all characters after "Next Round" occurs, and maybe work in the "Permanent Condition" toggle for those few characters that have non-expiring Shield/Retaliate.

**Comment by Lurkars** [comment]
> My suggestion is to make Shield/Retaliate expire for all characters after "Next Round" occurs, and maybe work in the "Permanent Condition" toggle for those few characters that have non-expiring Shield/Retaliate.

Sounds like a good idea, have to check how to implement, by now works very different technically from conditions etc.

**Comment by Lurkars** [comment]
Okay, I just added now the whole stuff a second time for persistent shield/retaliate in [v0.84.5](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.84.5). Might not be the best UX, but I think it will work out for usual cases and was now easier to implement.

**Comment by itemforty** [comment]
Works great, thanks for considering that. Visually it does balance the page a bit if that helps.

**Comment by jorge-graca-sky** [comment]
Been using the shield tracking, works well and is easy to use :)
