### ISSUE TITLE
Unable to add curses or blesses when using setting "Disable standees"

### ISSUE THREAD

**Issue by patrickdevarney** [Lurkars/gloomhavensecretariat#48]
In GHH, we are able to add curses and blesses by clicking on the monster stats column (health, movement, attack, range).

In GHS, we were unable to find this feature unless using standees.

**Comment by Lurkars** [comment]
Thanks, I didn't know about this function, but makes sense, so added in [v0.31.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.31.0).

Besides, you can always add curses, blesses or other cards in Attack Modifier Deck Menu.

**Comment by patrickdevarney** [comment]
Thank you!

I am kicking myself for not thinking of checking the attack deck. That is a more-intuitive place for it to live.

**Comment by patrickdevarney** [comment]
FYI, an inconsistency, I can click on the attack discard pile to add bless/curse but ONLY when there are cards in the discard pile. If it is empty, the only way I can add new cards is via the new feature with the monster stats.

**Comment by Lurkars** [comment]
You can always open the menu by clicking on the number of left cards.
