### ISSUE TITLE
Resource Reward for Scenario Hangs Application

### ISSUE THREAD

**Issue by pikdonker** [Lurkars/gloomhavensecretariat#483]
### Describe the bug

We recently finished Scenario 73. We were rewarded with 3 wood. Clicking Finish in the Scenario Summary dialog crashes the application. The console shows a `TypeError: reduce of empty array with no initial value` in availableCollectiveResource. We've never used Gloomhaven Secretariat to track resources, which probably means a variable never was initialized.. 

### Game Enviroment

Scenario 73

### To Reproduce

Finish scenario 73 in a private window will reproduce this.

### Expected behavior

Finishing scenario should be possible

### Gloomhaven Secretariat Version

0.83.15

### Used Browser

Firefox 121

### OS

Win 10

**Comment by Lurkars** [comment]
I cannot reproduce, can you please provide more details.

**Comment by pikdonker** [comment]
Ah that's strange. I can reproduce this by opening Gloomhaven Secretariat in a private window, starting Scenario 73, opening all sections, choosing an ending (section 90 not sure if this matters), then clicking Finish. This causes the crash.

**Comment by Lurkars** [comment]
I have possible fix in [v0.83.16](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.83.16). Maybe check again. Are you using Characters? Any special settings etc? Everything can matter.

**Comment by pikdonker** [comment]
Yeah that fixed it, thanks!

We're not using any characters btw.
