### ISSUE TITLE
Enhancement request: toggle permanent condition(s) for Frosthaven Classes (spoilers in description)

### ISSUE THREAD

**Issue by itemforty** [Lurkars/gloomhavensecretariat#485]
### Is your feature request related to a problem? Please describe.

The Fist has a permanent action that gives them two abilities:

1. Permanent regeneration 
2. The ability to trade a certain amount of health to retrieve a discarded card at the end of the round 

The problem is that regen will automatically turn off if the player takes any damage. So, assuming no _enemy_ damage has occurred, at the end of the round a player:

1. Opens the condition area to take damage to get a card back
2. Closes the window, which automatically turns off regen 
3. Opens conditions back up to turn regeneration back on 
4. Close the window again. 
 
This also happens every time the player takes damage from enemies too, so they might have to open and close that window 4+ more times, depending.

It's not terrible to work around but it is a hassle.

### Describe the solution you'd like

Maybe a double-click or long click on mobile to keep specific conditions on until the player turns them back off again? I don't know what's easiest to add or makes the most sense UI-wise. 

### Describe alternatives you've considered

Turning off other settings that expire, apply, or confirm applicable conditions won't help the benefits of regenerate, nor will it stop regenerate from being removed after damage (if I understand your expiration rules correctly). 

### Additional context

A Shackles player has their own issue here: [the ability "Delayed Malady"](https://raw.githubusercontent.com/cmlenius/gloomhaven-card-browser/images/images/character-ability-cards/frosthaven/PC/fh-delayed-malady.jpeg) allows the player to be immune to all negative conditions, but unable to remove them, for 5 rounds. That player could easily turn off "automatic apply" and "automatic expire" for their own client, but wanted to provide context that there's at least one other class that could benefit from this enhancement.

**Comment by Lurkars** [comment]
I am a bit confused. Have you checked the "permanent" symbol (<img width="20px" src="https://github.com/Lurkars/gloomhavensecretariat/raw/main/src/assets/images/condition/permanent.svg">)  in the character menu? This is exactly what the case is for. In combination with  "immune" symbol (<img width="20px" src="https://github.com/Lurkars/gloomhavensecretariat/raw/main/src/assets/images/fh/condition/immune.svg">) you can also keep a condition without applying. This was all due to request in #355 . So please check that first or specify if I understood something wrong.

**Comment by itemforty** [comment]
Oh nope, you're totally right, that's the fix for what I'm reporting/requesting. Previously on mobile I tried condition and then the "permanent" symbol and it didn't work, so that's on me for not being curious enough. Thanks for the quick reply!
