### ISSUE TITLE
FH39 Incorrect monster data

### ISSUE THREAD

**Issue by mqstout** [Lurkars/gloomhavensecretariat#488]
### Edition

FH

### Type of data

Scenario/Section

### Describe the data affected

FH 39 Starting room

### Describe the error

Black imp data is incorrect. Per book, this should be the distribution of imps:

00n
0ne
0nn
eee
nee
nne
nnn
nnn

Scouts, Guard, and Corpses appear to be correct.

**Comment by Lurkars** [comment]
Should be fixed in [v0.84.6](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.84.6).

**Comment by mqstout** [comment]
Appears correct.
