### ISSUE TITLE
Investigate performance of Scenario screen

### ISSUE THREAD

**Issue by mqstout** [Lurkars/gloomhavensecretariat#489]
### Describe the bug

The filtering (and removal of filtering to show all) on the scenario window seems to be particularly slow. While I use a lower-performance computer with GHS, something about this particular panel is unreasonably slow, especially when compared to any other use on my device. The problem is not just the "filter scenario" text entry up top, but also Unlock Scenarios down below, and sometimes even just scrolling this panel. During-scenario play, settings, monster picker, character picker, campaign management, and data management do not seem to have this issue; just the set scenario.

Firefox's  "stop script" prompt will regularly appear while on the scenarios panel.

### Game Enviroment

I can privately provide my exported campaign state JSON if desired.

### To Reproduce

Enter "set scenario" screen to try to unlock a new scenario or use filters. Scrolling issue not always present, but often is after using filters.

### Expected behavior

Performance of the various screens, including those with filtering, to be approximately on-par.

Possibly "type to filter" should delay after key entry before performing search.

Simply scrolling should not have a performance impact.

### Gloomhaven Secretariat Version

0.84.5

### Used Browser

Firefox 121

### OS

Windows 10x64

**Comment by mqstout** [comment]
gist sent to your email.

**Comment by Lurkars** [comment]
Yes, already took a look. Can you test performance now in  [v0.84.7](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.84.7)? Initial load of menu can still take, I will take investigation further, but search etc. should now be faster. Happy about feedback!

**Comment by mqstout** [comment]
After a session with a couple scenario unlocks that weren't automated, etc, I would say it seems improved to close.
