### ISSUE TITLE
QoL Suggestion: Character Attack Modifier Deck Close On New Round

### ISSUE THREAD

**Issue by BraunMichael** [Lurkars/gloomhavensecretariat#49]
Hi,

A small quality of life suggestion, when not using the full screen attack modifier option, upon ending a round, all characters bars should switch to their "normal" appearance so the initiative selection can be opened with a single click. Currently 2 clicks are required if that character flipped an attack modifier, once to switch to the "normal" bar, then again to open the initiative window.

Thank you!

https://user-images.githubusercontent.com/64288950/207200628-9ba356a3-fc99-45b6-85c1-627c437f9d01.mp4

**Comment by Lurkars** [comment]
Thanks, should be resolved in [v0.31.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.31.0).

**Comment by BraunMichael** [comment]
Perfect! Thank you so much! Truly excellent work overall on this app!
