### ISSUE TITLE
Incorrect road event added

### ISSUE THREAD

**Issue by tronic101** [Lurkars/gloomhavensecretariat#491]
### Edition

FH

### Type of data

Scenario/Section

### Describe the data affected

Section 89.2

### Describe the error

Upgrading the Library to lvl3 (section 89.2)
GHS says to add SR-47, actually should be adding SR-49 instead.

**Comment by Lurkars** [comment]
Thanks, should be fixed in [v0.84.11](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.84.11).

**Comment by tronic101** [comment]
Looks good, thanks
