### ISSUE TITLE
Poison Prompt difficult to click

### ISSUE THREAD

**Issue by JP-Ellis** [Lurkars/gloomhavensecretariat#50]
We noticed last week in our game that the poison prompt (with the check mark/cross) is difficult to press and instead of the check mark or cross being clicked on, the underlying button gets triggered (e.g. the character headshot for characters, or the specific monster's icon).

I don't know whether this is a browser specific issue, or is a known issue. Happy to do some testing if need be.

**Comment by Lurkars** [comment]
Thanks. That definitely is a bug! Will fix it!

**Comment by Lurkars** [comment]
Should be fixed in [v0.32.1](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.32.1). Please verify.

**Comment by JP-Ellis** [comment]
I can confirm it works great!
