### ISSUE TITLE
Incorrect presentation of mix element modifier card at drawing them

### ISSUE THREAD

**Issue by keinkurt** [Lurkars/gloomhavensecretariat#500]
### Describe the bug

When I have the perk for creating mix element of a meteor character, it will be looks fine at the modifier deck, but not on the drawing card.

### Game Enviroment

Edition: Frosthaven
Scenario: Meteor Solo Scenario

### To Reproduce

1. Go to Character Sheet at Meteor and click on the perk "Add two +1 Fire or Earth element perk
2. Start a scenario
3. Draw attack modifier on Meteor. If the Mix Element perk is drawing, it is not showing correct

### Expected behavior

The attack modifier card should look exactly as it does in the attack modifier list when you draw the card in a scenario.

### Gloomhaven Secretariat Version

v0.85.0

### Used Browser

Firefox v122.0

### OS

Windows 11

### Additional

Right presentation at modifier deck:
![grafik](https://github.com/Lurkars/gloomhavensecretariat/assets/6031362/891e2cea-f17b-4a8c-8e67-9a0edaa7d3df)

Wrong representation at drawing the card:
![grafik](https://github.com/Lurkars/gloomhavensecretariat/assets/6031362/c9ff5d52-8360-4ddf-8990-70bd43382429)

**Comment by Lurkars** [comment]
Thanks, should be fixed in [v0.85.1](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.85.1).

**Comment by keinkurt** [comment]
Thank you, works like a charm!
