### ISSUE TITLE
Morale X has artifacts

### ISSUE THREAD

**Issue by jorge-graca-sky** [Lurkars/gloomhavensecretariat#502]
### Describe the bug

![image](https://github.com/Lurkars/gloomhavensecretariat/assets/117302909/6d1d8a51-8d89-4895-91ec-e00382f946ea)

### Game Enviroment

Campaign sheet

### To Reproduce

Open campaign sheet

### Expected behavior

X is pretty

### Gloomhaven Secretariat Version

latest

### Used Browser

chorme

### OS

mac

**Comment by Lurkars** [comment]
Thanks, should be fixed in [v0.85.1](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.85.1).

**Comment by jorge-graca-sky** [comment]
Fixed:
<img width="56" alt="image" src="https://github.com/Lurkars/gloomhavensecretariat/assets/117302909/aeeb6d16-9149-4277-9cd0-6372ab59eb26">

But must say it sill looks a bit odd on the positioning.

**Comment by Lurkars** [comment]
Haha okay, that was on purpose to make it look more "human". But I'll change it for you!

**Comment by Lurkars** [comment]
Checkout  [v0.86.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.86.0) if the alignment is now correct for you!

**Comment by jorge-graca-sky** [comment]
Thanks!
