### ISSUE TITLE
Rewards not calculated correctly with absent characters

### ISSUE THREAD

**Issue by gkaragia** [Lurkars/gloomhavensecretariat#504]
### Describe the bug

The loot cards that reward the players with more resources on fewer player counts, are not calculated correctly.

### Game Enviroment

Nothing specific

### Steps to reproduce:
1. Have a 4 character group
2. Mark one of the characters as absent
3. Begin a scenario and do some looting until you get a loot card that gives a bonus on smaller player counts.
4. Finish the scenario as a success

### What I expected to happen
To get the bonus loot for 3 players

### What happened instead
The loot cards are calculated for 4 players.

### Gloomhaven Secretariat Version

0.86

### Used Browser

N/A

### OS

N/A

### Additional

Too bad that we figured this out close to the end of our campaign. Seems like we were playing on hard mode :)

**Comment by Lurkars** [comment]
Sorry I cannot reproduce. Tested, the values change correctly regarding how many players I put absent. Are you sure you checked the card right? Also from code side I checked, that absent characters are not count.

![image](https://github.com/Lurkars/gloomhavensecretariat/assets/2760570/27d49a4b-8d68-4e10-9b8f-366e9e847f21)

![image](https://github.com/Lurkars/gloomhavensecretariat/assets/2760570/cace139f-af3d-46e0-bf1b-8f167593b513)

![image](https://github.com/Lurkars/gloomhavensecretariat/assets/2760570/23e6f184-0589-4624-92ba-8afbebaab58d)

![image](https://github.com/Lurkars/gloomhavensecretariat/assets/2760570/c2ffe3d3-3764-44f5-8724-3462ac2afbd9)

My tested example with the given cards and toggling 0,1 and 2 players absent to get card values for 4,3 and 2 players.

**Comment by gkaragia** [comment]
Oh sorry it seems that I got the rules wrong. What I thought was that the bonus above the card was meant to be added to the loot value. So the first card in your example would give 2 hides for 4 players and 3 hides for 2 or 3. Thank you for looking into this.
