### ISSUE TITLE
Personal Quest Display Issue

### ISSUE THREAD

**Issue by PghCalcifer** [Lurkars/gloomhavensecretariat#508]
### Describe the bug

After updating to v0.89.3, there seems to be a visual issue with the way Personal Quests are displayed. You now have to scroll left/right to see the quest and corresponding tracking information whereas the previous versions would fit everything to the width of the character sheet.

Character Sheet Width not showing full info:
![Personal Quest (character sheet width)](https://github.com/Lurkars/gloomhavensecretariat/assets/127225075/0fba3d62-d376-4c23-9152-bfea313ccf5d)

Expanded to show all info:
![Personal Quest (expanded)](https://github.com/Lurkars/gloomhavensecretariat/assets/127225075/3fa7e82b-8583-4031-899f-b6c5c597947c)

### Game Enviroment

- Frosthaven theme
- 'Compact Character Sheets' unchecked
- no current scenario

### To Reproduce

1. Click on any character to open their character sheet
2. Scroll down to Personal Quests
3. Set a personal quest (if none present)

### Expected behavior

The full personal quest and related tracking should fit within the existing character sheet width.

### Gloomhaven Secretariat Version

v0.89.3

### Used Browser

installed via Chrome

### OS

Windows 11

**Comment by Lurkars** [comment]
Yes thank. Already aware and locally fixed. New release in 1-2 hours!

**Comment by Lurkars** [comment]
Should be fixed in  [v0.89.4](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.89.4). Happy if you can verify and close issue if solved.

**Comment by TrollerCoasterGR** [comment]
Everything back to normal. I can confirm it is solved.
