### ISSUE TITLE
FH Character Perks

### ISSUE THREAD

**Issue by Viou** [Lurkars/gloomhavensecretariat#51]
Are you working on or do you need help with the new fh character perks?

**Comment by Lurkars** [comment]
I started working on it, but of course if someone wants to help entering all the data it will be faster. I am currently implementing the active stack (for Blinkblade perk for example). What's next it the combined perks for example last banner spear perk. And all the design is not ready yet.

For example data you can take a look at
https://github.com/Lurkars/gloomhavensecretariat/blob/main/data/fh/character/banner-spear.json#L100
https://github.com/Lurkars/gloomhavensecretariat/blob/main/data/fh/character/blinkblade.json#L45

If capable, may start with the looked classes, so I continue myself with starter and we wouldn't do work twice.

**Comment by Viou** [comment]
Ok, cool! I actually started on Blinkblade but then got into a rabbit hole of trying to figure out how to modify the images for wound to match the FH change. When I get back from vacation and/or have access to some character sheets I can work on some other characters.

**Comment by Lurkars** [comment]
I can send you images of the character sheets if you provide me an email. If you don't want to post your mail public, just send me one to github@gloomhaven-secretary.de.
