### ISSUE TITLE
Boneshaper Summons disconnect from server

### ISSUE THREAD

**Issue by EricE-MW** [Lurkars/gloomhavensecretariat#512]
### Describe the bug

We discovered in a long play session yesterday, that with every client i hit the summon button on bone shaper, than select a shambling skeleton, the clients disconnect from server and changes were not applied. This leads to we werent able to use the boneshaper summons for tracking in the app. I tried to reproduce it on https://ghs.champonthis.de/ but there it works.
So seems it is a bug with the server application?

### Game Enviroment

any scenario, own server host with ssl enabled, 4 clients + serve server client for "showing" the results

### To Reproduce

1. Go to 'add character -> Bone shaper.'
2. Click on '+ Icon' for summoning
3. Scroll down to 'Shambling skeleton' and klick ok
4. See error / Client disconnects from server

### Expected behavior

Summons appear for all clients / Server

### Gloomhaven Secretariat Version

0.89.4

### Used Browser

Microsoft Edge

### OS

Windows / Clients Android & iOS

**Comment by Lurkars** [comment]
Thanks, this was a [server issue](https://github.com/Lurkars/ghs-server) after I updated the FH summons in the client. This is now fixed on the public server (look that the server version is listed as `0.89.5`). But I would be happy if you could check it yourself and close the issue if it is fixed. Thanks for noticing!

**Comment by EricE-MW** [comment]
Wow thank you for this awesome fast reaction - it is fixed! Looking forward to our next session :D! Thanks for your awesome work!!! My party will spent you "some" coffees ;)
I also recognized another bug in the server / made an issue there!
