### ISSUE TITLE
Modifying monster attack deck limited to 5 -1 cards

### ISSUE THREAD

**Issue by rjmackinnon** [Lurkars/gloomhavensecretariat#52]
The Diviner can add up to 8 -1 cards to the monster attack deck, but the interface stops adding at 5. Tested on both mobile & PC, same result.

There is a workaround where you can edit the deck instead to add more than 5, but this seems counter-intuitive.

**Comment by Lurkars** [comment]
Thanks for the report. I accidentally put the same limit of 10 to the Minus 1 cards as for Curses and Blesses, with the 5 default -1, you can only add 5. I will fix this. Should be no limit.
