### ISSUE TITLE
Adjust calendar lock to one week at a time

### ISSUE THREAD

**Issue by tttopuz** [Lurkars/gloomhavensecretariat#520]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/Lurkars/gloomhavensecretariat/assets/6255709/bffbac80-109a-426a-a699-5068cbfd5c5d)

Locking the calendar is a nice feature and prevents accidently forwarding a lot of weeks. However, with the setting of not automatic passing time, it would be nice to be able to forward one week when locked. 

### Describe the solution you'd like

-

### Describe alternatives you've considered

-

### Additional context

-

**Comment by Lurkars** [comment]
To make it a bit more flexible, I just added a third state. So doubleclick (long press on mobile) on the icon will just allow to add one week or remove current week. So it not depends on any other setting.

**Comment by Lurkars** [comment]
So happy if you can check in [v0.90.2](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.90.2) if this is okay for you and if so, close the issue. Thanks.
