### ISSUE TITLE
Special rules for prism

### ISSUE THREAD

**Issue by TrollerCoasterGR** [Lurkars/gloomhavensecretariat#521]
### Is your feature request related to a problem? Please describe.

I could not find a way to mark a summon with the **Mode** Token.

### Describe the solution you'd like

I would like to have a way to mark 1 or more summons with a **Mode** token.

### Describe alternatives you've considered

Ideally, it would be perfect if the marked summons were considered inactive so they would not take their turns as normal.

**Comment by Lurkars** [comment]
Added now an action in menu of prism summons to set add mode token. If so, summon is inactive. I do not manage any other special state, so up to player to manage the mode tokens / switches correctly, but at least you can mark it in the app now. Version is [v0.90.4](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.90.4), happy if you can verify it that is working for you as expected and if so close issue.

**Comment by TrollerCoasterGR** [comment]
Yes its definitely an improvement. At least now we don't have to kill and re-summon all the time.
