### ISSUE TITLE
Items found in treasure chests should be added to the character's inventory

### ISSUE THREAD

**Issue by stonie73** [Lurkars/gloomhavensecretariat#522]
### Describe the bug

As fas as I understood the game-rules... when you are opening a treasure chest and find an item, it is added to the finder's inventory (but it can not be used/equipped immeiately, this can be only done between scenarios).

GHS currently lets you open a treasure and select which character takes the item, but the item is not added to the character's inventory.

### Game Enviroment

- tested with JOTL scenario 3, treasure 10

### To Reproduce

1. Go to JOTL scenario 3
2. open room 1
3. open treasure 10 with any character
4. open that character's sheet
5. the found item is not listed in the character's items 

### Expected behavior

The character's items should contain the treasure item. 

### Gloomhaven Secretariat Version

0.90.3

### Used Browser

Chrome

### OS

Windows 11

**Comment by Lurkars** [comment]
Thanks for noticing. Issue was, that item wasn't added when "Character Items" are disabled in setting, actually I should also check for "Character Sheet" being disabled too to not add item. Should be fixed now in [v0.90.4](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.90.4). Happy if you can verify and close issue if solved.

**Comment by stonie73** [comment]
works as expected now, thanx for the quick repsone!
