### ISSUE TITLE
Touch-scrolling in the perks list causes unwanted perk changes

### ISSUE THREAD

**Issue by schteff** [Lurkars/gloomhavensecretariat#524]
### Describe the bug

This is an annoying issue for our party. 
In the perks list on the character sheet the perks are being checked/unchecked when scrolling if the scroll happens to end on a checkbox or on the texts. 

https://github.com/Lurkars/gloomhavensecretariat/assets/2564884/9c7d6cc3-f989-4f82-8730-9cff54e13aac

I gave fixing it myself a try but Angular is outside my comfort zone. 

In the video i'm reproducing it in chrome desktop on a mac emulating an iphone.

### Game Enviroment

In the character sheets

### To Reproduce

1. Open a character sheet on a touch screen (phone)
2. Scroll in the perks list
3. Notice unwanted checks being made

### Expected behavior

When scrolling no checkboxes should be changed

### Gloomhaven Secretariat Version

0.90.6

### Used Browser

Chrome and Safari latest version, probably all browsers

### OS

Android, iOS, Windows and MacOS

**Comment by Lurkars** [comment]
I got exactly this as email feedback and will add a lock button like on the FH campaign sheet.

**Comment by schteff** [comment]
Great. Love the work you put into this 👍

**Comment by Lurkars** [comment]
So LOCK icon should be available now in [v0.90.8](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.90.8). Happy if you can give feedback if it is working and okay like this for you.

**Comment by schteff** [comment]
Thanks! Good solution, works for me, we'll give it a spin on all our phones on monday :)
