### ISSUE TITLE
Receiving "players has null item" error

### ISSUE THREAD

**Issue by iamwpj** [Lurkars/gloomhavensecretariat#530]
### Describe the bug

We play on a locally hosted up-to-date version of the application with ghs-server. In the upper left corner by the server connection status a red warning triangle shows indicating an error. 

```
{type: 'error', message: 'players has null item', serverVersion: '0.92.2'}
```

<img width="517" alt="image" src="https://github.com/Lurkars/gloomhavensecretariat/assets/3053195/6db4da3d-edfc-4146-8abc-e1ad5b6521ba">

### Game Enviroment

release: 92.2

### To Reproduce

1. Open webpage
2. Often session will wipe and start a new game
3. Select Menu > Undo (server sync) will bring back the normal session with correct stats. Sometimes importing data results in a slightly off (basically like the data is missing from latest gameplay, but accurate for two scenarios ago, but in the actual backup accurate data is present)

<img width="1558" alt="image" src="https://github.com/Lurkars/gloomhavensecretariat/assets/3053195/309cf3ee-8f6e-4334-8cfd-f4612aca36d9">

### Expected behavior

Either an indicator of the missing item/character affected or a log in the server logging.

### Gloomhaven Secretariat Version

92.2

### Used Browser

Chrome

### OS

MacOS 14.4

**Comment by Lurkars** [comment]
Could you please send me a data dump by email (just use the feedback button in the menu!). It would help me a lot to investigate the problem.

**Comment by iamwpj** [comment]
Sent!

**Comment by Lurkars** [comment]
I think I could identify and fix the issue in client while I have still no idea how you created that state, but anyways, please checkout with latest client [v0.92.4](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.92.4) if the fix is working and if so close issue. Thanks.

**Comment by iamwpj** [comment]
I deleted the client files and pulled 0.92.4 and got the same issue.

**Comment by Lurkars** [comment]
I am not able to reproduce with your send backup. Are you using multiple parties?

**Comment by iamwpj** [comment]
I looked at this this morning and found that I hadn't moved the correct client files. Your fix did the trick! Many thanks!
