### ISSUE TITLE
iOS: Monster ability cards blank in overview

### ISSUE THREAD

**Issue by m42i** [Lurkars/gloomhavensecretariat#533]
### Describe the bug

In the overview of a monster‘s ability cards, on iOS they are blank. Background is visible but no text. 

![GH monster ability cards](https://github.com/Lurkars/gloomhavensecretariat/assets/1315881/4cf4cb04-da48-482f-b3da-4309dc719d82)

### Game Enviroment

All

### To Reproduce

1. Go to '.main screen'
2. Click on '.a monster ability card '
3. Click on a card pre reveal all

### Expected behavior

See text on front and back of the cards

### Gloomhaven Secretariat Version

0.92.5

### Used Browser

Safari

### OS

iOS 17.4, iOS 15.8

**Comment by Lurkars** [comment]
Can you please provide more information or export game state and send it to me? Is this for every monster? In every scenario? Or only specific cases etc.

**Comment by m42i** [comment]
It’s in all scenarios with every monster. On all tested iOS devices (iPad/iPhone). 

[ghs-game.json](https://github.com/Lurkars/gloomhavensecretariat/files/14733624/ghs-game.json)

**Comment by Lurkars** [comment]
Okay, can reproduce on an iPad. Sad, I cannot really debug on iPad (Apple really s**** for developers without Apple Hardware). So it may take a while with try and error to fix this.

**Comment by Lurkars** [comment]
Okay, actually seemed easy. Happy if you confirm the fix in [0.93.2](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.93.2) and close the issue if solved!

**Comment by m42i** [comment]
Nice. Works on all my devices. 🙏
