### ISSUE TITLE
Remove wound/poison/brittle/bane when increasing health on a figure.

### ISSUE THREAD

**Issue by Kafei56** [Lurkars/gloomhavensecretariat#535]
### Is your feature request related to a problem? Please describe.

Relevant negative conditions aren't removed when increasing health.

### Describe the solution you'd like

When increasing health on a figure it would be nice if the relevant conditions would be removed immediately so we don't have to double click on them to manually remove. I notice this functionality already exists when the long rest heal goes off but when dragging to heal the conditions remain.

### Describe alternatives you've considered

Include an option to toggle if this feature isn't desired by some.

### Additional context

Would it be possible to include this functionality with the regenerate condition heal?

**Comment by Lurkars** [comment]
There is functionality called "Confirm applicable condition" with also a heal condition (just disable the other condition if you don't need then). Enable this and you will be asked on inc. health if this was heal and conditions are removed. At least this is only one more click. But without confirmation you will run into a the problem that if you want to inc. health without removing condition, you need to remember the conditions and add them back etc.

**Comment by Kafei56** [comment]
Ah there it is! Though it is a little cumbersome in it's current implementation for my request. As it stands it takes a few moments for the confirm/deny box to pop up and then you click, so it's faster to disable the setting and then double click the icon to remove. I still feel like there could be a setting where they auto remove when you increase health for those of us that want it! I know I'm nit picking though so no worries if you are satisfied as is. Thank you for everything!

**Comment by Lurkars** [comment]
Don't know if you get notified about links, so I created separate issue for this:  #538.

**Comment by Lurkars** [comment]
You can test in [v0.94.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.94.0)
