### ISSUE TITLE
Include shortcuts to map, party sheet, and scenario flow chart within each of those screens; and possibly shortcuts on the main screen header next to the party name.

### ISSUE THREAD

**Issue by Kafei56** [Lurkars/gloomhavensecretariat#536]
### Is your feature request related to a problem? Please describe.

When exiting the map it requires a few clicks to go back into the party sheet or scenario flow chart. Also, when perusing the scenario flow chart it would be nice to be able to quickly look between the flow chart and the map to see where the scenarios are in the world before choosing.

### Describe the solution you'd like

On the party sheet have shortcuts to the scenario flow chart next to the existing map button (or wherever). On the scenario flow chart screen have shortcuts to the map and party sheet. On the map screen have shortcuts to the scenario flow chart and party sheet.

### Describe alternatives you've considered

Maybe a keyboard shortcut instead/also?

**Comment by Lurkars** [comment]
So I added a few things in [v0.93.4](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.93.4)
- keyboard shortcuts:
    - Map (<kbd>g</kbd> for ***Global** Map*) 
    - Flow Chart (<kbd>c</kbd> for *Scenario Flow **Chart***)
- small menu on bottom left for toggling on Map/Flow Chart (on map there's also toggle for highlighting, wanted to add this anyway, so this idea from you was good reason to add this too!)

These shortcuts also work on Map/Flow Chart itself, as well as the <kbd>p</kbp> shortcut for Party Sheet.

Happy if you can test/verify and close issue if solved!

**Comment by Kafei56** [comment]
Works great, thank you! One small change that I think would be better is that the party sheet button go to the Party/Campaign Sheet and not the Global Campaign Management Sheet as I think the former is used most frequently.

**Comment by Lurkars** [comment]
Okay, I am not sure what I read before, I was so sure that you requested the global campaign sheet and just made it that way for you, but now reading your comment, I have no idea why I thought this 😅. Will change!

**Comment by Lurkars** [comment]
Should be fixed in [v0.94.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.94.0).
