### ISSUE TITLE
Setting to automatic apply conditions with confirmation dialog

### ISSUE THREAD

**Issue by Lurkars** [Lurkars/gloomhavensecretariat#538]
Added a setting to automatically apply the confirmation dialogue to certain conditions such as Heal, Brittle, Ward and Shield. Instead of asking for confirmation, the effect is applied immediately. This should be used with care, as with many conditions and a lot of automation it can quickly become very unclear what has happened!

For Brittle and Shield, this can only work if the figure is not poisoned or if apply poison is disabled, otherwise the damage will not be clear before confirming the poison.

> Ah there it is! Though it is a little cumbersome in it's current implementation for my request. As it stands it takes a few moments for the confirm/deny box to pop up and then you click, so it's faster to disable the setting and then double click the icon to remove. I still feel like there could be a setting where they auto remove when you increase health for those of us that want it!

_Originally posted by @Kafei56 in https://github.com/Lurkars/gloomhavensecretariat/issues/535#issuecomment-2019664958_

**Comment by Lurkars** [comment]
@Kafei56 happy if you can also test this in [v0.94.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.94.0) and provide feedback. As always with all this condition stuff, I really hope I didn't break any stuff...

**Comment by Kafei56** [comment]
I like how you implemented the settings and the descriptions are intuitive. Yeah I imagine what's under the hood gets pretty complex with these things!

Most looks good but I notice when I reduce health with brittle the condition isn't removed until I activate the next figures turn, and for ward the condition isn't removed automatically at all but the effects are applied.

**Comment by Lurkars** [comment]
On single client this was only a visually issue, because the condition just gets expired after animation is shown. But this lead to issue when using multiple clients, so reworked a bit and should be now fixed in [v0.94.1](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.94.1). Happy again if you can also test a bit.

**Comment by Kafei56** [comment]
Works great now, thank you for everything! Excited to test these out next session.

**Comment by Lurkars** [comment]
Fine, I'll close issue now. Re-open when we experience any issues.
