### ISSUE TITLE
TAB-Shortcut not working, if others has enter initiative 

### ISSUE THREAD

**Issue by keinkurt** [Lurkars/gloomhavensecretariat#539]
### Describe the bug

The TAB-Shortcut works great if you enter the initiatives of all players at one PC. But if some player enters their initiative on their own device an you see the ?? in the initiative field on the PC, the TAB key is not working anymore (no field is getting focus, after hitting TAB)

### Game Enviroment

Last tested version was v0.93.3. Our game setup is, one Windows PC, with the Windows native app controlling by one player (he enters his initiative on this client) and doing most scenario management there. The other players using smartphones to enter initiatives.

### To Reproduce

1. Start scenario 
2. Enter initiative on one player with a client
3. Try to use the TAB key on another PC client 

### Expected behavior

no initiative input field is selected 

### Gloomhaven Secretariat Version

v0.93.3

### Used Browser

Native client 

### OS

Windows 11

**Comment by Lurkars** [comment]
Thanks, during testing I also noticed, that you're not able to click on the ***??*** to change initiative, so also addressed this. Happy if you can test in [v0.94.2](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.94.2) if it is working now as expected for you!

**Comment by keinkurt** [comment]
Thanks, it works like a charm. Nice idea to have the possibility to change the other values.
