### ISSUE TITLE
Living Doom spawing card Call For Souls

### ISSUE THREAD

**Issue by keinkurt** [Lurkars/gloomhavensecretariat#540]
### Is your feature request related to a problem? Please describe.

It would be very nice to have the spawing functionality of the card Call For Souls from Living Dooms

### Describe the solution you'd like

If the Living Dooms draws the card Call For Souls and it's their turn, their sould be spawning X Living Spirits if I click on the card text. Maybe you have to implement more spawning logic, because here their will be spawning multiple Monster based on the current helth of the spawner. (spawn 1 Living Spirit per 5 HP of the Living Doom)

### Describe alternatives you've considered

At least it will be helpful to add Living Spirits to the possible monster list, if Living Dooms present in this part of the scenario.

**Comment by Lurkars** [comment]
This was a tough one, hope again that I didn't break any existing stuff. On the other hand identified a few general issue with interactive abilities. So happy if you can test a bit more in [v0.95.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.95.0). If this is working fine, I may identify if other monster abilities exists with such requirements.

**Comment by keinkurt** [comment]
I opened a pull request, which fixed the simple spawn cards, without count value. With this the Ooze, Abael Herder, Living Doom and Deep Terror spawn cards works fine.
