### ISSUE TITLE
Frosthaven Scenario #109

### ISSUE THREAD

**Issue by eaganlai** [Lurkars/gloomhavensecretariat#542]
### Describe the bug

The final session book apply notice was shown before the condition was fully met. We only fulfill 2 of the four conditions and the notice is shown already.

### Game Enviroment

FH 109

### To Reproduce

Unlock two of the sessions and killed two objectives.

### Expected behavior

Not notice shown.

### Gloomhaven Secretariat Version

0.95.0

### Used Browser

Firefox 

### OS

win 11

**Comment by Lurkars** [comment]
Should be fixed in [v0.95.3](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.95.3). Happy if you can verify and close issue if solved.
