### ISSUE TITLE
Fist enhancement

### ISSUE THREAD

**Issue by Jaerin** [Lurkars/gloomhavensecretariat#544]
### Is your feature request related to a problem? Please describe.

Add the ability to make the regen condition permanent.
Fist "one with the mountain" ability allows regen to be on permanently, it reapplies if it's ever lost.
Currently if you have the automatic expire conditions option set it will force it off and you have to manually keep reapplying it.

### Describe the solution you'd like

Have an option or way for Fist to permanently apply Regen

### Describe alternatives you've considered

Manaully applying the condition every time it is removed.

**Comment by Lurkars** [comment]
This has already been solved, there is a permanent symbol in the character menu, simple toggle permanent and choose condition:
![Screenshot_20240401-162035_Ecosia.png](https://github.com/Lurkars/gloomhavensecretariat/assets/2760570/9f0494e6-4293-4256-9998-ae5f894ff7bd)
