### ISSUE TITLE
Server Closed

### ISSUE THREAD

**Issue by Rolok** [Lurkars/gloomhavensecretariat#545]
### Describe the bug

We've used the software for several weeks, slowly learning how it works.  Tonight we got together and ended up getting a server Closed error.  We could not connect to the server.  Thanks to the default action of being able to backup data I have a data dump from last week but we could not resolve the issue tonight.  We ended up playing a scenario tonight and now if we're able to connect later we'll have to manually add in what we did.  

What happened?  Were/Are there issues with the server?  We tried restoring from the file, but still cannot connect.  Tried the path with changing autoconnect to false (or something like that) but still seems messed up.

Being a player yourself, I think you can imagine our combination of feelings over this.  Any advice?

### Game Enviroment

From our previous sessions we had finished up the Algox scenarios I think.  We had 114, 7, 8 and 9 available.  

Tonight's error was just when trying to get everybody connected.

### To Reproduce

1. Go to https://gloomhaven-secretariat.de/
2. Click on Connect to server.  (Connect automatically and synchronize settings are selected)
3. See "Closed" under Synchronize Settings.
4. Click outside of that dialog to see the main screen
5. See "Since you are not connected to your local server..."

### Expected behavior

1. Go to https://gloomhaven-secretariat.de/
2. Click on Connect to server.  (Connect automatically and synchronize settings are selected)
3. See "Connected" and then be able to have all the data available

### Gloomhaven Secretariat Version

0.95.6

### Used Browser

Firefox 123.0.1

### OS

Windows 11

### Additional

I have also tried Force Update on the client.  I've tried importing data from the backup.  Nothing has helped.

**Comment by Rolok** [comment]
Below is the json backup file.

[ghs-data-dump_2024-03-30T18_36_09.850Z.json](https://github.com/Lurkars/gloomhavensecretariat/files/14847726/ghs-data-dump_2024-03-30T18_36_09.850Z.json)

I can also provide the key we use on the public server if need be.  We have been playing on gloomhaven-secretariat.de not us.gloomhaven-secretariat.de

**Comment by Lurkars** [comment]
The key is in the backup file. I deleted it now because of this. The game state on the server is pretty old in comparison to your backup, so I guess there must be a problem long before. I just cannot reproduce why connection isn't working. But also the backup file shows some hint, that it was generated with an old client. Did you just played a long time with an outdated client? 

Anyways. On a clean client, it should be possible to import your backup. Then 'allow local changes', edit the server connection and use a new game code. Then this state should be in sync with the server.

**Comment by TrollerCoasterGR** [comment]
We have exactly the same problem for the last couple of hours.

**Comment by TrollerCoasterGR** [comment]
All good now!

**Comment by Rolok** [comment]
Can confirm that it has been resolved.  Thank you!!!
