### ISSUE TITLE
Item 204 Typo

### ISSUE THREAD

**Issue by TrollerCoasterGR** [Lurkars/gloomhavensecretariat#546]
### Edition

Frosthaven

### Type of data

Other

### Describe the data affected

Item 204

### Describe the error

Item 204 normally adds (-1) x3 in a player's AMD not x1 as the app states.

**Comment by Lurkars** [comment]
Should be fixed in [v0.96.7](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.95.7)

**Comment by TrollerCoasterGR** [comment]
One last thing that I forgot to mention is that it should also write 'Damage "equal" to their Shield value'.  Sorry about that.

**Comment by Lurkars** [comment]
Thanks, should now be fixed in [v0.95.8](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.95.8)
