### ISSUE TITLE
JOTL: Perks tracking

### ISSUE THREAD

**Issue by davebang** [Lurkars/gloomhavensecretariat#55]
In JOTL, you get the first perk after Scenario 3 (i think, or maybe it's 4) in the learn to play guide. But this isn't currently represented in the app - all the perks are blocked out until you complete another character goal before you can add any perks (such as battle goals or level up).

**Comment by Lurkars** [comment]
Hello, this is addressed in the F.A.Q.
https://help.gloomhaven-secretary.de/#faq

> If some rewards or house rules requires to add extra Perks to the Character Sheet, use the Retirements counter on the bottom of the sheet to gain additional perks without getting warning message.

**Comment by davebang** [comment]
Ah ok, perfect - thanks @Lurkars and thank you for the application, it's fantastic!
