### ISSUE TITLE
name-container div shows unneeded horizontal scroll bar in Firefox

### ISSUE THREAD

**Issue by pikdonker** [Lurkars/gloomhavensecretariat#557]
### Describe the bug

I'm getting a horizontal scroll bar on the `name-container` div in Firefox:

![image](https://github.com/Lurkars/gloomhavensecretariat/assets/58171422/316bcddd-4066-4058-8d14-825bff552c14)

Changing `overflow-x: scroll;` to `auto` in its css fixes this, but I don't know what the implications for that are for the rest of the application. 

Edge on the same machine does not show the scroll bar, so it seems only Firefox is affected by this.

### Game Enviroment

using v0.95.14, Firefox 124.02, Windows 10, Resolution 3000x2000 with 200% scaling. Tried several scenario's, all give the same scroll bar with all monsters. Have restarted my browser, reloaded Secretariat, all without a different result. 

### To Reproduce

Start a scenario: see a scrollbar. 

### Expected behavior

Don't show a scroll bar

### Gloomhaven Secretariat Version

v0.95.14

### Used Browser

Firefox 124

### OS

Win 10

**Comment by Lurkars** [comment]
Should be fixed in [v0.95.15](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.95.15). Happy if you can verify and close issue if solved.

**Comment by pikdonker** [comment]
Fixed. Thanks for your continuing work and speedy replies!
