### ISSUE TITLE
Add support for Prism repair bot mode

### ISSUE THREAD

**Issue by desidius** [Lurkars/gloomhavensecretariat#567]
### Is your feature request related to a problem? Please describe.

This is related to one case as far as i know but when the repair drone is selected as mode it does not count for the effect.

I understand the player has to track multiple switches and so on but this would greatly help out by reducing actions done by the player when starting their turn.

The problem is when you start with wound/poison it would be nice not to have to backtrack and then heal/remove status effects.
This would also not require players to remember the heal on every round start.

### Describe the solution you'd like

Automatically apply a heal at start of every round when repair bot is mode.

### Describe alternatives you've considered

Simply ignore this..

### Additional context

Example of actions that need to be taken when Prism is wounded and repair bot is selected as mode.
(Automatic) Prism receives 1 damage
(Manual) Heal for 1 to counter Automation
(Manual) Remove wound
(Manual) Heal for 2

**Comment by Lurkars** [comment]
It's easy to add for my understanding. What confuses me now is this:

>  (Manual) Heal for 1 to counter Automation

I really don't understand. I would just automatic add a heal 2 when checked, so with wound:
- Wound applies for 1 damage
- Heal 2 applies with removing wound and adding 2 HP

**Comment by desidius** [comment]
Thanks for considering this.

My group goes on players decide the "Start-of-Turn" order of heal/wound (as shown in Gloomhaven's FAQ).
If your default is receiving damage and then heal (Total healing of 1) then it makes sense doing it that way to be consistent.

I only know of two classes that this could effect so it's not a big deal, getting rid of the wound and healing automatically is a big gain in my opinion :)

**Comment by Lurkars** [comment]
Damn, I didn't know about this rule, that it was player choice. That makes me feel bad if I just implement it as described now, but in the end it's just a matter of remembering for those who play differently to manually undo the automatic wound, so I'll add this as is and if there are any complaints I can think of a solution.

**Comment by desidius** [comment]
It's not something i knew about for a long time and i would guess most people play it your way.
Just getting the same results should be good for whichever way you want to play.

My group gets together once a week to have brunch and fun playing Frosthaven for the rest of the day so we like it lenient.
Thanks again!

**Comment by Lurkars** [comment]
Yes, you can now test the mode in [v0.97.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.97.0). Just enable it in the character menu and close this issue if it solved for you.

**Comment by desidius** [comment]
Just tested selecting the repair bot mode on the character and it works great.
I'd love to see it auto-activate if you only put the mode token on the bot itself but as this would basically only apply to this character i image the effort will be put in the backlog :)

This is really convenient and will be much loved in the next session!

Now to a "bug" that applies if the user does not select modes properly, the healing is applied twice (seems to do Prism's start of turn twice?):
Setup: Prism has "Repair Drone Mode" selected and Repair Drone does not have Mode selected.
1. Repair drone start it's turn
2. Prism gets healed for 2 and wound is removed
4. Repair drone finishes it's turn and Prism starts it's turn
5. Prism gets healed for 2

This might be fixed by changing the start of turn "detection" when a character has summons to mitigate the error.
Ultimately this would be user error but the healing at the start of the drone's turn should not be happening.

**Comment by desidius** [comment]
I tested a bit more with more than one summon and each time a summon (that's not selected as mode) start's it's turn Prism is healed for 2.

Setup: Repair Drone as Mode, Summon2 on the field.
1. Start of Summon2's turn, heal Prism for 2
2. Summon2 completes turn
3. Prism starts turn and heals for 2

**Comment by Lurkars** [comment]
Yes, will be fixed soon!

**Comment by Lurkars** [comment]
Should be fixed in [v0.97.1](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.97.1), happy if you can verify.

**Comment by desidius** [comment]
Can't find a fault, works perfectly ❤️ 
Thanks for the effort!
