### ISSUE TITLE
"Automatic Standee" Option spawns extra standees with fast keyboard inputs

### ISSUE THREAD

**Issue by OLavagante** [Lurkars/gloomhavensecretariat#570]
### Describe the bug

With the "Automatic Standees" option enabled, if you input numbers through the keyboard fast enough, extra standees will spawn. Example: Start a new scenario, and when you open standee number menu(let's say there is 1 elite and 1 normal of a specific type of monster), if you press quickly the numbers 1,2,3 on the keyboard, there will be an extra normal standee spawned. If initially there are only elite standees, the extra ones will be elite as well. 

### Game Enviroment

This can happen if you have the "Automatic Standees" option enabled.

### To Reproduce

1. Have the "Automatic Standees" option enabled and open any scenario.
2. Click on any unnumbered monster standee.
3. Press on your keyboard the numbers 1 through 6 (or 4 or 10, depending on monster type) as fast as you can.
4. See error: there are more standees than there are supposed to.

### Expected behavior

An expected behaviour would be for the extra inputs to be unregistered, i.e, no extra standees would spawn.

### Gloomhaven Secretariat Version

v0.96.1

### Used Browser

Chrome 124.0.6367.156 (64-bit)

### OS

Windows 10

### Additional

The bug also occurs with the "Automatic Standee Dialog" option enabled, since the only difference is that this option automatically pops up the standee number menu for each present monster.

**Comment by Lurkars** [comment]
Should be fixed now in [v0.97.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.97.0). Anyways, I would not recommend spamming short keys. If you're now spamming to much, dialogs closes and you trigger the element hotkeys. I won't fix that. Happy if you can verify if the issue is solved for you and then close it.

**Comment by OLavagante** [comment]
Thank you so much for fixing it. Didn't even know the hotkeys for the elements were a thing ahah, I'll keep it in mind.
