### ISSUE TITLE
Reputation from scenario rewards being added twice

### ISSUE THREAD

**Issue by davew9999** [Lurkars/gloomhavensecretariat#571]
### Describe the bug

I believe we have seen this happen a couple of times, and it has just happened again after completing scenario 72 - Oozing Grove. Upon completing the scenario we were given an extra 2 reputation instead of 1. I have attached a save you should be able to replicate it on.

[ghs-autobackup-2024-06-04T19_25_47.706Z.json](https://github.com/user-attachments/files/15570222/ghs-autobackup-2024-06-04T19_25_47.706Z.json)

### Game Enviroment

Gloomhaven scenario 72 - Oozing Grove

### To Reproduce

1. Load the attached save
2. Complete the scenario
3. Noticed that the reputation is increased by 2 instead of 1

### Expected behavior

The reputation is only increased by 1 upon completing the scenario

### Gloomhaven Secretariat Version

v0.96.1

### Used Browser

Windows exe install

### OS

Windows 10

**Comment by Lurkars** [comment]
Woah, thanks for noticing this. Seemed to be a stupid copy&paste error, it is really just twice in the code. Should be fixed in [v0.99.2](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.99.2). Happy if you can verify too and close issue if solved.

**Comment by davew9999** [comment]
Sure I will check when we next play, won't be for a while.
