### ISSUE TITLE
Tap to increase XP

### ISSUE THREAD

**Issue by tttopuz** [Lurkars/gloomhavensecretariat#577]
### Is your feature request related to a problem? Please describe.

We make a lot of use of the slider to increase XP or health, but this is sensitive. As the most common use is to increase XP, it would be nice if this could be done with one tap/click on the XP icon. 

![image](https://github.com/Lurkars/gloomhavensecretariat/assets/6255709/1dae64d0-f822-4e09-8fb3-6211af045028)

### Describe the solution you'd like

-

### Describe alternatives you've considered

-

**Comment by Lurkars** [comment]
Thanks for the input will come. To dec. XP I will set "double click" (long press on mobile).

**Comment by Lurkars** [comment]
Now implemented in [v0.99.8](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.99.8). Happy if you provide feedback and close issue if solved. Thanks.

**Comment by tttopuz** [comment]
Working! Thanks!
