### ISSUE TITLE
Shortcut icons for conditions

### ISSUE THREAD

**Issue by tttopuz** [Lurkars/gloomhavensecretariat#578]
### Is your feature request related to a problem? Please describe.

It would save some clicks, to be able to register the conditions on the "main screen" without having to open the figure menu. 

![image](https://github.com/Lurkars/gloomhavensecretariat/assets/6255709/1972cc75-dca5-4620-8fc7-58558c410402)

### Describe the solution you'd like

Clickable icons on the character bar for each condition which are greyed out when not in use and highlighted when in use.

### Describe alternatives you've considered

-

**Comment by Lurkars** [comment]
This will make the character board way too crowded. So I don't like it. There are keyboard shortcuts nearly for everything, so if some one really needs to act faster, I would recommend using/learning keyboard shortcuts.

**Comment by tttopuz** [comment]
I understand. In some scenario's characters get muddled nearly every turn, so accessing it from the main screen would save some clicks. 

I will look into the keyboard shortcuts. Is there a key to directly open the active standee menu? Also, maybe for directly opening character menu it would be nice to lock this to hotkeys? For example, s 1 always opens player 1, s2 always opens player 2, etc. ? That way you can open the menu without looking it up.

**Comment by Lurkars** [comment]
I added now in [v0.99.9](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.99.9) new shortcut <kbd>w</kbd> to behave same like <kbd>s</kbd>, but with fixed values (for characters). Also added setting to sort characters by player number. Hope this helps.
