### ISSUE TITLE
Three-eyes: Perk 7 should read enfeeble instead of empower

### ISSUE THREAD

**Issue by m42i** [Lurkars/gloomhavensecretariat#580]
### Edition

ToA

### Type of data

Character Stat/Sheet

### Describe the data affected

Perks, position 7, ritualist: empower

### Describe the error

On line 248 it should be „enfeeble“ instead of „empower“: https://github.com/Lurkars/gloomhavensecretariat/blob/1880ccc5d87b860cedf3b2227964ba23e1e9ff19/data/toa/character/three-eyes.json#L248

**Comment by Lurkars** [comment]
fixed in [v0.99.9](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.99.9)

**Comment by Lurkars** [comment]
yes, seemed I just replace the wrong enfeeble with empower, please verify if it is now correct in [v0.99.10](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.99.10)

**Comment by Lurkars** [comment]
So, I hope it's now all fixed in [v0.99.11](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.99.11). In the end it was all just stupid copy paste errors, but I first fixed the wrong line and overlooked another (not mentioned) error.
