### ISSUE TITLE
When shuffling and redrawing a new monster ability card the monster remains at old place in initiative instead of moving to new initiative.

### ISSUE THREAD

**Issue by Kafei56** [Lurkars/gloomhavensecretariat#581]
### Describe the bug

Title. There are items that allow you to redraw monster ability cards after revealing but the monsters don't move to their new updated initiative, instead having to manually move each one.

### Game Enviroment

All scenarios with monsters.

### To Reproduce

Click on revealed monster ability card and click shuffle.

### Expected behavior

Monster moves to new position in initiative order based on new card drawn.

### Gloomhaven Secretariat Version

v0.99.9

### Used Browser

Chrome

### OS

W11

**Comment by Lurkars** [comment]
Should be fixed now in  [v0.99.10](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.99.10). Happy if you can verify too and close issue if solved.

**Comment by Kafei56** [comment]
Thank you!
