### ISSUE TITLE
Can't use data management -> import game from file with Autosaves

### ISSUE THREAD

**Issue by Leprejuan** [Lurkars/gloomhavensecretariat#586]
### Edition

Both online and downloaded app.

### Type of data

Other

### Describe the data affected

data management -> Import game from file

### Describe the error

Hi!
I played Crimson Scales last in April, then had surgery and a spate of my day off not matching my game partner's day off.  I loaded up the game earlier this month to play, and we have no saved data.  No worries, I thought, I do the backups.  I pulled up the last autosave from April, but when the app tries to load it, it just...sits there.  

I can load the last named save I made myself back in December of last year.  It is 16 kb but I could play from that point because Secretariat can see our data from that time.  I don't WANT to play from there because we have gotten significantly further in the game.

None of the autosaves from after that seem to work.  I pulled up Notepad and I can SEE the data in the autosaves, but they are noticeably larger, 1822 kb-1966 kb.  

Is there a format difference in the autosaves compared to manual saves?  I don't understand why Secretariat can't read its own autosave.

Best,
John

**Comment by Leprejuan** [comment]
[ghs-gameCRIMSONBACKUP.json](https://github.com/user-attachments/files/15938286/ghs-gameCRIMSONBACKUP.json)
Is the last file that it can read.

[ghs-autobackup-2024-04-17T19_22_59.748Z.json](https://github.com/user-attachments/files/15938288/ghs-autobackup-2024-04-17T19_22_59.748Z.json)
Is the one I WANT to read.

**Comment by Lurkars** [comment]
Cannot test myself now, buf if one file is auto backup, then please usecthe "import data dump" functionality instead of "import game".

**Comment by Leprejuan** [comment]
I think that this did it.  I can see updated characters.  Thanks so much!
