### ISSUE TITLE
[FH] Item 57 should be lost after use

### ISSUE THREAD

**Issue by keinkurt** [Lurkars/gloomhavensecretariat#592]
### Edition

FH

### Type of data

Other

### Describe the data affected

Item 57 (Shovel)

### Describe the error

Now, the Item 57 looks
<img width="213" alt="image" src="https://github.com/Lurkars/gloomhavensecretariat/assets/6031362/a0380dfa-5b3b-498b-b4b0-22e2db148788">
but it should have a lost icon (from gloomhavencard.com)
<img width="269" alt="image" src="https://github.com/Lurkars/gloomhavensecretariat/assets/6031362/4708d259-dfa8-4266-ab43-fd1d93b0e780">

**Comment by Lurkars** [comment]
Should be fixed in [v0.99.13](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.99.13).

**Comment by keinkurt** [comment]
Thanks, it works!
