### ISSUE TITLE
Add Drill Identities to Entity Menu

### ISSUE THREAD

**Issue by rdollffg** [Lurkars/gloomhavensecretariat#596]
### Is your feature request related to a problem? Please describe.

In our group, our Drill uses a mobile device to access GHS and has trouble hitting the pressure gauge to swap identities.

### Describe the solution you'd like

For characters with multiple identities, add their current identity icon to the Entity Menu. Clicking the icon or character's name will swap their current identity.

### Describe alternatives you've considered

I considered putting all identities below the character's name in the Entity Menu, but it was too busy.

### Additional context

I prototyped a rough solution and the class icon next to the identity icon looked odd enough that I wanted some feedback before continuing. I'd obviously align the icon and text correctly, but you get the idea.

![image](https://github.com/user-attachments/assets/067d9134-5825-4d88-89be-ee78e1af4cc0)

Let me know if you'd like me to finish this. And, if so, do you want to refactor the identity logic out of character.ts so it won't be duplicated it in entity-menu-dialog.ts?

**Comment by Lurkars** [comment]
added in [v0.99.16](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.99.16). Happy about feedback. I just added it to the bottom of the menu:
![image](https://github.com/user-attachments/assets/deba393e-e9c8-4347-9afa-77826b339dc8)

**Comment by rdollffg** [comment]
Validated as working. We'll definitely use this at our next session in a few weeks. Amazing response time -- thanks!
