### ISSUE TITLE
Brittle/ward applying when removing health and gaining condition.

### ISSUE THREAD

**Issue by Kafei56** [Lurkars/gloomhavensecretariat#597]
### Describe the bug

With automatic confirm conditions enabled, when you reduce an enemies health and apply brittle simultaneously the brittle is applied to the damage input from the attack applying brittle.

### Game Enviroment

Automatic apply conditions on with Brittle and Ward.

### To Reproduce

1. Go to standee and apply brittle and reduce health
2. Back out and the brittle is removed immediately and the health loss doubled.

### Expected behavior

The health should be removed by what you input and the brittle should remain.

### Gloomhaven Secretariat Version

v0.99.15

### Used Browser

Chrome

### OS

W11

**Comment by Lurkars** [comment]
Thanks for noticing, should be fixed now in [v0.99.16](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.99.16). Happy if you can verify and close issue if solved.

**Comment by Kafei56** [comment]
Thank you!
