### ISSUE TITLE
Summon poison/wound etc. do not apply unless "Active summons" setting is enabled.

### ISSUE THREAD

**Issue by Kafei56** [Lurkars/gloomhavensecretariat#598]
### Describe the bug

These conditions only trigger automatically when "Active summons" setting is enabled.

### Game Enviroment

Classes with summons.

### To Reproduce

1. A figure with summons turn is activated.
2. Summons conditions aren't automatically applied

### Expected behavior

When the figure with summons turn is activated have the summons conditions apply, like losing health to wound or gaining health from regenerate.

### Gloomhaven Secretariat Version

v0.99.16

### Used Browser

Chrome

### OS

W11

**Comment by Lurkars** [comment]
Should be fixed in [v0.99.17](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.99.17). Happy if you can verify and close issue if solved.

**Comment by Kafei56** [comment]
Looks good! Though for some reason stun remains on summons after their turn ends?

**Comment by Lurkars** [comment]
It should be transparent as reminder, that it was still stunned on it's turn.

**Comment by Kafei56** [comment]
I see, thank you!
