### ISSUE TITLE
Active summons change double click to end turn to single click to match functionality with the rest of the figures turns.

### ISSUE THREAD

**Issue by Kafei56** [Lurkars/gloomhavensecretariat#599]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

I would like to be able to single click on the summon that is activated to end it's turn. just like I would single click on any other figure to end their turn.

### Describe alternatives you've considered

None

**Comment by Lurkars** [comment]
Just single click on the character portrait. Single click on summon not possible, because single click opens menu.

**Comment by Kafei56** [comment]
Oh derp, sorry about that!
