### ISSUE TITLE
Soldier Tracking

### ISSUE THREAD

**Issue by glenn-fredrx** [Lurkars/gloomhavensecretariat#603]
### Is your feature request related to a problem? Please describe.

Currently when training up soldiers, you need to manually go through the party to collect the needed resources.

### Describe the solution you'd like

On the campaign sheet there is a section for the number of soldiers per level.  When soldiers are trained up have an option to collect the resources from the party.  This could be a prompt when the soldier box is checked.  Also grey out the levels that are higher than the current level of the barracks.

### Describe alternatives you've considered

None

**Comment by Lurkars** [comment]
Good ideas, will add this.

**Comment by Lurkars** [comment]
Add this in  [v0.99.22](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.99.22). Happy if you can test and verify. Please close issue if solved.

**Comment by glenn-fredrx** [comment]
Works great.  I also appreciate that a double click allows you to add without having to pay.

Thanks for all the work on the app, it is awesome.
