### ISSUE TITLE
Frosthaven Building Upgrade Error

### ISSUE THREAD

**Issue by glenn-fredrx** [Lurkars/gloomhavensecretariat#604]
### Describe the bug

I should be able to upgrade the Craftsman building, I have the needed prosperity and resources, but it is greyed out.  After upgrading the Alchemist, then the Craftsman is ungreyed and available to upgrade.
[ghs-data-dump-2024-08-16T12_52_32.515Z.json](https://github.com/user-attachments/files/16637301/ghs-data-dump-2024-08-16T12_52_32.515Z.json)
<img width="827" alt="Building Upgrade Error" src="https://github.com/user-attachments/assets/606204e0-e61a-4ef5-a973-966daedcc10c">

### Game Enviroment

Files attached, both the screen shot before the Alchemist upgrade, the current prosperity and then after the upgrade.  Also included a data dump from the app.

### Expected behavior

Noted above

### Gloomhaven Secretariat Version

v0.99.21

### Used Browser

Chrome

### OS

Windows 11

**Comment by glenn-fredrx** [comment]
OK, so I figured out what is going on and found the actual bug.  It looks like the wrong prosperity tracker was being shown.  It was showing the gloomhaven version and not the frosthaven one.  If you go from Campaign/Character Management, Global Campaign Management, then the correct prosperity tracker is shown.  However if you go from Campaign/Character Management, Party/Campaign Sheet, then select the Gloomhaven Party Sheet link below the Town Guard perks, then choose Campaign.  The prosperity tracker for gloomhaven is shown instead of the frosthaven one.

So the correct conditions for upgrading the buildings is actually correct.  By upgrading the alchemist, that pushed the party to prosperity 2 and then unlocking the upgrade for Craftsman is correctly unlocked.

**Comment by Lurkars** [comment]
Sorry, I can't really follow here now. You should not really use the "Go to Gloomhaven Party Sheet" in a normal Frosthaven Campaign. The Global Campaign sheet is accessible on the top of the Campaign Sheet, see
![image](https://github.com/user-attachments/assets/f69e5f52-4aae-4d24-9c27-4d70a069bad2)

Anyways, seems there is no actual issue. So I will close this.
