### ISSUE TITLE
Can only select numbers 1-4 for Polar Bear despite having 1-6 standees

### ISSUE THREAD

**Issue by joewesch** [Lurkars/gloomhavensecretariat#605]
### Describe the bug

When I went to select which standee I was using for the Polar Bear at the start of scenario 8, it only allows me to select numbers 1-4, but I have 1-6 standees.

### Game Enviroment

Frosthaven, scenario 8

### To Reproduce

1. Turn off Random standees setting
2. Load scenario 8
3. Try and pick Polar Bear 6

### Expected behavior

Standees Numbers 1-6 available to choose from

### Gloomhaven Secretariat Version

v0.99.21

### Used Browser

Chrome

### OS

ChromeOS

### Additional

![Screenshot 2024-08-18 9 52 54 PM](https://github.com/user-attachments/assets/92986073-48e9-42a3-855f-ec0a6a5c6394)

**Comment by Lurkars** [comment]
I did some research and that seems a change for second printing. In my (first) printing, I only have 4 standees. Will update!

**Comment by Lurkars** [comment]
added 6 standees now in  [v0.99.22](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.99.22). Happy if you can verify fix and close issue if solved.

**Comment by joewesch** [comment]
Confirmed, fixed. Thanks again for the super fast fix!
