### ISSUE TITLE
Add required prerequisite settings to hover tooltips

### ISSUE THREAD

**Issue by joewesch** [Lurkars/gloomhavensecretariat#606]
### Is your feature request related to a problem? Please describe.

I was trying to enable the Draw Random Item on Loot setting, but it was disabled. When I hovered over the small `i` icon next to it, it told me what the setting did but not what other setting I had to enable first to allow me to enable this setting. I started enabling other settings that seemed related until I finally found it. It would have been nice to know that it required the Character Items setting to be enabled as a prerequisite.

### Describe the solution you'd like

I'd like to see any prerequisite settings as part of the tooltip that shows up when you hover over the `i` next to the setting.

### Describe alternatives you've considered

Trial and error.

**Comment by Lurkars** [comment]
Thanks for the input, added this in [v0.99.22](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.99.22). Happy about feedback or close this issue if satisfied with result.

**Comment by joewesch** [comment]
Amazingly fast turn-around, and excellent execution. It looks great! Thank you so much for adding this.
