### ISSUE TITLE
Ward doesn't remove after reducing damage from wound until turn is ended.

### ISSUE THREAD

**Issue by Kafei56** [Lurkars/gloomhavensecretariat#607]
### Describe the bug

When a figure has wound and ward upon beginning there turn the wound triggers, then ward triggers and the health is regained as it should, but the ward remains until you start the next figures turn. This causes confusion when finishing the turn because the player will think they still have ward for there turn when it should have fallen off.

### Game Enviroment

Anytime a figure has wound and ward and the following settings are enabled: Automatic Apply Conditions (ward), Automatic Confirm Conditions (ward).

### To Reproduce

Figure has wound and ward.
Turn begins.
Wound triggers, then ward triggers and health goes back to initial value.
Ward doesn't remove.
Start next figures turn and ward removes from previous figure.

### Expected behavior

Ward removes when it prevents the damage from wound.

### Gloomhaven Secretariat Version

v0.99.22

### Used Browser

Chrome

### OS

W11

**Comment by Lurkars** [comment]
Thanks for noticing this. Was a very small issue, but I still put out a new version [v0.99.23](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.99.23) . So happy if you can verify the fix too and close issue if solved.

**Comment by Kafei56** [comment]
Thank you for the quick fix!
