### ISSUE TITLE
Hive repair drone mode heals every time the figure is activated.

### ISSUE THREAD

**Issue by Kafei56** [Lurkars/gloomhavensecretariat#609]
### Describe the bug

When repair drone mode is activated (under the conditions menu) Hive heals each time he is activated or re-activated during the round.

### Game Enviroment

All.

### To Reproduce

1. Enable repair drone mode under conditions menu.
2. Enter initiative and begin round.
3. Activate Hive's turn.
4. Activate a different figures turn (previous or next)
5. Activate Hive again.
6. Heal goes off again.

### Expected behavior

The heal would only activate once per round, no matter how many times Hive's turn is activated.

### Gloomhaven Secretariat Version

0.100.1

### Used Browser

Chrome

### OS

W11

**Comment by Lurkars** [comment]
Thanks for noticing. Should be fixed in [v0.100.2](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.100.2). Happy if you can verify and close issue if solved.

**Comment by Kafei56** [comment]
Looks good, thank you!
