### ISSUE TITLE
[Frosthaven] "Snowflake" character perk auto apply

### ISSUE THREAD

**Issue by joewesch** [Lurkars/gloomhavensecretariat#611]
### Is your feature request related to a problem? Please describe.

The snowflake character has a perk that muddles everyone at the start of each scenario, as well as each new enemy that is revealed each time a room is revealed.

### Describe the solution you'd like

I'd like to see an "Apply" pop up button - like you have for other scenario effects - that is enabled once I've completed the perk on the character. When I click Apply, it would automatically add muddle to every monster at the start of each scenario and again to each monster that gets revealed via new sections/rooms.

### Describe alternatives you've considered

1. I have to click/tap through every monster and muddle them individually
2. I have to actually remember to do this (the hardest part 😄)

**Comment by Lurkars** [comment]
I added this in [v0.100.4](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.100.4). I used the special actions for this, so if you have the perk selected, you can enable the automation in the character menu. Afterwards, every new revealed monster should get muddled. Happy if you can verify and provide feedback if this is working for you!
![image](https://github.com/user-attachments/assets/de1abe4c-fbdd-45c7-ada1-61c255097c29)

**Comment by joewesch** [comment]
Works great, thanks as always!
