### ISSUE TITLE
Menu screen to quickly manage party member inventory

### ISSUE THREAD

**Issue by joewesch** [Lurkars/gloomhavensecretariat#612]
### Is your feature request related to a problem? Please describe.

There are times during the game where we are instructed to gain or lose items (gold, XP, crafting items, etc.) collectively or each; for example, during some road or outpost events. More specifically, during the building operations phase in Frosthaven we lose collective gold to gain collective crafting items. Our party tries to spread the gold cost of crafting items - as well as who gets the items - evenly across the party members so that no one character has all the gold or all the crafting items.

### Describe the solution you'd like

I'd like to see a party inventory menu that can be brought up on-demand to quickly assess who has the most gold or the most of a single crafting item and be able to increase or decrease those numbers via this menu.

### Describe alternatives you've considered

Right now, for example, during the building operations phase I click on each character's icon to see who has the most gold and then they pay for the crafting items. After that I go back through everyone to see who has the least of each crafting and distribute them evenly.

### Additional context

I am envisioning something that is similar to the modals that pop up at the end of the scenario or during the construction phase that shows you all party members' inventory.

**Comment by Lurkars** [comment]
Currently, if you click on the Campaign Sheet on Frosthaven Supply, a pop-up like this appears:
![image](https://github.com/user-attachments/assets/5ee00259-3994-404d-b0ee-f24f52deccbd)

Is this what you mean? I can add Gold to the table, if you want.

**Comment by joewesch** [comment]
> Is this what you mean?

That panel is read only, correct? I would like a place that I can not only see everyone's supply but also increase/decrease the values as well.

> I can add Gold to the table, if you want.

I'm also looking for XP as well, please.

I pretty much want everything on this panel, but for all active party members on the same view:
![Screenshot 2024-09-30 at 12 55 53 PM](https://github.com/user-attachments/assets/7df0b1ce-0f32-47dc-8317-5f91cac43683)

**Comment by Lurkars** [comment]
I will think about this. Maybe I just add gold (and XP) to the table and make it editable. Just need a better place where to open it.

**Comment by Lurkars** [comment]
Sorry for taking so long. So I edited the screen now in [v0.102.4](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.102.4). There is an "Edit" Button on top to toggle edit mode. Also added Gold and XP. View is also accessible from Campaign Menu.

Happy about Feedback/Testing.

**Comment by joewesch** [comment]
I definitely like it, thanks! I poked around at it a bit and I do have one point of feedback so far.

I find myself naturally following this sequence:
- I open the window
- enable the Edit checkbox
- making my changes
- disable the Edit checkbox
- click outside of the window to dismiss it

This sequence causes the changes to not be saved as I never hit "Apply changes" at the bottom of the window. Is there any better UX for this? I feel like something should happen when I disable the checkbox instead of simply leaving edit mode. Can you change it so it will save automatically when you leave Edit mode, possibly? Unless you think that's counterintuitive or that there should be some other alternative.

**Comment by Lurkars** [comment]
Thanks for the feedback. In [v0.102.5](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.102.5) I made it the following:
- if just open, close with click as before
- if you toggle to edit mode, but don't touch anything, close with click as before
- if you edit something:
  - edit button is grayed out, no toggle back to view
  - dialog only closable via "close" (discard changes) or "apply"
  
Hope that's fine now.

**Comment by joewesch** [comment]
Yes, I can't accidentally click away without saving or discarding now. Thanks!
