### ISSUE TITLE
[Frosthaven] "Draw Random Item on Loot" not working?

### ISSUE THREAD

**Issue by joewesch** [Lurkars/gloomhavensecretariat#613]
### Describe the bug

I have the "Draw Random Item on Loot" setting enabled in my settings and it doesn't seem to randomly select any item. Instead, it just shows a treasure chest icon in the loot menu:
![Screenshot 2024-09-29 at 3 54 00 PM](https://github.com/user-attachments/assets/b216beec-7ac2-489f-92b8-6ed1dbaad8e3)

Then, when you finish the scenario, it shows that character gaining the random item in the scenario recap screen:
![Screenshot 2024-09-29 at 3 54 26 PM](https://github.com/user-attachments/assets/8eca1d23-8517-4d39-8cc8-f133024a2deb)

Lastly, if you then go to the character sheet, the character doesn't have any new items but can move the random item to the frosthaven supply:
![Screenshot 2024-09-29 at 3 55 02 PM](https://github.com/user-attachments/assets/5c570f88-32f9-4d09-87b4-467bfe40ada8)

Moving it to the Frosthaven supply does nothing (as far as I can tell).

### Game Enviroment

This can be seen as early as scenario 2 as it's the first scenario that has a random item as part of the loot deck.

### To Reproduce

1. Enable the "Character Items" setting to unlock the "Draw Random Item on Loot" setting
2. Enable the "Draw Random Item on Loot" setting
3. Start a Frosthaven campaign
4. Select any 2 characters
5. Start scenario 1 and immediately complete it with a success so you can unlock scenario 2
6. Start scenario 2 and start looting until you get a random item
7. No item gets attributed to the character who is looting

### Expected behavior

I'm not sure what it is supposed to do, and maybe I'm missing a step? I apologize if I am, so please let me know.

### Gloomhaven Secretariat Version

v0.100.3

### Used Browser

Chrome

### OS

Chrome OS

**Comment by Lurkars** [comment]
Cannot reproduce, drawing this loot should end in this pop-up:
![image](https://github.com/user-attachments/assets/f5215e40-134e-42f0-92a8-cdfbefaf64e5)

**Comment by joewesch** [comment]
I loaded up https://gloomhaven-secretariat.de/ in an incognito window to start a brand new instance to test this. Here are the exact steps I followed:

1. Enable the "Character Items" setting to unlock the "Draw Random Item on Loot" setting
2. Enable the "Draw Random Item on Loot" setting (if not already enabled, for me it was enabled after selecting "Character Items")
3. Start a Frosthaven campaign
4. Select any 2 characters
5. Start scenario 1 and immediately complete it with a success so you can unlock scenario 2
6. Start scenario 2 and start looting until you get a random item
7. No item gets attributed to the character who is looting

Here is the settings export from that session:
[ghs-settings.json](https://github.com/user-attachments/files/17194370/ghs-settings.json)

**Comment by Lurkars** [comment]
I can completely follow this steps and get the exact result I posted above. Can you try a different browser? Is this an ad-blocking thing? As said, I just can't reproduce this.

**Comment by joewesch** [comment]
I tried disabling uBlock and PiHole. I tried a different browser. I tried a VPN. I even had a friend in another state try. I still can't get it to work.

Can you provide an export of your settings or game backup where it is working to see if your settings will work for me?

**Comment by Lurkars** [comment]
I use the default settings just as you describe. Enable Character Items and start. Also importing your settings posted here work fine for me!
[Screencast from 01.10.2024 21:58:53.webm](https://github.com/user-attachments/assets/0e4bbbfe-3c35-415e-ac9e-8fbd05767632)

**Comment by joewesch** [comment]
Wow, yeah that pop-up doesn't show up for me. Ok, let me dig in to the browser tools to see if there are any red flags on why it's not popping up for me.

**Comment by joewesch** [comment]
Ah ha! I can get it to work if I click on the loot deck. Try using the keyboard shortcut (`l`)?

**Comment by Lurkars** [comment]
Thanks for digging deeper and noticing this. Hopefully fixed now in [v0.100.5](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.100.5). Happy if you can verify!

**Comment by joewesch** [comment]
Confirmed fixed! Thanks for your patience and glad we finally got to the bottom of this.
