### ISSUE TITLE
[JotL] Scenario 11 applies section 2 special rules at beginning of the scenario

### ISSUE THREAD

**Issue by joewesch** [Lurkars/gloomhavensecretariat#614]
### Describe the bug

When you start scenario 11 in a Jaws of the Lion campaign, it wants to immediately apply the Special Rules for section 2 (spawn items at B and C). When you finally get to the point when you are supposed to spawn monsters for section 2, it shows it as already applied:
![Screenshot 2024-09-29 at 4 21 49 PM](https://github.com/user-attachments/assets/e1f45509-4d97-4fef-91e5-d6364ab2133f)

### Game Enviroment

Jaws of the Lion scenario 11

### To Reproduce

1. Start Jaws of the Lion scenario 11
2. A box at the bottom pops up and asks you to spawn items at B and C already

### Expected behavior

I expected monsters to spawn at B and C after revealing section 2 instead of at the beginning.

### Gloomhaven Secretariat Version

v0.100.3

### Used Browser

Chrome

### OS

Chrome OS

**Comment by Lurkars** [comment]
No idea why, but it's just a simple type in the data. It's `revealedRooms` instead of `requiredRooms`. So will be fixed soon.

Thanks for noticing.

**Comment by Lurkars** [comment]
Solved in [v0.100.4](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.100.4)
