### ISSUE TITLE
[Gloomhaven] Scenario 33 locked while shouldn't be 

### ISSUE THREAD

**Issue by Jedayr** [Lurkars/gloomhavensecretariat#615]
### Describe the bug

Scenario 33 is locked after party lost one of requirements, but still has other. Scenario books suggests that party require 

### Game Enviroment

Gloomhaven 1st edition.
Completed scenario: 16, 24, 25, 30, 32. 34. Unlocked:  40 (not locked but require 33), 42
 Achievement from scenario 24 is with us, achievement from scenario 25 lost in scenario 34.

### To Reproduce

1. Create new save
2. Set scenarios 1, 2, 3, 8, 14, 7, 20, 16, 24, 30, 32, 25 
3. See 33 scenario as unlocked
4. Set scenario 34 as completed
5. 33 scenario locks itself, but it should be open from 32. 

### Expected behavior

Scenario 33 should be unlocked.

### Gloomhaven Secretariat Version

v0.100.3

### Used Browser

Vivaldi

### OS

Ubuntu / Win 10 

### Additional

Reproduced bug in extra save, got dump data.
[ghs-data-dump.json](https://github.com/user-attachments/files/17185871/ghs-data-dump.json)

**Comment by Lurkars** [comment]
Solved in [v0.100.4](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.100.4).
