### ISSUE TITLE
macOS intel version

### ISSUE THREAD

**Issue by wimch** [Lurkars/gloomhavensecretariat#617]
### Is your feature request related to a problem? Please describe.

There are no more builds for macOS that work on intel chips.
The last version that currently works on intel chips is 0.95.15. 

### Describe the solution you'd like

Is it possible to release macOS intel builds again?

### Describe alternatives you've considered

/

**Comment by Lurkars** [comment]
Okay I will try to check. I don't have Mac and just use `electron` and `electron-builder`. I will do some research if something has changed here in the meantime. Maybe a bit back-and-forth testing here, because I don't own any Apple Devices to test.

**Comment by Lurkars** [comment]
I changed now to 'universal` build in [v0.100.6](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.100.6). But as said, I cannot test if this is the correct way, so happy if you can test.

**Comment by wimch** [comment]
It works!
Thank you!
