### ISSUE TITLE
Validation of FH Scenario Loot Data

### ISSUE THREAD

**Issue by Doctawin** [Lurkars/gloomhavensecretariat#62]
For the scenario data, I focused on checking the loot deck, since it's more obvious when playing if there's a wrong/missing monster. When possible, I also tried to check the special scenario rules for health values. 

I organized the following by line number until there was an addition/removal---at which point, I switched to scenario number identification for clarity. 

- [x] line 106: corpsecap = 1 
- [x] line 127: corpsecap = 1
- [x] line 197: rockroot -> axenut 
- [x] lines 233, 237, 241: take the floor, since these ice pillar health values should be rounded down
- [x] Scenario 17: There should be 4-C spectral helpers; it looks like the code always creates 2. I don't believe the spectral helpers have health, at least I didn't see a health value for them. 
- [x] line 547: metal = 4
- [x] line 585: arrowvine = 1 
- [x] line 730: flamefruit = 1
- [x] lines 780, 784, 788, 792: take the floor as the health of the doors are rounded down
- [x] Scenario 64: Should be C*2 militia members, not always 8. 
- [x] line 1687: money = 7
- [x] line 1688: lumber = 5
- [x] line 1689: metal = 2
- [x] line 1690: hide = 3
- [x] line 1691: rockroot -> flamefruit 
- [x] line 1693: remove random item
- [x] Scenario 82 (line 1878): snowthistle = 2
- [x] Scenario 85 (line 1935): snowthistle = 1
- [x] Scenario 111 (line 2485): remove random item 
- [x] Scenario 112 (line 2503): rockroot = 2
- [x] Scenario 112 (line 2504): axenut = 1 
- [x] Scenario 122 (line 2771): rockroot = 2 
- [x] Scenario 129 (line 2959): money = 10
- [x] Scenario 129 (line 2960):
- [x] Scenario 129 (line 2961): metal = 2
- [x] Scenario 129 (line 2962): hide = 2
- [x] Scenario 129 (line 2963): rockroot -> axenut
- [x] Scenario 129 (line 2964): arrowvine -> snowthistle and change value to 1
- [x] Scenario 129 (line 2965): remove random item 
- [x] Scenario 130 (line 2983): arrowvine = 2

**Comment by Lurkars** [comment]
Thank you again @DoctawinDoctawin for contribution (maybe I need to teach you some Git basic, so you can create PR directly)

**Comment by Doctawin** [comment]
> Thank you again @Doctawin for contribution (maybe I need to teach you some Git basic, so you can create PR directly or you take a look at something like this: https://www.dasblinkenlichten.com/how-to-create-a-github-pull-request-pr/)

You're welcome. Thanks for the reference. I'll read up :)
