### ISSUE TITLE
Buttons & Bugs: Gloomtoad deck errors

### ISSUE THREAD

**Issue by bealeofsteel** [Lurkars/gloomhavensecretariat#626]
### Edition

Buttons & Bugs

### Type of data

Monster Stat/Ability

### Describe the data affected

Gloomtoad abilities at initiative 37 and 43

### Describe the error

Two issues with the Gloomtoad's ability deck:

1) The initiative 37 ability should have range 2 instead of 3
2) The initiative 43 ability should have range 2 (no range is specified), and the element consumption should trigger Muddle instead of Poison

**Comment by Lurkars** [comment]
Thanks, should be fixed in [0.103.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.103.0). Happy if you can verify and close issue if solved.

**Comment by bealeofsteel** [comment]
Still one small issue here: the initiative 43 ability should apply Muddle instead of Poison when the element is consumed

**Comment by Lurkars** [comment]
Totally overlooks that muddle issue, should be fixed in [0.103.1](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.103.1).

**Comment by bealeofsteel** [comment]
Fixed now, thanks!
