### ISSUE TITLE
Implement new B&B advantage/disadvantage rules

### ISSUE THREAD

**Issue by bealeofsteel** [Lurkars/gloomhavensecretariat#627]
### Is your feature request related to a problem? Please describe.

A few days ago, the rules in Buttons & Bugs for advantage and disadvantage were changed to be more in line with how those mechanics work in other Gloomhaven games: https://boardgamegeek.com/thread/3401129/living-rules-update-20241107

Instead of rolling twice in the same row, advantage and disadvantage now roll from two consecutive rows.

### Describe the solution you'd like

Clicking the advantaged/disadvantaged draw buttons should roll from two consecutive rows (and increment the row counter appropriately), displaying both options as it does now. 

### Describe alternatives you've considered

Currently we can manually draw twice, but it's nicer to see both cards side by side.

**Comment by Lurkars** [comment]
Thanks, should be changed in [0.103.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.103.0). Happy if you can verify and close issue if solved.

**Comment by bealeofsteel** [comment]
Looks good to me, thanks for the quick fix!
