### ISSUE TITLE
Can't upgrade Barracks (FH) GHS version 0.103.1

### ISSUE THREAD

**Issue by rehajel** [Lurkars/gloomhavensecretariat#629]
### Describe the bug

There is no button to upgrade the barracks from level 2 to level 3.
We pulled an Outpost event to upgrade the barracks to the next level but there is no button to do so.

### Game Enviroment

GHS Version 0.103.1, self hosted, running as docker container in unraid.

### To Reproduce

Try to level Barracks from level 2 to level 3

### Expected behavior

There should be an upgrade button next to the barracks, but it is missing.

### Gloomhaven Secretariat Version

v.0.103.1

### Used Browser

Firefox 130.0 (64-bit)

### OS

Unraid Server, Linux und iPadOs Clients

**Comment by Lurkars** [comment]
Should be fixed in [v0.104.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.104.0). Happy if you can verify and close issue if solved.

**Comment by rehajel** [comment]
It works now, thank you for the fast fix and for making such an awesome tool!
