### ISSUE TITLE
When enabling "Appendix F: Favors Wealth" show the updated gold conversion in the bottom bar.

### ISSUE THREAD

**Issue by Kafei56** [Lurkars/gloomhavensecretariat#630]
### Is your feature request related to a problem? Please describe.

No.

### Describe the solution you'd like

When enabling the Wealth favor it would be great to have the gold conversion show the new +1 amount without having to remember.

### Describe alternatives you've considered

Just remembering it.

**Comment by Lurkars** [comment]
Added in [v0.104.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.104.0). Happy if you can verify and close issue if satisfied with result.

**Comment by Kafei56** [comment]
Looks good, thank you!
