### ISSUE TITLE
Automation of Challenge Cards 1487 and 1525 are not working correctly

### ISSUE THREAD

**Issue by keinkurt** [Lurkars/gloomhavensecretariat#635]
### Describe the bug

For Challenge Card 1487 - the wound would be apply when either negativ and positiv conditions would be apply, but it should on apply wound on applying negativ conditions.

For Challenge Card 1525 - The Monster will only get the strenghten when you double click on the negativ condition to remove them, but IMHO it should also be apply if a negativ condition expire at the end of the monsters next full turn.

### Game Enviroment

v0.105.2

### To Reproduce

1. Start a scenario
2. Draw and activate the challenge cards Hypochondria and Spiteful Retribution
3. Give a character a positiv condition, the character also gain wound
4. Give a monster a negativ condition
5. After the turn of this monster, the nagativ condition automatically removed, but no stregthen is applied

### Expected behavior

3. Give a Character a positov condition, it should not apply wound on them
5. After the turn of this monster, the nagativ condition automatically removed and strenghten should be apply

### Gloomhaven Secretariat Version

v0.105.2

### Used Browser

Firefox

### OS

macOS 14.5

**Comment by Lurkars** [comment]
Should be fixed in [v0.105.4](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.105.4). Happy if you can verify and close issue if solved.

**Comment by keinkurt** [comment]
Yes, it works now as expected. Thank you!
