### ISSUE TITLE
[JOTL] Scenario 16 monster text incorrect

### ISSUE THREAD

**Issue by joewesch** [Lurkars/gloomhavensecretariat#637]
### Describe the bug

In Jaws of the Lion Scenario 16, after starting the last phase (door 2), when the Rat Monstrosity spawns they have the following text on their character card "Spawn 1 Elite Black Imp":
![Screenshot 2024-12-16 at 11 05 47 AM](https://github.com/user-attachments/assets/e0943229-466d-48ca-bbf1-518a9a078e1c)

Although, in the rule book (at least the one that I have) their innate ability is still that nearby figures suffer damage, **but** if those figures die _because_ of said damage **then** they spawn a black imp:
![PXL_20241214_011633597](https://github.com/user-attachments/assets/09f905dd-38a6-4055-99de-a2ed737210b2)

So, the wording on their character card of "Spawn 1 Elite Black Imp" is not technically correct as spawning a black imp doesn't happen every time. This can cause confusion.

_Note: This was probably a copy from the previous phase (door 1) when all rats spawn blood imps instead of causing adjacent figures to suffer damage, but in this last phase they go back to causing damage again when they die._

### Game Enviroment

Jaws of the Lion Scenario 16, door 2

### To Reproduce

1. Start JOTL Scenario 2
2. Open door 2
3. Start round and spawn Rat Monstrosity
4. See Rat Monstrosity innate ability

### Expected behavior

I expect the standard Rat Monstrosity innate ability:
![Screenshot 2024-12-16 at 11 14 56 AM](https://github.com/user-attachments/assets/6bd9c9e7-7810-4f63-8664-a61be0af81e2)

But, if you can add the caveat that black imps are spawned on death of this damage it would help.

### Gloomhaven Secretariat Version

v0.105.4

### Used Browser

Chrome

### OS

Chrome OS

**Comment by Lurkars** [comment]
Thanks, should be fixed in [v0.105.5](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.105.5). Happy if you can verify and close issue if solved.

**Comment by joewesch** [comment]
@Lurkars not quite correct, the are indeed **black** imps and not blood imps on the last phase. The rest of the text looks correct, though.
![Screenshot 2024-12-16 at 3 53 09 PM](https://github.com/user-attachments/assets/da88ffe3-7b49-49da-8f82-a9d9f7d53666)

**Comment by Lurkars** [comment]
Should be fixed in [v0.105.6](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.105.6) now.

**Comment by joewesch** [comment]
Confirmed, fixed. Thanks!
