### ISSUE TITLE
[JOTL] Demolitionist level 5 card bug

### ISSUE THREAD

**Issue by joewesch** [Lurkars/gloomhavensecretariat#638]
### Describe the bug

The level 5 card for the Demolitionist provides a mech suit that increases the max health of the character and heals them 10 when they put it on. This part works great. If you remove the mech suit while still in a scenario, it removes 5 points from your max health as well. However, if you finish the scenario with the mech suit still applied it removes 10 points from the character max health instead.

### Game Enviroment

Jaws of the Lion, Demolitionist character level 5 mech suit

### To Reproduce

1. Start a JOTL Campaign
2. Add a Demolitionist character
3. Change the character's level to 5 (max health should be 14)
4. Start the scenario's first round
5. Click the Demolitionist and enable the "Mech Suit" option at the bottom of the card (max health goes up to 19)
6. Finish the scenario (Demolitionist max health goes down to 9)

### Expected behavior

I expect it to remove 5 max health instead.

### Gloomhaven Secretariat Version

v0.105.4

### Used Browser

Chrome

### OS

Chrome OS

**Comment by Lurkars** [comment]
Thanks, should be fixed in [v0.105.5](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.105.5). Happy if you can verify and close issue if solved.

**Comment by joewesch** [comment]
Confirmed fixed. Thanks as always for being so quick!
