### ISSUE TITLE
Flame and Chaos Demon Area Attack Placement

### ISSUE THREAD

**Issue by Doctawin** [Lurkars/gloomhavensecretariat#67]
When checking how the ability card data was displayed in the app, I noticed two cases where the area attack placement was outside of the element consumption dashed line box, which can be confusing as the area attack could be interpreted as part of the default attack ability. The affected cards are 

- Flame Demon Explosive Blast
- Chaos Demon Seismic Punch. 

I couldn't figure out what may have been wrong with the data files for those two area attacks to be displaced, but my supposition is that the area attack is somehow misplaced in the data file. Here's an image of the actual card (left) with the app image (right): 
![subaction box](https://user-images.githubusercontent.com/121493484/211072123-4716de45-9dc9-4572-b360-574b8c937de7.png)

**Comment by Lurkars** [comment]
Thanks for the report. That definitely worked before, but must be created during some rework/other fixes! I will take a look and fix it.
