### ISSUE TITLE
Issues with item management in character sheets

### ISSUE THREAD

**Issue by z-m-k** [Lurkars/gloomhavensecretariat#72]
There are three issues with items and item form:

- [ ] when buying items that have discounts the displayed price of the item is adjusted for the discount, but clicking on the 'button loot' charges full list price. Then, if the character owns less gold than the list price while still being able to buy the item given discounts, the 'button loot' is disabled.
- [ ] the input box (the one allowing to select items by their numbers) is not visible on phones and on computers in full screen either because width is set to auto or because min-width is 0. Changing any of these causes overflow
- [ ] if character hoards items, the item box overflows

![Screenshot 2023-01-19 123735](https://user-images.githubusercontent.com/3216223/213432771-8f4ca307-bbac-4d72-b80f-7b4c2e39c13f.png)

**Comment by Lurkars** [comment]
Thanks. I will take a deeper look. That was one of the Q&D features I never revisited really.

**Comment by Likw3d** [comment]
Cant seem to see any items in the list at the moment.. they are adding but they still seem collapsed

**Comment by Likw3d** [comment]
It seems to be only on the frosthaven characters. gloomhaven are working
properly

**Comment by Lurkars** [comment]
Ah I see, it's a visual problem with the FH style sheet. Will move the items below the sheet and switch with actual notes!

**Comment by Lurkars** [comment]
Should be fixed in  [v0.43.1](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.43.1), please verify. (Item are now on the bottom for FH char sheet, because orig. sheet doesn't list items at all)

**Comment by Lurkars** [comment]
@Likw3d  can you verify fix and close if solved? Thanks.

**Comment by Likw3d** [comment]
Fixed
