### ISSUE TITLE
Incorrect Blinkblade Perk

### ISSUE THREAD

**Issue by mbpen** [Lurkars/gloomhavensecretariat#76]
Hi,

The Blinkblade has an incorrect perk as of v0.42.8, the remove a -1 and add a +1 should not have a rolling icon. The current version in the app is shown in the first screenshot, and the first printing of Frosthaven character sheet is shown in the second. I also included links to my raw scans of the character sheet and the unique AMD cards below. Thank you!

<img width="172" alt="Current" src="https://user-images.githubusercontent.com/121310896/213938873-42faf400-689b-4813-9891-a7db57a8a761.PNG">

<img width="360" alt="Sheet" src="https://user-images.githubusercontent.com/121310896/213938907-b5f2430e-8288-4018-8bf4-8f75bf4c9c23.PNG">

https://github.com/mbpen/FrosthavenUploads/blob/main/CharacterSheets/Raw/TIFF/Blinkblade.tif
https://github.com/mbpen/FrosthavenUploads/blob/main/AttackModifiers/Raw/TIFF/Blinkblade.tif

**Comment by Lurkars** [comment]
Thank, will be fixed!
