### ISSUE TITLE
Overlap of Loot/Monster AMD Toggle Icon With XP Indicator in Portrait Orientation

### ISSUE THREAD

**Issue by mbpen** [Lurkars/gloomhavensecretariat#77]
Depending on zoom and aspect ratio, the toggle icon for loot/monster AMD overlaps with the XP for scenario value. 2 suggestions for fixing: 1) include the toggle icon in setting the allowed width for displaying the scenario info values or 2) Move the toggle to the far bottom right (see screenshot, doesn't appear to overlap after drawing cards, would need more testing/validation most likely). Thank you!
<img width="540" alt="Option" src="https://user-images.githubusercontent.com/121310896/213939744-a58e9c41-ad24-44f7-8ea2-e49f220cb2a8.png">

**Comment by Lurkars** [comment]
Can you provide more information about resolution, device etc? On small screens, the AM deck should be above the bottom bar, so maybe your resolution is an edge case I need to consider more. See screenshot from mobile:
![image](https://user-images.githubusercontent.com/2760570/213940169-3ceff554-20b9-4757-86ef-6abcc108082d.png)

**Comment by mbpen** [comment]
This is on a 13" 1920 x 1080 windows laptop. This appears to be due to Windows scaling. I have it set to 150% scaling in the OS (which Windows marks as "recommended") to increase the size of the UI across the computer to be more readable. But, switching to 100% scaling has everything displaying nicely in Secretariat. I'm not sure how this gets reported to the app (1080 pixel width but 150% scaling) if it's possible to have a fix for OS display scaling induced issues?

Thanks!

**Comment by Lurkars** [comment]
I hope I found a solution and making the position depending on width of AM deck in comparison to width of bottom bar. Hope this will fix the issue for your screen and doesn't break on other devices.

**Comment by Lurkars** [comment]
Please check in [v0.48.9](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.42.9) and close issue if solved for you.

**Comment by mbpen** [comment]
Looks good at 100% and 150% scaling, thank you!
