### ISSUE TITLE
Suggestion: Increase the size of the click area of the Modifier Deck

### ISSUE THREAD

**Issue by pakoito** [Lurkars/gloomhavensecretariat#79]
Right now the area of the click corresponds only to the icon, which is very small specially on touchscreens. The button should extend the whole box with a more generous touch area.

https://github.com/Lurkars/gloomhavensecretariat/blob/ad8605592b6c646980dfe10dbf951b909376678d/src/app/ui/figures/character/character.scss#L254-L268

**Comment by Lurkars** [comment]
Yes, will take a look.

**Comment by pakoito** [comment]
Thanks :D

**Comment by Lurkars** [comment]
Please check in [v0.48.9](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.42.9)

**Comment by pakoito** [comment]
Sadly it has not, yet. I have checked in Firefox and Chrome.

![2023-01-23 20_35_37-Settings](https://user-images.githubusercontent.com/514871/214144445-9499fa3d-4d8a-4342-b63e-5d11ad0bd6d5.png)

**Comment by pakoito** [comment]
Oh gotcha, yeah :D Lemme check on the phone.

**Comment by pakoito** [comment]
Yeah, it looks better too!
