### ISSUE TITLE
Forgotten Circles - Incorrect Monster Type - Scenario #105

### ISSUE THREAD

**Issue by itemforty** [Lurkars/gloomhavensecretariat#81]
I submitted this through GHS feedback form already so sorry for the double post, but this feels like a better place to communicate if there's questions. 

Scenario #105 has two special, hybrid monsters, Wolf-Viper Abomination and Bear-Drake Abomination. However, when expanding the sections, the monsters added are just the basic cave bear and hounds. 

![image](https://user-images.githubusercontent.com/175024/214157169-e1501528-04eb-4fd8-8792-7c7024d10484.png)

Easy workaround is to add the "Hidden Monsters" manually, since you already have them in your database. 

![image](https://user-images.githubusercontent.com/175024/214157232-e4907caf-e7a2-4e8b-ae40-4ebc627a65fd.png)

Also this is for Forgotten Circles so it's probably moot at this point, but wanted to report it just in case there are others like me trying to complete everything else before Frosthaven lands. Thanks so much!

**Comment by Lurkars** [comment]
Thanks. I am currently still working on the FC Room/Section data for the adding automatic standees feature, and really, I got to #104 today. So everything > 104 needs to be checked and fixed I think. Just parsed the room data from TTS mod and it didn't use the special monster names of course. But yeah, this will be fixed anyways now.

**Comment by Lurkars** [comment]
Please validate fix in [v0.48.11](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.42.11)

**Comment by itemforty** [comment]
Verified working as expected. Thank you!
