### ISSUE TITLE
Missing Innate Named Monster Ability - Scenario 7 

### ISSUE THREAD

**Issue by mbpen** [Lurkars/gloomhavensecretariat#82]
The named monster in Scenario 7 has innate brittle per the section 48.4 special rules in the first printing of Frosthaven, which isn't shown in the app.

<img width="293" alt="Scenario7_BossInateAbility_Section" src="https://user-images.githubusercontent.com/121310896/214159243-80f23f67-7fd0-4cff-ba2f-f7273b0dd8e3.PNG">
<img width="686" alt="Scenario7_BossInateAbility" src="https://user-images.githubusercontent.com/121310896/214159248-b031aa99-f4af-407f-bac9-f3e76133f777.PNG">

**Comment by Lurkars** [comment]
Thanks, will be fixed soon.

**Comment by Lurkars** [comment]
Please validate fix in [v0.48.11](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.42.11)

**Comment by mbpen** [comment]
Innate brittle is there now, thank you!
