### ISSUE TITLE
Unclear Monster Ability Card - Lurker Clawcrusher Crush Armor

### ISSUE THREAD

**Issue by mbpen** [Lurkars/gloomhavensecretariat#83]
Lurker Clawcrusher Crush Armor ability card (695) has "consume earth, X is double their shield value instead", as displayed in the app, it's unclear what X is? I don't have our monster ability cards right now to upload the physical card wording, I could add on Wednesday if that is helpful?
<img width="688" alt="Clawcrusher_CrushArmor" src="https://user-images.githubusercontent.com/121310896/214159964-f8adba7e-fa8f-464a-9f62-9606656882e5.PNG">

**Comment by Lurkars** [comment]
This is actually a bug I created during JOTL special rules, the data is correct, but cards throws error due to the X value their and isn't shown properly. Will be fixed soon!

**Comment by Lurkars** [comment]
Please validate fix in [v0.48.11](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.42.11)

**Comment by mbpen** [comment]
The true damage text shows up now, thank you!
