### ISSUE TITLE
Nail Spheres has 3 summons

### ISSUE THREAD

**Issue by JP-Ellis** [Lurkars/gloomhavensecretariat#91]
The circle's "Nail Spheres" summons has 3 characters. I noticed you fixed some of the other summons to prompt for the additional summons, but it appears that Nail Spheres is still incorrect.

**Comment by Lurkars** [comment]
Thanks. Should be fixed in [v0.42.17](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.42.17)
