### ISSUE TITLE
Incorrect section linking in Scenario 8

### ISSUE THREAD

**Issue by mbpen** [Lurkars/gloomhavensecretariat#92]
The section linking is incorrect in Scenario 8 for the 2nd section. Currently links to 29.2 and unveils the blacksmith. Should be linked to 12.1 and add 1 polar bear (normal for 2, elite for 3/4 player).

Thank you!

<img width="695" alt="Scenario8" src="https://user-images.githubusercontent.com/121310896/215305697-e32abf8c-45f9-49be-bd4d-72c7ef77a346.PNG">

![PXL_20230129_040316109](https://user-images.githubusercontent.com/121310896/215305772-72fc2669-f216-411e-baec-cb1466545fcb.jpg)
![PXL_20230129_040338916](https://user-images.githubusercontent.com/121310896/215305777-e7e66105-e2ab-40fd-b107-6955981beff9.jpg)

**Comment by Lurkars** [comment]
Thanks. Should be fixed in [v0.42.18](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.42.18)
