### ISSUE TITLE
Touch scrolling inhibited on inactive monster ability cards

### ISSUE THREAD

**Issue by mbpen** [Lurkars/gloomhavensecretariat#93]
I believe this is new after fixing #87, when using touch scrolling, if the touch starts on an inactive (no standees) monster ability card, the app does not scroll.

Thank you!

**Comment by Lurkars** [comment]
Can reproduce. Will be fixed soon! Thanks.

**Comment by Lurkars** [comment]
Please verify fix in [v0.43.0](https://github.com/Lurkars/gloomhavensecretariat/releases/tag/v0.43.0).

**Comment by mbpen** [comment]
Working great, thank you!
