### ISSUE TITLE
The help page is unavailable

### ISSUE THREAD

**Issue by TijmenvanderKemp-Leap** [Lurkars/gloomhavensecretariat#97]
Navigating to this URL: https://help.gloomhaven-secretary.de/ gives me the following error:
<img width="805" alt="Screenshot 2023-01-31 at 14 23 37" src="https://user-images.githubusercontent.com/85866362/215772376-d3d5f406-73a2-4f33-80f3-67ca06460539.png">

**Comment by Lurkars** [comment]
Thanks for reporting. Should have come with publishing the version archive. Should be fixed now!
